### PR TITLE
fixes #7602: calling `jj metaedit --author-timestamp` twice should not edit twice

### LINKED ISSUE #7602: `jj metaedit --author-timestamp` should not rewrite a revision if the new timestamp matches the old one
## Description

`jj metaedit --author-timestamp SOME_TIMESTAMP` should not rewrite the revision if `SOME_TIMESTAMP` matches the current author timestamp. Unfortunately this is not always the case.

## Steps to Reproduce the Problem

```bash
jj git init example
cd example
jj metaedit --author-timestamp "2025-09-27 15:08:33+02:00"
jj metaedit --author-timestamp "2025-09-27 15:08:33+02:00"
```
The expectation is that the second call should just say "Nothing changed". Instead the revision is edited again (and a new git commit is created under the hood.

## Specifications

- Platform: macOS 15.6.1
- Version: jj 0.33.0

### PR DESCRIPTION
**Pull request by AngelEzquerra**
I also added a test. I made a separate test case because that's how I was able to reproduce the issue.

# Checklist

If applicable:

- [x ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [ x] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/commands/metaedit.rs [hunk 1]
```diff
@@ -175,7 +175,7 @@ pub(crate) fn cmd_metaedit(
                 // changes.
                 if new_author.name != old_author.name
                     || new_author.email != old_author.email
-                    || new_author.timestamp != commit_builder.author().timestamp
+                    || new_author.timestamp != old_author.timestamp
```
Comment (yuja) [inline cli/src/commands/metaedit.rs]: This would break `jj metaedit` (with no arguments) when the target commit is discardable. I thought this would be covered by the test, but apparently not.

File: cli/tests/test_metaedit_command.rs [hunk 2]
```diff
@@ -485,6 +485,37 @@ fn test_update_empty_author() {
...
+
+    // Running it again with the same date has no effect
+    let output = work_dir
+        .run_jj([
+            "metaedit",
+            "--author-timestamp",
+            "2001-02-03 04:05:14.000+07:00",
+        ])
+        .success();
+    insta::assert_snapshot!(output.stderr, @r"
```
Comment (yuja) [inline cli/tests/test_metaedit_command.rs]: nit: just snapshot the `output`.

File: cli/src/commands/metaedit.rs (hunk 1 above)
Comment (AngelEzquerra) [reply cli/src/commands/metaedit.rs]: OK, so I think the solution is keeping the old check as well.

File: CHANGELOG.md [hunk 3]
```diff
@@ -79,6 +79,9 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
   is set in `.gitconfig` (but jj still isn't able to fetch the submodules
   or to operate on them).
 
+* `jj metaedit --author-timestamp` twice with the same value no longer
+edits the change twice in some cases.
```
Comment (yuja) [inline CHANGELOG.md]: nit: you'll need to rebase and move this to the unreleased section.

File: cli/tests/test_metaedit_command.rs [hunk 4]
```diff
@@ -485,6 +485,38 @@ fn test_update_empty_author() {
...
+        .success();
+
+    // Running it again with the same date has no effect
+    let output = work_dir
+        .run_jj([
+            "metaedit",
+            "--author-timestamp",
+            "2001-02-03 04:05:14.000+07:00",
+        ])
+        .success();
```
Comment (yuja) [inline cli/tests/test_metaedit_command.rs]: nit: `.success()` can be omitted since the output is snapshotted.

File: cli/tests/test_metaedit_command.rs [hunk 5]
```diff
@@ -485,6 +485,38 @@ fn test_update_empty_author() {
...
+
+    // Set the author-timestamp to the same value twice
+    // and check that the second time it does nothing
+    work_dir
+        .run_jj([
+            "metaedit",
+            "--author-timestamp",
+            "2001-02-03 04:05:14.000+07:00",
+        ])
+        .success();
```
Comment (yuja) [inline cli/tests/test_metaedit_command.rs]: nit: snapshot the output as well (instead of `.success())`? I think it's better to ensure that the commit is rewritten by this command.

**Review by yuja — APPROVED** [review]
Thanks.
