### PR TITLE
id_prefix: check conflicting bookmarks/tags when calculating shortest length

### LINKED ISSUE #2416: Conflicting {change, commit}.shortest() and branch name
## Description

I have a change for which jj reports the shortest change ID is `l`, but turns out there's an (old) branch in the repo named `l` (which jj resolves to, when asked for `l`), but I would probably expect for jj to resolve to both (out of caution) or maybe consider branches (and other references) when reporting shortest, so this is not an issue in the first place.

## Steps to Reproduce the Problem

Pick {change, commit}.shortest() from a random commit and create a new branch with the same name on another commit.

### PR DESCRIPTION
**Pull request by yuja**
Fixes #2416

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/id_prefix.rs [hunk 1]
```diff
@@ -244,6 +255,21 @@ impl IdPrefixIndex<'_> {
...
+    (min_len..id_sym.len())
+        .find(|&n| {
+            // Tags, bookmarks, and Git refs have higher priority, but Git refs
+            // should include "/" char. Extension symbols have lower priority.
+            let prefix = &id_sym[..n];
+            view.get_tag(prefix.as_ref()).is_absent()
+                && view.get_local_bookmark(prefix.as_ref()).is_absent()
+        })
+        // No need to test conflicts with the full ID. We have to return some
+        // valid length anyway.
```
Comment (martinvonz) [inline lib/src/id_prefix.rs:269]: Perhaps we should check when resolving a bookmark or tag if it also matches a commit id or change id. If it does, we could print a warning. But that's something we can decide later.

Comment (yuja) [reply lib/src/id_prefix.rs:269]: We can also prioritize full change/commit ID resolution, but the situation where all prefixes are shadowed by tags/bookmarks would be pretty rare.

Comment (martinvonz) [reply lib/src/id_prefix.rs:269]: I was thinking of the case where someone has accidentally created a bookmark with a full commit id or change id as name because they misused some command. Perhaps something like this:

```
COMMIT_ID=$(...)
jj bookmark create my-bookmark $COMMIT_ID
```

I've seen people do that with hg.

Comment (yuja) [reply lib/src/id_prefix.rs:269]: I mean there would usually be shorter prefix `$COMMIT_ID[..len - 1]` to return.

A warning might be nice, btw.
