### PR TITLE
git_backend: do not include renamed trees in copy records

### LINKED ISSUE #6390: diff: panic when file and directory swap names
## Description

The following panic occurs if a file and a directory have their names swapped:

    thread 'main' panicked at cli/src/diff_util.rs:1240:13:
    Unexpected tree in diff at path "b"
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The same thing happens if the two entities are a directory and a symlink.

## Steps to Reproduce the Problem

Tested within a blank repo with jj 0.28.2:

    $ echo 'first file' > a
    $ mkdir b
    $ echo 'second file' > b/file
    $ jj new
    Working copy  (@) now at: toulwzts a0a5d2cd (empty) (no description set)
    Parent commit (@-)      : tlqysmuz 52817723 (no description set)
    $ mv a a~
    $ mv b a
    $ mv a~ b
    $ jj diff

    thread 'main' panicked at cli/src/diff_util.rs:1240:13:
    Unexpected tree in diff at path "b"
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

For convenience, I've also included the test repo here: https://github.com/mernen/jj-diff-test

## Expected Behavior

Should be presented as two renames. Git output, for comparison:

    $ git --git-dir=$(jj git root) show $(jj log --no-graph -T commit_id -r @)

    commit 05f6679114b0403c812ad7b709f2c666812f1bc6
    Author: Daniel Luz <dev.gsz@mernen.com>
    Date:   Sun Apr 20 16:03:31 2025 -0300

    diff --git a/b/file b/a/file
    similarity index 100%
    rename from b/file
    rename to a/file
    diff --git a/a b/b
    similarity index 100%
    rename from a
    rename to b

## Actual Behavior

Panic in diff_util.rs:

https://github.com/jj-vcs/jj/blob/b9ebe2f03c976515d2a155a411a368ae773c5493/cli/src/diff_util.rs#L925-L927

## Specifications

- Platform: macOS
- Version: 0.28.2

### PR DESCRIPTION
**Pull request by yuja**
Fixes #6390

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

File: lib/src/git_backend.rs [hunk 1]
```diff
@@ -1352,13 +1352,20 @@ impl Backend for GitBackend {
...
                     ..
                 } = change
                 else {
                     return Ok(None);
                 };
+                // TODO: Renamed symlinks cannot be returned because CopyRecord
+                // expects `source_file: FileId`.
+                if !source_entry_mode.is_blob() || !dest_entry_mode.is_blob() {
+                    return Ok(None);
+                }
```
Comment (martinvonz) [inline lib/src/git_backend.rs:1368]: I'm a bit surprised that we get tree entries from Gitoxide. I wonder if that's a bug or intentional. I can see it easily being a bug that happens due to comparing tree entries exactly as a first step.

**Review by martinvonz — APPROVED** [review]
Thanks!

File: lib/src/git_backend.rs (hunk 1 above)
Comment (yuja) [reply lib/src/git_backend.rs:1368]: `gix` appears to emit directory rename entry even if new file is added to the directory. So I think it's intentional?
