### PR TITLE
cli: fix race condition in Git HEAD import/export

### LINKED ISSUE #6830: jj creates divergent operations without any user input whatsoever
## Description

jj creates divergent operations (and changes) when just typing into the editor - no commands required to run.

I have a theory on what the problem is (see actual behaviour section)

## Steps to Reproduce the Problem
No commands involved, but I believe this is due to `core.watchman.register-snapshot-trigger = true`. I suspect the feature has race conditions that trigger when:
* You're on a large repo (thus the snapshot takes longer - ~1 second for me)
* You're using an editor that automatically saves files for you very frequently (I'm using vscode)

I get divergent changes in my jj log arbitrarily, after not having run any jj commands.

My op log contains:
```
@  cbda09db69fd msta@msta2.c.googlers.com 1 minute ago, lasted 1 second
│  snapshot working copy
│  args: jj debug snapshot
○    4bf1c16327ae msta@msta2.c.googlers.com 1 minute ago, lasted 965 milliseconds
├─╮  reconcile divergent operations
│ │  args: jj debug snapshot
○ │    f6ff969db703 msta@msta2.c.googlers.com 1 minute ago, lasted 932 milliseconds
├───╮  reconcile divergent operations
│ │ │  args: jj debug snapshot
○ │ │  9594d9b3678a msta@msta2.c.googlers.com 1 minute ago, lasted 1 second
│ │ │  snapshot working copy
│ │ │  args: jj debug snapshot
│ ○ │  6e6f484ee8d9 msta@msta2.c.googlers.com 1 minute ago, lasted 1 second
│ ├─╯  snapshot working copy
│ │    args: jj debug snapshot
│ ○  2a563ca5d0de msta@msta2.c.googlers.com 1 minute ago, lasted 1 second
├─╯  snapshot working copy
│    args: jj debug snapshot
○  680b07ec0f8d msta@msta2.c.googlers.com 4 minutes ago, lasted 1 second
│  snapshot working copy
│  args: jj debug snapshot
○  88e1d6aa889c msta@msta2.c.googlers.com 4 minutes ago, lasted 1 second
│  snapshot working copy
│  args: jj debug snapshot
...
```

## Expected Behaviour

I expect to not have divergent changes

## Actual Behaviour

jj creates two divergent changes. My theory is that:
1) the user starts typing "ab". Vscode saves mid-sentence with only the content "a"
1) Watchman sees a filesystem change and triggers a snapshot operation
1) jj starts to create a new snapshot operation `2a56` based off the current op head (`680b` in the example above)
1) jj reads the content "a" to the snappshot `2a56`
1) vscode writes "ab" to the file, triggering watchman's snapshot operation again
1) jj starts to create a new snapshot operation `9594` based off the current op head (`680b` in the example above)
1) jj writes the content "ab" to the snapshot `9594`
1) Both operations complete, creating divergent changes
1) Divergent changes merge

If this theory is correct, then the solution I would propose is to, after completing a snapshot operation from watchman, check if the op head has changed, and if it has, you discard the current operation instead of attempting to reconcile it.

## Specifications

- Platform: Linux
- Version: 0.29.0

### PR DESCRIPTION
**Pull request by sheremetyev**
Closes #6830

Fixes divergence caused by concurrent operations importing and exporting Git HEAD by protecting Git HEAD operations with the working copy lock. Conceptually, Git HEAD is part of the working copy state and should be protected by the same lock. Other Git refs belong to the repository and can still be updated asynchronously, preserving Jujutsu's concurrent design.

Added a probabilistic test that reproduces the issue most of the time, on Linux and macOS.

For manual testing: do `jj new` on an old commit on the trunk of a repository that's not too small (for example, the JJ repo), then run the following two loops in separate terminals:

```
while jj status; do done

while sleep 1 && jj next; do done
```

Prior to the change, I quickly get "Concurrent checkout" errors and divergent operations creating empty commits. After the change, both loops run smoothly in parallel. Tested on macOS 15.6.1.

### CODE REVIEW

File: cli/src/cli_util.rs
Comment (martinvonz) [inline cli/src/cli_util.rs:1]: nit: This commit does a few different things. It would have been easier to review if they had been split out:

1. Inline `WorkspaceCommandHelper::update_working_copy()`. Good change on its own IMO.
2. Replace `update_working_copy()` by `update_working_copy_locked()`. Should be possible to make this change without changing where we take the lock, right?
3. Take the lock before exporting Git HEAD.
4. Take the lock before importing Git HEAD.

I tried to do this in https://github.com/jj-vcs/jj/compare/main...mz/lospzquksypn . Could you take a look and see if I did it correctly and update your branch if it looks good? Feel free to reset the author to be you.

File: cli/src/cli_util.rs [hunk 1]
```diff
@@ -2101,11 +2141,24 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
         // don't leave the working copy in a stale state.
         if self.may_update_working_copy {
             if let Some(new_commit) = &maybe_new_wc_commit {
-                self.update_working_copy(ui, maybe_old_wc_commit.as_ref(), new_commit)?;
+                let locked = locked_ws
+                    .take()
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: unnecessary?

File: cli/src/cli_util.rs [hunk 2]
```diff
@@ -2075,12 +2096,31 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
...
 
+        // Determine if we need to acquire the WC lock:
+        // - If we're exporting Git HEAD (colocated repo with new WC commit)
+        // - OR if we're updating the working copy files
+        let need_wc_lock = {
+            #[cfg(feature = "git")]
+            let git_head_export =
+                self.working_copy_shared_with_git && maybe_new_wc_commit.is_some();
+            #[cfg(not(feature = "git"))]
+            let git_head_export = false;
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: We try to use `cfg!()` instead when possible so we always compile-test both branches. It also helps with code navigation.

Actually, do we even need to check the `git` feature? If it's disabled, then `self.working_copy_shared_with_git` should be false anyway.

File: cli/src/cli_util.rs
Comment (sheremetyev) [reply cli/src/cli_util.rs:1]: Thanks very much for splitting @martinvonz! Makes sense. I've updated PR branch to commits from your branch and tweaked titles to make GitHub Action happy. Also re-tested the fix, and checked that it rebases cleanly onto the latest "main" and still works (didn't push rebase to keep PR history cleaner).

File: cli/src/cli_util.rs (hunk 1 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Indeed! Looks more similar to the another side of `if` that is doing `take()` but not really necessary here.

File: cli/src/cli_util.rs (hunk 2 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Yep, `git` feature check is not need - thank you!

File: cli/src/cli_util.rs
Comment (martinvonz) [inline cli/src/cli_util.rs:1]: The last commit message seems stale now. The second-to-last one could also use some more details. In particular, I think it would be useful if it explained the scenario that causes divergence before that commit. (Sorry, I just put a brief description in because the commits were mostly a way for me to share with you what I meant.)

Actually, explaining the problem would be useful in the last commit message too.

Comment (martinvonz) [inline cli/src/cli_util.rs:1]: Add "Closes #6830" to the PR description or the last commit description (I don't remember which is better)? Or is there anything else left to do for that bug?

Comment (martinvonz) [inline cli/src/cli_util.rs:1]: It seems like we should mention this fix in the changelog, no?

File: cli/src/cli_util.rs [hunk 3]
```diff
@@ -2085,9 +2100,9 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
         // don't leave the working copy in a stale state.
         if self.may_update_working_copy {
             if let Some(new_commit) = &maybe_new_wc_commit {
-                let locked_ws = self.workspace.start_working_copy_mutation()?;
+                let locked = locked_ws.expect("locked_ws should be held if updating WC");
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: Call this new variable `locked_ws` too? We frequently redefine variables like that when they have similar types (and we do it on line 2116)

File: cli/src/cli_util.rs [hunk 4]
```diff
@@ -2059,12 +2059,27 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
...
+                self.working_copy_shared_with_git && maybe_new_wc_commit.is_some();
+            let wc_update = self.may_update_working_copy && maybe_new_wc_commit.is_some();
+            git_head_export || wc_update
+        };
+
+        let mut locked_ws = if need_wc_lock {
+            Some(self.workspace.start_working_copy_mutation()?)
+        } else {
+            None
+        };
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: Can combine these since `need_wc_lock` isn't needed later:

```rust
        let mut locked_ws = {
            let git_head_export =
                self.working_copy_shared_with_git && maybe_new_wc_commit.is_some();
            let wc_update = self.may_update_working_copy && maybe_new_wc_commit.is_some();
            let need_wc_lock = git_head_export || wc_update;
            if need_wc_lock {
                Some(self.workspace.start_working_copy_mutation()?)
            } else {
                None
            }
        };
```

Feel free to also inline `need_wc_lock`.

File: cli/src/cli_util.rs [hunk 5]
```diff
@@ -1130,32 +1130,67 @@ impl WorkspaceCommandHelper {
     #[instrument(skip_all)]
     fn import_git_head(&mut self, ui: &Ui) -> Result<(), CommandError> {
         assert!(self.may_update_working_copy);
-        let mut tx = self.start_transaction();
+
+        // Extract values needed before acquiring lock
+        let old_repo_op_id = self.repo().op_id().clone();
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: I'd drop the `repo_` in the name so it doesn't sound like it's for another repo (it's old precisely in the sense that it's from a different operation)

File: cli/src/cli_util.rs [hunk 6]
```diff
@@ -1130,32 +1130,67 @@ impl WorkspaceCommandHelper {
...
+        let workspace_name = self.workspace_name().to_owned();
+        let repo = self.repo().clone();
+        let string_args = self.env.command.string_args().clone();
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: can inline this where it's used and avoid the `.clone()`

File: cli/src/cli_util.rs [hunk 7]
```diff
@@ -1130,32 +1130,67 @@ impl WorkspaceCommandHelper {
...
+        let repo = if wc_operation_id != old_repo_op_id {
+            // The WC operation differs from what we loaded. This can happen in two cases:
+            // 1. Another process created a new operation and updated the WC (need to
+            //    reload)
+            // 2. We loaded a newer repo than the WC is at (e.g., during init - don't
+            //    reload)
+            //
+            // To distinguish: check if the WC operation is an ancestor of our repo.
+            // If our repo operation has the WC operation as a parent, the WC is older.
+            let repo_operation = repo.loader().load_operation(&old_repo_op_id)?;
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: i.e. `repo.operation()`?

File: cli/src/cli_util.rs [hunk 8]
```diff
@@ -1130,32 +1130,67 @@ impl WorkspaceCommandHelper {
...
+            let wc_is_ancestor = repo_operation.parent_ids().contains(&wc_operation_id);
+
+            if wc_is_ancestor {
+                // WC is older than repo (normal during init), don't reload backwards
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: Maybe we should update the working copy's operation id during init instead?

**Review by martinvonz — COMMENTED** [review]
Would it be hard to add tests? I understand that it will be hard to write tests that are guaranteed to fail without the locks but maybe it's not too hard to write tests that are quite likely to fail without locks. It would be nice to have tests for both the export and import problems.

File: cli/src/cli_util.rs [hunk 9]
```diff
@@ -2059,12 +2059,27 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
...
+        } else {
+            None
+        };
+
         #[cfg(feature = "git")]
         if self.working_copy_shared_with_git {
             use std::error::Error as _;
             if let Some(wc_commit) = &maybe_new_wc_commit {
-                // This can fail if HEAD was updated concurrently. In that case,
-                // the actual state will be imported on the next snapshot.
```
Comment (yuja) [inline cli/src/cli_util.rs:2096]: I think this comment is still valid. Another `jj` process may update working copy after the current process imported Git HEAD, but before exporting new Git HEAD.

File: cli/src/cli_util.rs [hunk 10]
```diff
@@ -1130,32 +1130,67 @@ impl WorkspaceCommandHelper {
...
-        let mut tx = self.start_transaction();
+
+        // Extract values needed before acquiring lock
+        let old_repo_op_id = self.repo().op_id().clone();
+        let workspace_name = self.workspace_name().to_owned();
+        let repo = self.repo().clone();
+        let string_args = self.env.command.string_args().clone();
+
+        // Acquire lock BEFORE reading Git HEAD to prevent races
+        let mut locked_ws = self.workspace.start_working_copy_mutation()?;
```
Comment (yuja) [inline cli/src/cli_util.rs]: Since it isn't technically needed to protect the working copy to update Git HEAD, etc., isn't it simpler to add another lock file? I don't think the extra I/O for locking would matter here because snapshotting would be I/O heavy operation.

File: cli/src/cli_util.rs [hunk 11]
```diff
@@ -1130,32 +1130,67 @@ impl WorkspaceCommandHelper {
...
+
+        // Check if another process already updated the working copy while we were
+        // waiting for the lock. If so, reload the repo at the new operation to
+        // avoid creating divergent operations.
+        let wc_operation_id = locked_ws.locked_wc().old_operation_id().clone();
+        let repo = if wc_operation_id != old_repo_op_id {
```
Comment (yuja) [inline cli/src/cli_util.rs]: Maybe we can reuse `WorkingCopyFreshness::check_stale()`, but I'm not sure.

File: cli/src/cli_util.rs (hunk 3 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: renamed

File: cli/src/cli_util.rs (hunk 4 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: inlined

File: cli/src/cli_util.rs (hunk 5 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: dropped

File: cli/src/cli_util.rs (hunk 6 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: inlined

File: cli/src/cli_util.rs (hunk 7 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: replaced

**Comment by sheremetyev** [comment]
> Would it be hard to add tests? I understand that it will be hard to write tests that are guaranteed to fail without the locks but maybe it's not too hard to write tests that are quite likely to fail without locks. It would be nice to have tests for both the export and import problems.

Yes, would be nice to prevent regression in the future. Added a test in a commit before fixes. It fails not every time but fairly consistently. Please see https://github.com/jj-vcs/jj/actions/runs/19165261133 for a CI run where it failed on Linux and macOS.

File: cli/src/cli_util.rs [hunk 12]
```diff
@@ -2059,12 +2059,25 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
...
+        };
+
         #[cfg(feature = "git")]
         if self.working_copy_shared_with_git {
             use std::error::Error as _;
             if let Some(wc_commit) = &maybe_new_wc_commit {
-                // This can fail if HEAD was updated concurrently. In that case,
-                // the actual state will be imported on the next snapshot.
+                // Export Git HEAD while holding the WC lock to prevent races
                 match jj_lib::git::reset_head(tx.repo_mut(), wc_commit) {
```
Comment (yuja) [inline cli/src/cli_util.rs:2150]: This is an idea for future change, but I think we can get rid of `view.git_head` and `view.git_refs` by deprecating revset/template functions. These fields track the last known Git state and will never be restored on `jj undo`. Therefore, these fields can be extracted to a separate storage, and `git::reset_head()` can be moved after `tx.commit()`.

I think we have had a failed attempt for this change, but we didn't have `@git` remote at that time.

File: cli/src/cli_util.rs (hunk 8 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Updated "init" command implementation and simplified `import_git_head`

Comment (martinvonz) [reply cli/src/cli_util.rs]: Thanks! Could you move the for for `init` earlier in the stack and squash the simplification of `import_git_head()` into the parent? Then we won't have an intermediate step where it's unnecessarily complicated.

File: cli/src/commands/git/init.rs [hunk 13]
```diff
@@ -182,7 +182,14 @@ fn do_init(
             // chronological order.
             let colocated = is_colocated_git_workspace(&workspace, &repo);
             let repo = init_git_refs(ui, repo, command.string_args(), colocated)?;
+            let new_repo_op_id = repo.op_id().clone();
             let mut workspace_command = command.for_workable_repo(ui, workspace, repo)?;
+            // Update WC operation id if init_git_refs created a new operation
+            if workspace_command.workspace().working_copy().operation_id() != &new_repo_op_id {
+                let (locked_ws, _wc_commit) =
+                    workspace_command.unchecked_start_working_copy_mutation()?;
```
Comment (martinvonz) [inline cli/src/commands/git/init.rs]: Will `start_working_copy_mutation()` not work? That seems like what we should generally use when possible.

Comment (sheremetyev) [reply cli/src/commands/git/init.rs]: That works, updated - thanks!

File: cli/src/cli_util.rs (hunk 9 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs:2096]: Good point! I've updated to this wording - please let me know if it need any correction.

```
// Export Git HEAD while holding the WC lock to prevent races:
// - Between two finish_transaction calls updating HEAD
// - With import_git_head importing HEAD concurrently
// This can still fail if HEAD was updated concurrently by a non-JJ process
// (e.g., git checkout). In that case, the actual state will be imported on
// the next snapshot.
```

File: cli/src/cli_util.rs (hunk 10 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: I think a separate lock would be less correct. Git HEAD and the working copy are operationally coupled: `import_git_head` updates the WC when HEAD changes, and `finish_transaction` exports HEAD based on the WC commit's parent - they describe the working copy state together. A single lock keeps updates atomic and avoids deadlock risks from lock ordering.

File: cli/src/cli_util.rs (hunk 11 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: `check_stale` doesn't seem to be applicable - it is comparing WC to commit first, while we care about consistency of operation ID with repository state.

File: cli/src/cli_util.rs (hunk 8 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: sure, done!

File: cli/src/cli_util.rs
Comment (sheremetyev) [reply cli/src/cli_util.rs:1]: Updated commits messages - please let me know if any other details/corrections needed!

Comment (sheremetyev) [reply cli/src/cli_util.rs:1]: Added to PR description. I believe this change should be sufficient to resolve the issue.

Comment (sheremetyev) [reply cli/src/cli_util.rs:1]: Didn't touch it previously to avoid conflicts in CHANGELOG.md. Added a line now and will move it to correct section after rebase.

File: cli/src/cli_util.rs (hunk 9 above)
Comment (yuja) [reply cli/src/cli_util.rs:2096]: It's not only non-jj processes.

1. jj-1 `maybe_snapshot()`
2. jj-2 `maybe_snapshot()`
3. jj-2 `finish_transaction()` updates HEAD and working copy
4. jj-1 `finish_transaction()` tries to update HEAD and working copy, leaving the working copy stale.

The changes made by jj-1 are still committed to the operation log, so the work wouldn't be lost. However, jj-1 doesn't update the working copy because it knows there were concurrent updates after jj-1's snapshot.

File: cli/src/cli_util.rs (hunk 10 above)
Comment (yuja) [reply cli/src/cli_util.rs]: The concern of `WorkingCopy::start_mutation()` is to protect its internal state, and Git HEAD isn't included in it. We could rely on working-copy's internal locking to address caller's problem, but that's kind of an abuse. I'm not against reusing the lock for different purposes if that's easy, though.

File: cli/src/cli_util.rs (hunk 11 above)
Comment (yuja) [reply cli/src/cli_util.rs]: afaict, check_stale() compares tree ids as a fast path. If the tree is unchanged, it's safe to create a divergent operation and merge later. I'm not pretty sure if the same rule applies to `import_git_head()`, but I think the situation would be similar.

BTW, as a follow up, I think `maybe_snapshot()` can be refactored in a way that it first checks stale working copy or operation, not twice.

1. lock
2. `check_stale()` and reload operation if needed
3. `import_git_head()`
4. `snapshot_working_copy()`

File: cli/src/cli_util.rs (hunk 9 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs:2096]: Ah, thank you for pointing that out! You're absolutely right - overlapping transactions from other JJ processes can also update HEAD, not just non-JJ processes.

I've updated the comment in change `orzlokwy` to acknowledge this:

```
// This can still fail if HEAD was updated concurrently by another JJ process
// (overlapping transaction) or a non-JJ process (e.g., git checkout). In that
// case, the actual state will be imported on the next snapshot.
```

And I've added a fix (in a new change `kysymxts`) that merges with concurrent operations after acquiring the working copy lock. This prevents the "Failed to update Git HEAD ref" error by ensuring our transaction incorporates any concurrent changes before updating HEAD. After the fix, the comment reverts to only mentioning non-JJ processes, since overlapping JJ transactions are now handled.

The way I think about this is that transactions on the repo can finish asynchronously and be reconciled later, unless they touch the working copy. In the latter case, they need to be serialised via the working copy lock.

Does this approach make sense? Please let me know if you'd rather remove the fix from this PR - it's not strictly about the race on Git HEAD.

**Comment by sheremetyev** [comment]
Rebased onto latest "main" in 884cdf0f - there were conflicts.

File: cli/src/cli_util.rs (hunk 9 above)
Comment (yuja) [reply cli/src/cli_util.rs:2096]: > I've updated the comment in change `orzlokwy` to acknowledge this:

LG, thanks.

> And I've added a fix (in a new change `kysymxts`) that merges with concurrent operations after acquiring the working copy lock.

I don't think we should make `finish_transaction()` more complex. If the concurrent updates can be fixed by just merging operations, it should be resolved by the next `jj` run. The user should be informed that they did something weird things (such as snapshotting changes while interactive `jj split` was in progress.)

I think we should instead make `update_working_copy()` not fail by `CheckoutError::ConcurrentCheckout` as the TODO comment suggests.

Comment (sheremetyev) [reply cli/src/cli_util.rs:2096]: Extracted last two commits into #7988 to not block this PR

**Comment by sheremetyev** [comment]
Rebased in e46f1df6

File: cli/tests/test_concurrent_operations.rs [hunk 14]
```diff
@@ -227,6 +227,115 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+            }
+        })
+    };
+
+    snapshot_handle.join().unwrap();
+    next_handle.join().unwrap();
+
+    // Check for divergent operations
+    let output = work_dir.run_jj(["op", "log", "-T", "description"]);
+    let divergent_count = output
```
Comment (martinvonz) [inline cli/tests/test_concurrent_operations.rs]: nit: maybe `concurrent_count` is better? `divergent` made me think of divergent commits. While divergent commits are often created by concurrent operations, I think what we care about here is concurrent operations. Also "divergent operations" -> "concurrent operations" in the message

File: cli/tests/test_concurrent_operations.rs [hunk 15]
```diff
@@ -227,6 +227,115 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+        .raw()
+        .lines()
+        .filter(|line| line.contains("reconcile divergent operations"))
+        .count();
+
+    if divergent_count > 0 {
+        eprintln!("Found {divergent_count} divergent operations:");
+        eprintln!("{}", output.stdout.raw());
+        panic!("Race condition detected: {divergent_count} divergent operations found");
+    }
```
Comment (martinvonz) [inline cli/tests/test_concurrent_operations.rs]: nit: It should not be an error in the first commit because we want tests to pass at every commit. You can comment out `panic!` line and add a `// TODO: Should never panic` above it or something like that, and then you remove the TODO and make it panic in the commit that fixes the bug.

File: cli/tests/test_concurrent_operations.rs [hunk 16]
```diff
@@ -227,6 +227,115 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+
+    let repo_path = work_dir.root().to_path_buf();
+    let duration = std::time::Duration::from_secs(5);
+    let start = std::time::Instant::now();
+
+    let snapshot_handle = {
+        let jj_bin = jj_bin.clone();
+        let repo_path = repo_path.clone();
+        let base_env = base_env.clone();
+        std::thread::spawn(move || {
```
Comment (martinvonz) [inline cli/tests/test_concurrent_operations.rs]: nit: I think you can use `std::thread::scope()` and not have to clone the variables and `move` the closure. You would use a single scope for both threads.

File: cli/tests/test_concurrent_operations.rs [hunk 17]
```diff
@@ -227,6 +227,115 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+            while start.elapsed() < duration {
+                // Snapshot repeatedly without delay
+                let mut cmd = std::process::Command::new(&jj_bin);
+                cmd.current_dir(&repo_path);
+                cmd.args(["debug", "snapshot"]);
+                for (key, value) in &base_env {
+                    if let Some(value) = value {
```
Comment (martinvonz) [inline cli/tests/test_concurrent_operations.rs]: nit: You can use `.filter_map()` on line 270 and not need this check

File: cli/tests/test_concurrent_operations.rs (hunk 14 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs]: updated

File: cli/tests/test_concurrent_operations.rs (hunk 15 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs]: added `#[should_panic]` (and later removed)

File: cli/tests/test_concurrent_operations.rs (hunk 16 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs]: updated

File: cli/tests/test_concurrent_operations.rs (hunk 17 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs]: updated

**Comment by sheremetyev** [comment]
Rebased in b4877d3e. @yuja, @martinvonz thanks for the reviews! I think I addressed all comments - anything blocking this fix from landing?

**Comment by yuja** [comment]
Any thoughts on https://github.com/jj-vcs/jj/pull/7895#discussion_r2502021956 ? I think a separate lock file will simplify lifetime issues of working copy object.

> I think I addressed all comments

Feel free to mark comments as resolved when they get addressed.

File: cli/src/cli_util.rs (hunk 10 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Thanks for the feedback! I understand the abstraction abuse concern, but I believe the single-lock approach is more correct. I've expanded my arguments below.

### Git HEAD and Working Copy Are Semantically Coupled

These operations maintain a consistency invariant in colocated repos:
- `import_git_head` reads Git HEAD, then updates both the WC commit and operation_id atomically
- `reset_head` exports Git HEAD based on `wc_commit.parent_ids()[0]`
- Git HEAD represents "what the working copy is based on" - they describe the same state

The test demonstrates this: concurrent import/export creates divergent operations precisely because these operations need serialisation.

### Concerns with Separate Locks

This would introduce new complexity:

- **Lock ordering**: We'd need strict rules to prevent deadlock (e.g., always acquire git-head.lock before working-copy.lock)
- **The reload-on-lock pattern breaks**: The fix checks if another process updated the WC while waiting, then reloads at that operation. This prevents divergent operations and only works cleanly with a single lock

How would separate locks handle the reload scenario while maintaining consistency?

### Abstraction Evolution

The original `WorkingCopy` abstraction was designed before we discovered this race condition. Sometimes discovering a real bug reveals that related concepts need coordinated access, even if they seem separate abstractly.

Proposal: document the dual purpose explicitly in `WorkingCopy::start_mutation()`. This makes the extended scope intentional. Hope this fix doesn't conflict with internal Google usage patterns for JJ?

**Comment by sheremetyev** [comment]
> I think a separate lock file will simplify lifetime issues of working copy object.

I've responded to the review feedback in that thread. I believe the single-lock approach provides stronger correctness guarantees, but I'm open to discussing alternatives. Hope we can resolve this and land the fix so JJ works correctly with Git in multi-process environments.

File: cli/src/cli_util.rs (hunk 10 above)
Comment (yuja) [reply cli/src/cli_util.rs]: I agree about the risk of deadlock, but I should note that `WorkingCopy` is allowed to become out of sync with the Git `HEAD` or the `@` revision.

https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy

The important thing to work around the concurrent HEAD import/export issue is to update Git HEAD and jj's view atomically. It's safer to update working copy within the locked scope instead of leaving it stale, but that wouldn't be strictly needed.

```
// in finish_transaction()
                // copy jj's view to Git HEAD
                // git::import_head() should be blocked until tx.commit()
                match jj_lib::git::reset_head(tx.repo_mut(), wc_commit) {
                ...
        // update jj's view
        self.user_repo = ReadonlyUserRepo::new(tx.commit(description)?);
```

There's another concurrency issue around import/export of bookmarks/tags. To fix this problem, we'll need a similar lock, but is unrelated to the working copy.

```
// in finish_transaction()
            // copy jj's view to Git refs/{heads,remotes,tags}/*
            // git::import_refs() should be blocked until tx.commit()
            let stats = jj_lib::git::export_refs(tx.repo_mut())?;
            ...
        self.user_repo = ReadonlyUserRepo::new(tx.commit(description)?);
```

So I think it's easier to add a separate lock file to fix this kind of problems.

Comment (sheremetyev) [reply cli/src/cli_util.rs]: Thanks for the response @yuja. How do you suggest to deal with the risk of deadlock?

Comment (martinvonz) [reply cli/src/cli_util.rs]: Always acquiring the git-head lock before the working-copy lock makes sense to me.

Comment (yuja) [reply cli/src/cli_util.rs]: Yes, and I think it's okay to protect the entire `maybe_snapshot()` scope. Maybe we can also pass around the lock for a bit of type safety.

```
    fn maybe_snapshot_impl(&mut self, ui: &Ui) -> Result<SnapshotStats, SnapshotWorkingCopyError> {
        if !self.may_update_working_copy {
            return Ok(SnapshotStats::default());
        }

        let lock: OpaqueLockToken = self.lock();
        self.import_git_head(ui, &lock)?
        let stats = self.snapshot_working_copy(ui, &lock)?;
        self.import_git_refs(ui, &lock)?;
        // release
        Ok(stats)
```

Comment (martinvonz) [reply cli/src/cli_util.rs]: And `OpaqueLockToken` can internally have an `Option` that's `None` when the working copy is not shared with Git, I suppose

File: cli/src/cli_util.rs [hunk 18]
```diff
@@ -1089,6 +1096,32 @@ impl WorkspaceCommandHelper {
...
+    /// Returns a token that can be passed to functions that need to export to
+    /// Git. For non-colocated repos, returns a token with no lock inside.
+    fn lock_git_head(&self) -> Result<GitHeadLock, CommandError> {
+        let lock = if self.working_copy_shared_with_git {
+            let lock_path = self
+                .workspace
+                .workspace_root()
+                .join(".jj")
+                .join("working_copy")
+                .join("git_head.lock");
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: Seeing this path made me think more about the scope of the lock. The `.jj/working_copy/` suggests that it's scoped to the working copy. But what if you have multiple workspaces? We don't currently support more than one colocated workspace, so I don't think it can be a problem in practice, but we'll probably get that support eventually. Is it better to put the lock inside `.git/` (wherever the main Git repo may be) to prepare for that?

File: cli/src/cli_util.rs (hunk 10 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: @yuja, @martinvonz, I've re-implemented the fix as a separate lock in 238704ac - please review!

Dropped note from CHANGELOG.md for now as it causes conflicts on every update to `main` - will restore it before merging.
```
* Fixed race condition that could cause divergent operations when multiple jj
  processes concurrently import/export Git HEAD in colocated repositories.
  [#6830](https://github.com/jj-vcs/jj/issues/6830)
```

File: cli/src/cli_util.rs (hunk 18 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Good point about multiple workspaces. I think storing it in `.git/` would break encapsulation too much - there's a nice property that you can remove `.jj/` from a colocated repo and get a "normal" Git repo back.

If `.jj/working_copy/` is the wrong scope because Git HEAD is repo-level, we could move it to `.jj/repo/git_head.lock` instead?

By the way, Git uses `.git/HEAD.lock` for locking but that lock file has different scope and lifetime (held only during the write operation itself, not across the import/snapshot/export cycle like ours).

Comment (martinvonz) [reply cli/src/cli_util.rs]: > there's a nice property that you can remove `.jj/` from a colocated repo and get a "normal" Git repo back.

True, but the lock files are supposed to be very short-lived, so it should rarely happen that a left-over lock still existed when you remove `.jj/`. We also already leave leave `refs/jj/` references in the repo. That said, `.jj/repo/git_head.lock` also seems fine. That was actually my first thought before I thought of putting it in `.git/`.

File: cli/tests/test_concurrent_operations.rs [hunk 19]
```diff
@@ -227,6 +227,101 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+    });
+
+    // Check for divergent operations
+    let output = work_dir.run_jj(["op", "log", "-T", "description"]);
+    let concurrent_count = output
+        .stdout
+        .raw()
+        .lines()
+        .filter(|line| line.contains("reconcile divergent operations"))
+        .count();
```
Comment (yuja) [inline cli/tests/test_concurrent_operations.rs:329]: Instead of counting "reconcile" operations, shouldn't we check for "import git head" operations? There would be still a race because the whole command session isn't locked.

File: cli/src/cli_util.rs (hunk 18 above)
Comment (yuja) [reply cli/src/cli_util.rs]: I think it's also better to rename the lock file to `.jj/repo/git_import_export.lock`. We can reuse the same lock file to fix import/export refs race.

File: cli/src/cli_util.rs [hunk 20]
```diff
@@ -2041,6 +2099,7 @@ See https://jj-vcs.github.io/jj/latest/working-copy/#stale-working-copy \
         ui: &Ui,
         mut tx: Transaction,
         description: impl Into<String>,
+        _git_head_lock: &GitHeadLock,
     ) -> Result<(), CommandError> {
         if !tx.repo().has_changes() {
```
Comment (yuja) [inline cli/src/cli_util.rs]: Locking isn't needed if the transaction has no changes. Perhaps, this check can be moved to caller.

File: cli/src/cli_util.rs (hunk 18 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Renamed lock file to `.jj/repo/git_import_export.lock` and corresponding variables etc.

File: cli/src/cli_util.rs (hunk 20 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Moved the check to caller (in a separate commit).

File: cli/tests/test_concurrent_operations.rs (hunk 19 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs:329]: Yes, that check would be more specific - updated. Verified that the test still catches race condition.

**Comment by sheremetyev** [comment]
Addressed all comments, added back a note in changelog, and rebased to latest main in 62988df4. @yuja @martinvonz please have another look!

File: cli/src/cli_util.rs [hunk 21]
```diff
@@ -1090,6 +1097,33 @@ impl WorkspaceCommandHelper {
...
+    /// that need to import from or export to Git. For non-colocated repos,
+    /// returns a token with no lock inside.
+    fn lock_git_import_export(&self) -> Result<GitImportExportLock, CommandError> {
+        let lock = if self.working_copy_shared_with_git {
+            let lock_path = self
+                .workspace
+                .workspace_root()
+                .join(".jj")
+                .join("repo")
+                .join("git_import_export.lock");
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: Should use `self.repo_path()` so we put the lock file in the main `.jj/repo/` directory if we run in another workspace (again, this cannot happen yet)

File: cli/src/cli_util.rs [hunk 22]
```diff
@@ -1090,6 +1097,33 @@ impl WorkspaceCommandHelper {
...
+            Some(
+                jj_lib::lock::FileLock::lock(lock_path.clone()).map_err(|err| {
+                    user_error(format!(
+                        "Failed to lock git import/export: {}: {}",
+                        lock_path.display(),
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: Isn't `.display()` the default formatting so this can be moved into the format string (as `{lock_path}`)?

File: cli/src/cli_util.rs [hunk 23]
```diff
@@ -1090,6 +1097,33 @@ impl WorkspaceCommandHelper {
...
+            let lock_path = self
+                .workspace
+                .workspace_root()
+                .join(".jj")
+                .join("repo")
+                .join("git_import_export.lock");
+            Some(
+                jj_lib::lock::FileLock::lock(lock_path.clone()).map_err(|err| {
+                    user_error(format!(
+                        "Failed to lock git import/export: {}: {}",
```
Comment (martinvonz) [inline cli/src/cli_util.rs]: nit: "git" -> "Git". Also maybe insert "take lock for"?

File: cli/src/cli_util.rs (hunk 22 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Don't think so - this method returns object that implements `Display` trait: https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.display

File: cli/src/cli_util.rs (hunk 21 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Updated - thank you!

File: cli/src/cli_util.rs (hunk 23 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: updated

File: cli/tests/test_concurrent_operations.rs [hunk 24]
```diff
@@ -227,6 +227,101 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+            .success();
+    }
+
+    // Extract environment from TestEnvironment to use in spawned processes
+    let base_cmd = test_env.new_jj_cmd();
+    let jj_bin = base_cmd.get_program().to_owned();
+    let base_env: Vec<_> = base_cmd
+        .get_envs()
+        .filter_map(|(k, v)| v.map(|v| (k.to_owned(), v.to_owned())))
+        .collect();
```
Comment (yuja) [inline cli/tests/test_concurrent_operations.rs:281]: We shouldn't run multiple `jj` commands with the same timestamp and random seed. The easiest workaround I think is to filter out `JJ_TIMESTAMP`, `JJ_OP_TIMESTAMP`, and `JJ_RANDOMNESS_SEED`.

Then, maybe we can assert that `cmd` exists successfully.

File: cli/tests/test_concurrent_operations.rs [hunk 25]
```diff
@@ -227,6 +227,101 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+    // (which imports Git HEAD) and another running `jj next/prev` repeatedly
+    // (which exports Git HEAD). Without the fix, this would create divergent
+    // operations.
+
+    let test_env = TestEnvironment::default();
+    test_env
+        .run_jj_in(".", ["git", "init", "--colocate", "repo"])
+        .success();
+    let work_dir = test_env.work_dir("repo");
+
```
Comment (yuja) [inline cli/tests/test_concurrent_operations.rs:244]: nit: Can you insert a test snapshot that does actually "import git head" and use it in the assertion? This will prevent us from nullifying the test by changing the operation description.

```rust
// copy some bits from test_git_colocated.rs to do "import git head" ...
...
let output = work_dir.run_jj(["op", "log", "-T", "description", "--limit=1"]).success();
let desc = output.stdout.raw().lines().next().unwrap();
insta::assert_snapshot!(desc, @"import git head");
...
    .filter(|line| line.contains(desc))
```

File: cli/src/cli_util.rs [hunk 26]
```diff
@@ -1090,6 +1097,28 @@ impl WorkspaceCommandHelper {
...
+    fn lock_git_import_export(&self) -> Result<GitImportExportLock, CommandError> {
+        let lock = if self.working_copy_shared_with_git {
+            let lock_path = self.workspace.repo_path().join("git_import_export.lock");
+            Some(
+                jj_lib::lock::FileLock::lock(lock_path.clone()).map_err(|err| {
+                    user_error(format!(
+                        "Failed to take lock for Git import/export: {}: {}",
+                        lock_path.display(),
+                        err.err
+                    ))
```
Comment (yuja) [inline cli/src/cli_util.rs]: nit: `user_error_with_message("Failed to take lock for Git import/export", err)`, which should print why the lock couldn't be obtained.

File: cli/src/cli_util.rs [hunk 27]
```diff
@@ -1090,6 +1097,28 @@ impl WorkspaceCommandHelper {
...
 
+    /// Acquires a lock for git import/export operations if the workspace is
+    /// colocated with Git. Returns a token that can be passed to functions
+    /// that need to import from or export to Git. For non-colocated repos,
+    /// returns a token with no lock inside.
+    fn lock_git_import_export(&self) -> Result<GitImportExportLock, CommandError> {
+        let lock = if self.working_copy_shared_with_git {
+            let lock_path = self.workspace.repo_path().join("git_import_export.lock");
+            Some(
+                jj_lib::lock::FileLock::lock(lock_path.clone()).map_err(|err| {
```
Comment (yuja) [inline cli/src/cli_util.rs]: nit: import `FileLock` by name

File: cli/src/cli_util.rs [hunk 28]
```diff
@@ -1099,9 +1128,27 @@ impl WorkspaceCommandHelper {
...
+
+        // Reload at current head to avoid creating divergent operations if another
+        // process committed an operation while we were waiting for the lock.
+        if self.working_copy_shared_with_git {
+            let repo = self.repo().clone();
+            let current_repo = repo.reload_at_head().map_err(snapshot_command_error)?;
+            if current_repo.op_id() != repo.op_id() {
+                self.user_repo = ReadonlyUserRepo::new(current_repo);
+            }
+        }
```
Comment (yuja) [inline cli/src/cli_util.rs:1155]: To optimize this for trivial cases, we can query op heads:
```rust
            let op_heads_store = repo.loader().op_heads_store();
            let op_heads = op_heads_store
                .get_op_heads()
                .block_on()
                .map_err(snapshot_command_error)?;
            if slice::from_ref(repo.op_id()) != op_heads {
                // Reload repo unconditionally
                // It might be better to use self.env.command.resolve_operation() to print status message.
```

File: cli/src/cli_util.rs [hunk 29]
```diff
@@ -1136,7 +1184,11 @@ impl WorkspaceCommandHelper {
     /// working-copy contents won't be updated.
     #[cfg(feature = "git")]
     #[instrument(skip_all)]
-    fn import_git_head(&mut self, ui: &Ui) -> Result<(), CommandError> {
+    fn import_git_head(
+        &mut self,
+        ui: &Ui,
+        git_import_export_lock: &GitImportExportLock,
+    ) -> Result<(), CommandError> {
```
Comment (yuja) [inline cli/src/cli_util.rs:1200]: nit: can you delete or update TODO comment about concurrent updates?

File: cli/tests/test_concurrent_operations.rs (hunk 24 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs:281]: Filtered out those environment variables to have randomness in the race test. Added `--ignore-working-copy` flag in the "op log" command because test was finishing with a stale working copy (before the fix).

Asserted commands succeed, in commit that fixes the race - they were failing before that.

File: cli/tests/test_concurrent_operations.rs (hunk 25 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs:244]: Good idea, thank you! Added the check in a separate commit.

File: cli/src/cli_util.rs (hunk 26 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Updated

File: cli/src/cli_util.rs (hunk 27 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Updated

File: cli/src/cli_util.rs (hunk 28 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs:1155]: Updated

File: cli/src/cli_util.rs (hunk 29 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs:1200]: Removed TODO comment

**Comment by sheremetyev** [comment]
Rebased in 16104ab6

File: cli/src/cli_util.rs [hunk 30]
```diff
@@ -1004,6 +1006,13 @@ impl WorkspaceCommandEnvironment {
     }
 }
 
+/// A token that holds a lock for git import/export operations in colocated
+/// repositories. For non-colocated repos, this is an empty token (no actual
+/// lock held). The lock is automatically released when this token is dropped.
+pub struct GitImportExportLock {
+    _lock: Option<jj_lib::lock::FileLock>,
```
Comment (yuja) [inline cli/src/cli_util.rs]: nit: `Option<FileLock>`

File: cli/tests/test_concurrent_operations.rs [hunk 31]
```diff
@@ -227,6 +227,103 @@ fn test_concurrent_snapshot_wc_reloadable() {
...
+    let base_cmd = test_env.new_jj_cmd();
+    let jj_bin = base_cmd.get_program().to_owned();
+    let base_env: Vec<_> = base_cmd
+        .get_envs()
+        .filter_map(|(k, v)| v.map(|v| (k.to_owned(), v.to_owned())))
+        // Filter out timestamp and randomness seed so each command gets different values
+        .filter(|(k, _)| k != "JJ_TIMESTAMP" && k != "JJ_OP_TIMESTAMP" && k != "JJ_RANDOMNESS_SEED")
+        .collect();
+
+    let repo_path = work_dir.root().to_path_buf();
```
Comment (yuja) [inline cli/tests/test_concurrent_operations.rs]: nit: `.to_path_buf()` isn't needed

File: cli/tests/test_concurrent_operations.rs [hunk 32]
```diff
@@ -309,20 +317,43 @@ fn test_git_head_race_condition() {
...
+        .run_jj(["op", "log", "-T", "description", "--limit=1"])
+        .success()
+        .stdout
+        .into_raw();
+
+    assert!(
+        last_op.contains(IMPORT_GIT_HEAD),
+        "Expected last operation to contain '{}', got: {}",
+        IMPORT_GIT_HEAD,
+        last_op.trim()
```
Comment (yuja) [inline cli/tests/test_concurrent_operations.rs]: nit: just inline parameters as `{IMPORT_GIT_HEAD}: {last_op}`? (I personally don't mind if `last_op` contained trailing whitespace.)

File: cli/src/cli_util.rs (hunk 30 above)
Comment (sheremetyev) [reply cli/src/cli_util.rs]: Updated

File: cli/tests/test_concurrent_operations.rs (hunk 31 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs]: Removed

File: cli/tests/test_concurrent_operations.rs (hunk 32 above)
Comment (sheremetyev) [reply cli/tests/test_concurrent_operations.rs]: Updated

**Comment by sheremetyev** [comment]
Test in the CI failed because we were lucky and "next/prev" loop ended up on the initial commit, making "git checkout" command a no-op. I've tweaked the test to remove this source of flakiness.
