### PR TITLE
file track: fix spurious `--include-ignored` warning

### LINKED ISSUE #8826: file track --include-ignored is being ignored
## Description

I'm adding a few files to the repository with `jj file track ...bunch-of-large-files.sql` and the CLI says that it can't track them because they are larger than 1M, which is fine. It friendly suggests to do some things to work around that, which includes the following:
```
 - Run `jj file track --include-ignored ...bunch-of-large-files.sql`
 ```

And it doesn't work. I literally copied this line from the output, pasted into the terminal and got exactly the same result (including the same advice, which meant I was at risk to die from starvation, lol).

## Steps to Reproduce the Problem

1. Create a few files larger than 1M (or whatever your limit is set at)
1. Try to track them

## Expected Behavior
Files being added/tracked

## Actual Behavior
Files are refused to be tracked

## Specifications

- Platform: MacOS
- Version: 0.37.0

### PR DESCRIPTION
**Pull request by gechr**
I was briefly confused when I saw the large file hint immediately after running `jj file track --include-ignored`, so ensure it is not emitted unnecessarily. This was originally introduced in #7900.

Also fix up a few nits (grammar, quoting, etc) around the hint and extract it to a helper function.

Resolves #8826

### CODE REVIEW

File: cli/src/commands/file/track.rs [hunk 1]
```diff
@@ -94,14 +94,18 @@ pub fn print_track_snapshot_stats(
     path_converter: &RepoPathUiConverter,
 ) -> io::Result<()> {
     let mut merged_untracked_paths = auto_stats.untracked_paths;
+
+    // Remove paths that were successfully tracked by `file track`
+    merged_untracked_paths.retain(|path, _| track_stats.untracked_paths.contains_key(path));
```
Comment (yuja) [inline cli/src/commands/file/track.rs]: Perhaps, this doesn't work if paths are specified. `track_stats` wouldn't include untracked paths not matching the path patterns. Maybe we have to use the snapshotted `tree`?

File: cli/src/cli_util.rs [hunk 2]
```diff
@@ -2894,21 +2894,51 @@ pub fn print_snapshot_stats(
...
+    large_files: Option<&[String]>,
+) -> io::Result<()> {
+    let (command, extra) = large_files
+        .map(|files| {
+            let files_list = shlex::try_join(files.iter().map(|s| s.as_str()))
+                .unwrap_or_else(|_| files.join(" "));
+            let command = format!("file track {files_list}");
+            let extra = format!(
+                r"
+
```
Comment (yuja) [inline cli/src/cli_util.rs]: nit: I wouldn't insert blank line.

I don't have opinion about the other style changes.

File: cli/src/cli_util.rs [hunk 3]
```diff
@@ -2894,21 +2894,51 @@ pub fn print_snapshot_stats(
...
+/// suitable for general snapshot operations.
+pub fn print_large_file_hint(
+    ui: &Ui,
+    max_size: u64,
+    large_files: Option<&[String]>,
+) -> io::Result<()> {
+    let (command, extra) = large_files
+        .map(|files| {
+            let files_list = shlex::try_join(files.iter().map(|s| s.as_str()))
+                .unwrap_or_else(|_| files.join(" "));
```
Comment (yuja) [inline cli/src/cli_util.rs]: nit: When does `try_join()` fail? Can you add comment?

Might be better to fall back per item, not at the whole list.

File: cli/src/cli_util.rs [hunk 4]
```diff
@@ -2894,21 +2894,51 @@ pub fn print_snapshot_stats(
...
+    writedoc!(
+        ui.hint_default(),
+        r"
+        This is to prevent large files from being added by accident. To fix this:
+          * Add the file(s) to `.gitignore`
+          * Run `jj config set --repo snapshot.max-new-file-size {max_size}`
+            This will increase the maximum file size allowed for new files, in this repository only.
+          * Run `jj --config snapshot.max-new-file-size={max_size} {command}`
+            This will increase the maximum file size allowed for new files, for this command only.{extra}
+"
```
Comment (yuja) [inline cli/src/cli_util.rs]: nit: indent `"`

File: cli/src/commands/file/track.rs (hunk 1 above)
Comment (gechr) [reply cli/src/commands/file/track.rs]: I added a test to demo that the current approach works if paths are specified. It appears they are added to `track_stats` with reason `FileNotAutoTracked`. Should I still use the snapshotted `tree`?

Comment (yuja) [reply cli/src/commands/file/track.rs]: Ah, okay. Good find. In that case, I would rewrite "merge" to use `track_stats` as the base data. Something like:
```rust
    let mut untracked_paths = track_stats.untracked_paths;
    for (path, reason) in &mut untracked_paths {
        if !matches!(reason, UntrackedReason::FileNotAutoTracked) {
            continue;
        }
        if let Some(old_reason) = auto_stats.untracked_paths.remove(path) {
            *reason = old_reason;
        }
    }
```

File: cli/src/commands/file/track.rs [hunk 5]
```diff
@@ -93,21 +93,19 @@ pub fn print_track_snapshot_stats(
...
-    {
-        // if the path was previously rejected because it wasn't tracked, update its
-        // reason
-        merged_untracked_paths.insert(path, reason);
+    let mut untracked_paths = track_stats.untracked_paths;
+    for (path, reason) in &mut untracked_paths {
+        if !matches!(reason, UntrackedReason::FileNotAutoTracked) {
+            continue;
+        }
+        if let Some(old_reason) = auto_stats.untracked_paths.get(path).cloned() {
```
Comment (martinvonz) [inline cli/src/commands/file/track.rs]: nit: Since we don't seem to use `auto_stats.untracked_paths` after this point, you can probably replace the `.get()` by `remove()` and drop the `.cloned()`. Oh, I see that Yuya already suggested that. Did that not work for some reason?

Comment (gechr) [reply cli/src/commands/file/track.rs]: Just a misunderstanding on my part while learning Rust. I thought `remove()` would risk modifying `auto_stats` in the caller - didn't realise that `mut auto_stats` would be a local copy, not a mutable reference.

Comment (martinvonz) [reply cli/src/commands/file/track.rs]: FYI, it would have been `&mut SnapshotStats` if it had been a mutably borrowing from the caller.
