### PR TITLE
working-copy: Ensure sub-repos are not tracked.

### LINKED ISSUE #4349: git submodules in colocated repos create weird phantom file creations/deletions
## Description

I found that if I use git submodules in a colocated repo, jj will get confused as I move the working copy around and introduce phantom file creations/deletions.

## Steps to Reproduce the Problem

1. jj git clone git@github.com:insanum/gcalcli.git --colocate
1. cd gcalcli
1. git submodule update --init
1. jj new zrv

Possible repro also involves a .gitkeep file there, or some other peculiarity in that repo.

## Expected Behavior

jj shows the new change I just created as "(empty)" with no diff.

## Actual Behavior

New change is non-empty and includes a bunch of spurious edits under the submodule paths:
```
Working copy changes:
A tests/cli/bats/.codespellrc
A tests/cli/bats/.devcontainer/Dockerfile
(...)
A tests/cli/test_helper/bats-support/test/cat
A tests/cli/test_helper/bats-support/test/test_helper.bash
```

If I try to `jj abandon`, I keep getting more new changes with spurious edits.

If I then move the working copy back past `main`, I see similar results with file deletion operations:

```
$ jj new main
Working copy now at: qonswokm 6fd66464 (empty) (no description set)
Parent commit      : kntwpymn 9b65c9a5 main | (empty) Merge pull request #716 from insanum/metadata
Added 8 files, modified 10 files, removed 415 files
Warning: 3 of those updates were skipped because there were conflicting changes in the working copy.
Hint: Inspect the changes compared to the intended target with `jj diff --from 6fd66464a519`.
Discard the conflicting changes with `jj restore --from 6fd66464a519`.

$ jj status
Working copy changes:
D tests/cli/bats
A tests/cli/bats/test/.bats/run-logs/.gitkeep
D tests/cli/test_helper/bats-assert
D tests/cli/test_helper/bats-support
```

## Specifications

- Platform: Ubuntu Linux
- Version: 0.20.0

### PR DESCRIPTION
**Pull request by matts1**
If a submodule was created in a commit C on a remote repo, switching from any commit after C to any commit before C (eg. `jj new C-`) will result in jj starting to track the files introduced in the submodule.

This issue has popped up very frequently for chromium developers, who get issues when attempting to check out an older version of chromium.

Fixes #4349

# Checklist

If applicable:

- [X] I have updated `CHANGELOG.md`
- [X] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [X] I have updated the config schema (`cli/src/config-schema.json`)
- [X] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/local_working_copy.rs [hunk 1]
```diff
@@ -1371,6 +1371,18 @@ impl FileSnapshotter<'_> {
...
         if file_type.is_dir() {
             let file_states = file_states.prefixed_at(dir, name);
+            // If a submodule was added in commit C, and a user decides to run
+            // `jj new <something before C>` from after C, then jj believes
+            // that the content of the submodule is now in the working copy of
+            // the main repo.
+            // See https://github.com/jj-vcs/jj/issues/4349.
+            let disk_dir = entry.path();
+            for name in RESERVED_DIR_NAMES {
+                if disk_dir.join(name).exists() {
```
Comment (yuja) [inline lib/src/local_working_copy.rs]: Perhaps, it's better to use `symlink_metadata()` because working-copy operation shouldn't usually follow symlinks.

File: lib/src/local_working_copy.rs [hunk 2]
```diff
@@ -1371,6 +1371,18 @@ impl FileSnapshotter<'_> {
 
         if file_type.is_dir() {
             let file_states = file_states.prefixed_at(dir, name);
+            // If a submodule was added in commit C, and a user decides to run
+            // `jj new <something before C>` from after C, then jj believes
+            // that the content of the submodule is now in the working copy of
+            // the main repo.
+            // See https://github.com/jj-vcs/jj/issues/4349.
```
Comment (yuja) [inline lib/src/local_working_copy.rs:1379]: This isn't just about submodules, but nested repositories in general. Can you update the comment and changelog?

FWIW, `git` doesn't ignore nested `<repo>/.git` directories if there are tracked files, whereas `hg` does. I don't know which behavior is better, though.

File: cli/tests/test_working_copy.rs [hunk 3]
```diff
@@ -469,3 +469,76 @@ fn test_conflict_marker_length_stored_in_working_copy() {
...
+    [EOF]
+    "###);
+
+    // Switch to a historical commit before the submodule was checked in.
+    work_dir.run_jj(["prev"]).success();
+    // jj new (or equivalently prev) should always leave you with an empty working
+    // copy.
+    let output = work_dir.run_jj(["diff", "--summary"]);
+    insta::assert_snapshot!(output, @"");
+}
```
Comment (yuja) [inline cli/tests/test_working_copy.rs:544]: I think we can instead add library test to test_local_working_copy.rs.

Comment (matts1) [reply cli/tests/test_working_copy.rs:544]: I didn't really trust the library test to be sufficient, since it didn't deql with a real filesystem and the nuances of JJ new leaving the filles behind. It felt like it'd test one aspect of it without testing that it truly works.

File: lib/src/local_working_copy.rs (hunk 2 above)
Comment (matts1) [reply lib/src/local_working_copy.rs:1379]: If you run git checkout HEAD^ here, git just leaves the repo on disk but leaves it as unstaged. Also, if you try and git add it, git warns you. JJ doesn't have this option though, since JJ has no such thing as unstaged.

Hg also doesn't have a concept of staged.

That's why I think not tracking these repos is a better idea. We could choose to add it as a config option later if someone decides this behaviour is an issue, but I don't anticipate this coming up.

File: cli/tests/test_working_copy.rs (hunk 3 above)
Comment (yuja) [reply cli/tests/test_working_copy.rs:544]: Well, we already have `test_git_submodule()` that do check out and snapshot.

I won't be against adding a few CLI tests to ensure that the status message about ignored submodule is printed, though.

File: lib/src/local_working_copy.rs (hunk 2 above)
Comment (yuja) [reply lib/src/local_working_copy.rs:1379]: To be clear, I'm not against this change. I just mean this should be documented as a breaking change about nested Git/jj repository handling rather than a fix for Git submodules.

File: CHANGELOG.md [hunk 4]
```diff
@@ -42,6 +42,9 @@ should not be broken.
   is not read anymore. Use `$XDG_CONFIG_HOME/jj` instead (defaults to
   `~/.config/jj`).
 
+* Sub-repos are no longer tracked. Any directory containing the subdirectory
+  `.jj` or `.git` is ignored. Note that git submodules are unaffected by this.
```
Comment (yuja) [inline CHANGELOG.md]: nit: we don't check if `.jj` or `.git` is a directory, and that's correct because `.git` may be a file.

File: lib/src/local_working_copy.rs [hunk 5]
```diff
@@ -1371,6 +1371,19 @@ impl FileSnapshotter<'_> {
 
         if file_type.is_dir() {
             let file_states = file_states.prefixed_at(dir, name);
+            // If a submodule was added in commit C, and a user decides to run
+            // `jj new <something before C>` from after C, then the submodule
+            // files stick around but it is no longer seen as a submodule.
+            // We need to ensure that it is not tracked as if it was added to
+            // the main repo.
+            // See https://github.com/jj-vcs/jj/issues/4349.
```
Comment (yuja) [inline lib/src/local_working_copy.rs:1379]: Can you also update this comment? A Git submodule is just one example, and we ignore any kind of nested repositories.

File: lib/src/local_working_copy.rs [hunk 6]
```diff
@@ -1371,6 +1371,19 @@ impl FileSnapshotter<'_> {
...
+            let disk_dir = entry.path();
+            for &name in RESERVED_DIR_NAMES {
+                if disk_dir.join(name).symlink_metadata().is_ok() {
```
Comment (yuja) [inline lib/src/local_working_copy.rs:1383]: Can you update lib/tests/test_local_working_copy.rs to include basic tests for nested repositories?

**Review by yuja — APPROVED** [review]
