### PR TITLE
git: set --intent-to-add on new files

### LINKED ISSUE #6122: Newly created files not added to git
## Description

Hi! I'm using Jujutsu with the Git backend, and whenever I create a new file, it doesn't get "added" to Git immediately, which hinders my workflow in some places (Neovim's find Git files only works when the files are added, Nix flakes only recognize files that are added, etc.). Currently, I've been using `jj new` after creating a new file, and then squashing the two commits together, which works but is quite annoying. Is there any way to fix/get around this?

## Steps to Reproduce the Problem

1. Create a new file  
2. Run `git status`  

## Expected Behavior

All files in the working copy should be tracked by Git.  

## Actual Behavior

New files in the working copy are untracked by Git.  

## Specifications

- Platform: Linux (NixOS)  
- Version: 0.27.0

### PR DESCRIPTION
**Pull request by martinvonz**
Closes #6122

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]

File: lib/src/git.rs [hunk 1]
```diff
@@ -1424,6 +1430,86 @@ fn build_index_from_merged_tree(
...
+        }
+    }
+
+    if added_paths.is_empty() && removed_paths.is_empty() {
+        return Ok(());
+    }
+
+    for (path, executable) in added_paths {
+        // We have checked that the index doesn't have this entry
+        index.dangerously_push_entry(
```
Comment (scott2000) [inline lib/src/git.rs:1487]: Does this properly handle the case where a file `.jj-do-not-resolve-this-conflict` is added in the working copy, and also the file `.jj-do-not-resolve-this-conflict` was already added as a conflict in the index (since there was a conflict that couldn't be represented in the index properly)? It seems like this could result in a duplicate entry.

File: lib/src/git.rs [hunk 2]
```diff
@@ -1424,6 +1430,86 @@ fn build_index_from_merged_tree(
     Ok(index)
 }
 
+pub fn update_intent_to_add(
```
Comment (yuja) [inline lib/src/git.rs:1433]: nit: for future reference, I think it's better to include when this function should be called.

File: CHANGELOG.md
Comment (yuja) [inline CHANGELOG.md:1]: nit: include the issue number in commit description

**Review by yuja — APPROVED** [review]

File: lib/src/git.rs [hunk 3]
```diff
@@ -1424,6 +1430,86 @@ fn build_index_from_merged_tree(
...
+    old_tree: &MergedTree,
+    new_tree: &MergedTree,
+) -> BackendResult<()> {
+    let mut diff_stream = old_tree.diff_stream(new_tree, &EverythingMatcher);
+    let mut added_paths = vec![];
+    let mut removed_paths = HashSet::new();
+    while let Some(TreeDiffEntry { path, values }) = diff_stream.next().await {
+        let (before, after) = values?;
+        if before.is_absent() {
+            if let Some(TreeValue::File { id: _, executable }) = after.as_normal() {
```
[the remark this answers is not in the document]
Comment (martinvonz) [reply lib/src/git.rs:1463]: Yeah, I wasn't sure either, but I've tested it now and it seems to behave as expected, so I added support for symlinks too.

File: lib/src/git.rs [hunk 4]
```diff
@@ -1424,6 +1430,86 @@ fn build_index_from_merged_tree(
...
+                if index
+                    .entry_index_by_path(BStr::new(path.as_internal_file_string()))
+                    .is_err()
+                {
+                    added_paths.push((
+                        BString::new(path.as_internal_file_string().into()),
```
[the remark this answers is not in the document]
Comment (martinvonz) [reply lib/src/git.rs:1469]: Done

File: lib/src/git.rs (hunk 1 above)
Comment (martinvonz) [reply lib/src/git.rs:1487]: Do you mean like in [this test case](https://github.com/jj-vcs/jj/blob/e39244828805892d71e770839d4ccc24af3ea12f/cli/tests/test_git_colocated.rs#L1247-L1258)? That passes. Does that mean the scenario you're thinking of is handled correctly?

Comment (scott2000) [reply lib/src/git.rs:1496]: I was thinking of that case, but if a snapshot is taken before `jj new` is run. I'm thinking it could lead to the index having 2 entries for the same file (one conflicted and one unconflicted) until `jj new` is run, and I'm not sure that's considered valid by Git.

Comment (martinvonz) [reply lib/src/git.rs:1496]: A snapshot is always taken before a command is run, so I think that's already covered. Maybe there's some way to cause a crash if you manually add a `.jj-do-not-resolve-this-conflict` file (as that test case does) but I don't really care if people get hurt when they deliberately shoot themselves in the foot. (If there's a way to run into a crash without doing that, I think we should definitely fix it, however.)
