### PR TITLE
docs: fix and improve colocation docs

### LINKED ISSUE #7776: Docs and help output regarding colocation are wrong
The docs and `help` output regarding colocation are wrong.

For example `jj help git clone` as well as https://jj-vcs.github.io/jj/latest/cli-reference/#jj-git-clone state, that the Git repo will be inside `.jj`, but that is only the case if you use `--no-colocate`, the colocation seems to be the default (at least now).

Same for `git init` to create a new repository or jj-ify an existing repository, it also by default creates colocated repos but the docs say otherwise.

### PR DESCRIPTION
**Pull request by ilyagr**
Follows up on 7c0328f

Fixes #7776

### CODE REVIEW

File: cli/src/commands/git/clone.rs [hunk 1]
```diff
@@ -62,10 +60,32 @@ pub struct GitCloneArgs {
...
+    /// the use of both `jj` and `git` commands in the same directory.
+    ///
+    /// The repository will contain a `.git` dir in the top-level. Regular Git
+    /// tools will be able to operate on the repo.
+    ///
+    /// **This is the default**, and this option has no effect, unless the
+    /// [git.colocate config] is set to `false`.
+    ///
+    /// [git.colocate config]:
+    ///     https://jj-vcs.github.io/jj/prerelease/config/#default-colocation
```
Comment (yuja) [inline cli/src/commands/git/clone.rs]: nit: the doc URL should point to the `/latest`?

File: docs/git-compatibility.md [hunk 2]
```diff
@@ -123,11 +123,15 @@ You can undo the results of mutating `git` commands using `jj undo` and `jj op
...
-repos may require you to deal with more involved Jujutsu and Git concepts.
-You can disable colocation with the `--no-colocate` flag on the commands
-`jj git init` and `jj git clone` or by setting the configuration
-`git.colocate = false`.
+You can disable colocation with the `--no-colocate` flag on the commands `jj git
+init` and `jj git clone` or by setting the configuration `git.colocate = false`.
+Much of the repo data will still be stored in the Git repository format, but the
+Git repository will be hidden inside a sub-directory of the `.jj` directory.
+Moreover, unless you explicitly use the `jj git import` and `jj git export`
+commands, that Git repository will either no branches at all (not even a main
```
Comment (yuja) [inline docs/git-compatibility.md]: nit: "either _have_ no branches"?

**Review by yuja — APPROVED** [review]

**Comment by ilyagr** [comment]
Thank you, Yuya!
