### PR TITLE
commit: allow Unicode characters in conflict labels

### LINKED ISSUE #8467: Unicode revision descriptions are escaped in conflict marker labels
## Description

When jj writes conflict markers into a file, the conflict label “description” is not rendered as Unicode text. Instead, CJK characters are escaped as \u{....} sequences (Rust-style escapes), which makes the conflict header hard to read.

This may be related to #7692 .

Notably, jj log displays the same descriptions correctly (e.g. `新提交`, `原提交`), but inside the conflict marker header they become `\u{65b0}\u{63d0}\u{4ea4}`, `\u{539f}\u{63d0}\u{4ea4}`.

Example conflict marker snippet:

```
a
<<<<<<< conflict 1 of 1
%%%%%%% diff from: xkoxssuy 349ed707 (parents of rebased revision)
\\\\\\\        to: kxnsxmyz d82f6154 "\u{539f}\u{63d0}\u{4ea4}" (rebase destination)
+b
+++++++ ywopvqrl 2629666e "\u{65b0}\u{63d0}\u{4ea4}" (rebased revision)
c
>>>>>>> conflict 1 of 1 ends
```

jj log shows (same revisions):

```
@  ywopvqrl wd.1105848296@gmail.com 2026-01-01 08:53:17 a2ce31de
│  新提交
○  kxnsxmyz wd.1105848296@gmail.com 2026-01-01 08:53:04 d82f6154
│  原提交
○  xkoxssuy wd.1105848296@gmail.com 2025-12-30 19:40:56 349ed707
│  (no description set)
◆  zzzzzzzz root() 00000000
```

## Steps to Reproduce the Problem

1. Create a repo and a file with some content (e.g. a, b, c around a line that will conflict).
2. Create commits whose descriptions include CJK characters, e.g. `原提交` and `新提交`.
3. Perform an operation that generates a textual conflict in the working copy (e.g. rebase/merge) so that jj writes conflict markers into the file.
4. Open the conflicted file and inspect the conflict label lines (diff from: ..., to: ..., etc.).

## Expected Behavior

The conflict marker header shows Unicode descriptions as-is (UTF-8), e.g.:

- to: ... "原提交" ...
- ... "新提交" ...

(or otherwise matches how jj log renders descriptions).

## Actual Behavior

The conflict marker header escapes Unicode characters as \u{....} sequences, e.g.:

- `\u{539f}\u{63d0}\u{4ea4}`
- `\u{65b0}\u{63d0}\u{4ea4}`

## Specifications

- Platform: Linux (Arch Linux, x86_64)
- Version: jj 0.36.0-e8e504107685c45c3bc1abb333f7ab2f5e80c72d

### PR DESCRIPTION
**Pull request by scott2000**
We only need to remove control characters. Git has support for UTF-8 in headers, so we can just directly include Unicode characters without escaping or replacing them.

Fixes #8467.

*Edit: I verified this by checking the Git source code as well as testing it locally using `git fsck` and `git cat-file -p`. The [Git code for parsing extra headers](https://github.com/git/git/blob/68cb7f9e92a5d8e9824f5b52ac3d0a9d8f653dbe/commit.c#L1487) doesn't rely on any particular encoding, since it only checks for `'\n'` to separate lines, as well as checking that continuation lines start with a space character. Separately, Git does check that the entire commit buffer (including extra headers) is valid UTF-8 [when writing commits](https://github.com/git/git/blob/68cb7f9e92a5d8e9824f5b52ac3d0a9d8f653dbe/commit.c#L1813). So it should be fine to write non-ASCII text as long as it is valid UTF-8, which Rust already guarantees for `String`.*

# Checklist

If applicable:

- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [X] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/commit.rs [hunk 1]
```diff
@@ -217,7 +218,7 @@ impl Commit {
             format!(
                 "{} \"{}\"",
                 self.conflict_label_short(),
-                subject.escape_default()
+                escape_string(subject)
```
Comment (yuja) [inline lib/src/commit.rs]: nit: can you add comment why we need escapes? If Git doesn't like ASCII control characters such as `\0`, it might be better to strip bad characters than escaping.

Comment (scott2000) [reply lib/src/commit.rs]: I don't have any strong reason for escaping control characters over stripping them. The main reason I can think of is that it would be confusing if the commit message contains quotes, and we also surround it with quotes. Using an example from this repo, if the commit message is `mise: rename "live" tasks to "watch"`, it might be a bit confusing to see double quotes like `otxuowyz 876cba8e "mise: rename "live" tasks to "watch""` compared to escaping it like `otxuowyz 876cba8e "mise: rename \"live\" tasks to \"watch\""`. But perhaps that looks uglier, and it's not meant to be machine-readable, so maybe just stripping control characters is better?

Comment (scott2000) [reply lib/src/commit.rs]: I updated to just remove control characters for now since it's simpler. Let me know what you think.

Comment (yuja) [reply lib/src/commit.rs]: nit: I think we can use `.replace(.., "")`.
