### PR TITLE
fix: add `$root` variable that can be used in commands

### LINKED ISSUE #7144: Windows: Repo-relative fix tool commands are executed from cwd rather than the workspace root
## Description

Suppose a fix tool is a path inside the repo, such as `node_modules/.bin/biome.exe`, and configured like so:

```
[fix.tools.biome]
command = ["node_modules/.bin/biome.exe"]
```

When executing `jj fix` from the workspace root, jj correctly spawns `$ROOT/node_modules/.bin/biome.exe`.

But, if the current working directory is not the root, then on Windows, jj attempts to invoke `node_modules/.bin/biome.exe` relative to the working directory.

## Steps to Reproduce the Problem

This was a little complicated to get into a script, especially because the bug needs to be reproduced on Windows and batch file escaping is awful. So I made a repository: https://github.com/jennings/jj-fix-relative-command-bug

Clone this repository:

```command
$ jj git clone git@github.com:jennings/jj-fix-relative-command-bug.git
$ cd jj-fix-relative-command-bug
```

Add the following fix tool config:

```toml
[fix.tools.a]
command = ["a/script.bat"]
patterns = ["f"]
```

Then, modify `f` and run `jj fix`, which correctly invokes the script in `a/script.bat`:

```command
$ echo "edit" > f
$ jj fix
f:
 hello from the nested script
<snip>
```

Then change into the `a` directory and run `jj fix` again. Notice the script output changed:

```command
$ cd a
$ jj fix 
..\f:
 hello from the double nested script
<snip>
```

I added equivalent `script.sh` files so it could be tested on other platforms. On macOS, both invocations output "hello from the nested script".

## Expected Behavior

The second invocation outputs "hello from the nested script" on Windows.

## Actual Behavior

The second invocation outputs "hello from the double nested script" on Windows.

## Specifications

- Platform: Windows 11 64-bit
- Version: jj 0.31.0-7f88b13bfcd6122715bc460967d91fd40db28f0d

### PR DESCRIPTION
**Pull request by jennings**
On Windows, spawning a child process finds the command relative to the parent's working directory. If a command is specified as `["path/inside/repo/tool.exe"]`, then tool won't be found if `jj fix` is run somewhere besides the workspace root.

There doesn't seem to be a good way to change this behavior, nor does it seem easy to convert `program` into an absolute path because `["tool.exe"]` could refer either to a file on the PATH or a file committed at the root of the repository.

So, we add a new variable `$root` that can be used in this situation. Workspace-relative tools on Windows should be defined using this variable:

```toml
# Tools on the path
command = ["tool.exe"]

# Workspace-relative tools
command = ["$root/tool.exe"]
command = ["$root/nested/dir/tool.exe"]
```

On Unix, the command is relative to the child's working directory, so this isn't an issue.

Fixes #7144

# Checklist

If applicable:

- [X] I have updated `CHANGELOG.md`
- [X] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [X] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/commands/fix.rs [hunk 1]
```diff
@@ -250,10 +253,11 @@ fn run_tool(
     file_to_fix: &FileToFix,
     old_content: &[u8],
 ) -> Result<Vec<u8>, ()> {
-    // TODO: Pipe stderr so we can tell the user which commit, file, and tool it is
-    // associated with.
     let mut vars: HashMap<&str, &str> = HashMap::new();
     vars.insert("path", file_to_fix.repo_path.as_internal_file_string());
+    if let Some(root) = workspace_root.to_str() {
+        vars.insert("root", root);
+    }
```
Comment (yuja) [inline cli/src/commands/fix.rs:264]: nit: better to return error if `.to_str()` failed?

File: cli/tests/test_fix_command.rs [hunk 2]
```diff
@@ -513,6 +513,84 @@ fn test_relative_paths() {
...
+    // Copy the fake-formatter into the workspace as a relative tool
+    let formatter_path = assert_cmd::cargo::cargo_bin("fake-formatter");
+    let formatter_name = formatter_path.file_name().unwrap().to_str().unwrap();
+    let tool_dir = work_dir.create_dir("tools");
+    let workspace_formatter_path = tool_dir.root().join(formatter_name);
+    std::fs::copy(&formatter_path, &workspace_formatter_path).unwrap();
+    work_dir.write_file(".gitignore", "tools/\n");
+    let formatter_relative_path = std::path::Path::new("$root")
+        .join("tools")
+        .join(formatter_name);
```
Comment (yuja) [inline cli/tests/test_fix_command.rs]: nit: `PathBuf::from_iter([..])` also works

File: docs/config.md [hunk 3]
```diff
@@ -1216,6 +1216,23 @@ command = ["sort", "-u"]
...
 
+### Tools stored inside the workspace
+
+Some fix tools may be stored inside the workspace. For example, a binary may be
+stored inside `node_modules`.
+
+On Windows, [relative paths for commands are resolved using the parent process's
+working directory][win-relative-command], not the working directory of the new
+process. To define a fix tool stored inside the workspace on Windows, use the
+`$root` variable to create an absolute path:
```
Comment (yuja) [inline docs/config.md]: nit: This is technically true, but I don't think we guarantee that a relative executable path is resolved against the workspace root on Unix either. It's rather an implementation detail.

**Review by yuja — APPROVED** [review]
Looks good to me, thanks.

File: cli/src/commands/fix.rs (hunk 1 above)
Comment (jennings) [reply cli/src/commands/fix.rs:264]: The repo could be in a path that isn't UTF-8, which is when `to_str()` would return `None`.

If we return an error, then `jj fix` doesn't work at all even if the fix tool doesn't use `$root` in its `command`. That's why I thought it would be okay to ignore the failure case here.

File: docs/config.md (hunk 3 above)
Comment (jennings) [reply docs/config.md]: Would you prefer to unconditionally say, "Use `$root` to define a workspace-relative command" and not even mention that it works without on Linux and macOS? Or, add at afterwards as explanatory text, like this:

> Some fix tools may be stored inside the workspace. For example, a binary may be stored inside `node_modules`. Use the `$root` variable to create an absolute path to such a program:
> 
> ```toml
> [fix.tools.biome]
> 
> # Linux and macOS
> command = ["$root/node_modules/@biomejs/cli-linux-x64/biome"]
> 
> # Windows
> command = ["$root\\node_modules\\@biomejs\\cli-win32-x64\\biome.exe"]
> ```
> 
> This variable is necessary on Windows because [relative paths for commands are resolved using the parent process's working directory][win-relative-command], not the working directory of the child process.
> 
> This isn't strictly necessary on Linux or macOS because these platforms resolve commands relative to the working directory of the child process.
> 
> [win-relative-command]: https://github.com/rust-lang/rust/issues/37868

File: cli/src/commands/fix.rs (hunk 1 above)
Comment (yuja) [reply cli/src/commands/fix.rs:264]: Can you leave a TODO comment then? I don't think silent substitution failure is good either.

A better option might be to use bytes-based substitution on Unix, but that would require non-trivial changes.

File: docs/config.md (hunk 3 above)
Comment (yuja) [reply docs/config.md]: > Would you prefer to unconditionally say, "Use $root to define a workspace-relative command" and not even mention that it works without on Linux and macOS?

Yes. I think that's better. I didn't expect workspace-relative command would work on Unix.

File: cli/src/commands/fix.rs (hunk 1 above)
Comment (jennings) [reply cli/src/commands/fix.rs:264]: A warning or error would be nice if running `jj fix`, the fix command actually uses `$root`, and `workspace_root.to_str()` returned `None`.

But I'd only want to emit that once, not once per file, so it seems slightly tricky unless `Ui` already has a way to deduplicate warnings.

Comment (jennings) [reply cli/src/commands/fix.rs:264]: Oh I posted my last comment without seeing your reply. Yes, I'll add the TODO, thanks.
