### PR TITLE
completion: do not resolve aliases in the argument the cursor sits at

### LINKED ISSUE #7773: Dynamic completion of a diff tool command completes to the last argument
## Steps to Reproduce the Problem

1. `jj config set --user aliases.foo '["diff", "--tool", "meld-3"]'`
1. `jj foo<TAB>`

## Expected Behavior

A space inserted.

## Actual Behavior

Command morphed to `jj meld-3`

## Specifications

- Platform: Git Bash in Windows Terminal
- Version: 0.34.0-22900c9a9ba362efa442fed2dd4e6e1d5c22cc7a

### PR DESCRIPTION
**Pull request by jgreitemann**
Fixes #7773.

Given a command alias "foo", the `expand_args` function applies the
expansion also to the completion arguments `["jj", "foo"]`, replacing
the `"foo"` token with whatever the alias resolves to. This is
undesirable as long as the cursor still sits at the alias subcommand:

The completion results pertaining to the resolved command are probably
not prefixed by the alias token that the completion has been invoked
on. Hence, zsh and fish ignored them (but also didn't insert a space to
advance the cursor to the next token), whereas bash replaced the alias
token with the last token of the expanded command.

This behavior was even troublesome when the alias happens to prefix the
aliased command, like for example the `"b"` alias for `bookmark`:
When completing after the `"b"`, the alias was resolved, causing the
completion to only suggest `bookmark`. However, there's now also the
`bisect` subcommand which should also be a viable completion candidate.

This is now fixed by excluding the last token (which the cursor sits at)
from the alias resolution during completion. Note that for the
resolution of the default command, the contents of the cursor matter, so
we cannot simply truncate the input to `expand_args`, we need to resolve
default command and aliases separately and differently in the context of
command completion.

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
~~- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)~~
~~- [ ] I have updated the config schema (`cli/src/config-schema.json`)~~
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/cli_util.rs [hunk 1]
```diff
@@ -3775,6 +3776,23 @@ pub fn expand_args(
...
+) -> Result<Vec<String>, CommandError> {
+    let string_args = to_string_args(args_os)?;
+    let mut string_args = resolve_default_command(ui, config, app, string_args)?;
+
+    // The argument which the cursor sits at should not be considered in alias
+    // resolution.
+    let cursor_arg = string_args.pop();
+    let mut resolved_args = resolve_aliases(ui, config, app, string_args)?;
+    resolved_args.extend(cursor_arg);
+    Ok(resolved_args)
```
Comment (yuja) [inline cli/src/cli_util.rs:3779]: Is this basically the same as `expand_args()` with `index` instead of `index + 1`?

iirc, we don't have a way to distinguish `foo<TAB>` from `foo <TAB>` (in zsh completion script, I think.) The latter should expand `foo`. I don't know if it is still the case, but can you test behaviors on bash, fish, and zsh?

Comment (jgreitemann) [reply cli/src/cli_util.rs:3779]: > Is this basically the same as expand_args() with index instead of index + 1?

That was my first thought as well but doing it this way would break the resolution of the default command:
* If the cursor token was blanketly omitted from the expansion, `jj c<TAB>` would result in `expand_args(["jj"])` which would then trigger `resolve_default_command` to insert the default command (say, `log`), which would then pass `["jj", "log", "c"]` to the regular completion engine, resulting in "c" being completed as a fileset ("cli" in the jj repo), rather than as a subcommand ("commit", "config"). So `resolve_default_command` needs to see the cursor token to prevent it from triggering.
* In contrast, the token which the cursor sits at really should be excluded from the resolution of the subcommand aliases because otherwise `["jj", "b"]` is resolved to `["jj", "bookmark"]`, omitting the other viable subcommand completion candidate, "bisect".

So unfortunately, I don't think it is possible to use the same `expand_args` function to cater both the final argument expansion and the "partial" expansion that's needed for completion. It's a good thing though, that the two aspects (default command & aliases) were already separated, so both versions of `expand_args` could reuse the actual tricky bits.

> iirc, we don't have a way to distinguish `foo<TAB>` from `foo <TAB>` (in zsh completion script, I think.) The latter should expand `foo`.

The completion script on zsh _does_ work differently from bash, fish, and PowerShell in that it doesn't pass an empty token when completing after the space. However, it is possible to distinguish between `foo<TAB>` and `foo <TAB>` based on the `_CLAP_COMPLETE_INDEX` env var. `handle_shell_completion()` is already taking care of this by padding out the arguments prior to expansion.

The `TestEnvironment` also simulates the different behaviors in the `Shell`-parametrized tests. But of course it's best to check, particularly since we might not notice if the clap completion script's behavior changes due to a dependency update.

> I don't know if it is still the case, but can you test behaviors on bash, fish, and zsh?

Already did that and it works on all of them.

The original bug could be reproduced on all of them in more or less the same way. The only difference is that zsh and fish themselves filter the completion candidates and will only show candidates that are actually prefixed by the current token whereas bash will happily replace the current token with the completion candidate. So in the repro given in the original bug report (`jj config set --user aliases.foo '["diff", "--tool", "meld-3"]'`), completing `jj foo<TAB>` resolved to `jj diff --tool meld-3<TAB>` which then came back with `meld-3` as the sole completion candidate. Zsh and fish discarded this (but also didn't insert a space, as the completion was unsuccessful), whereas bash changed the "foo" to "meld-3".

Comment (yuja) [reply cli/src/cli_util.rs:3779]: > * If the cursor token was blanketly omitted from the expansion, `jj c<TAB>` would result in `expand_args(["jj"])` which would then trigger `resolve_default_command` to insert the default command (say, `log`), which would then pass `["jj", "log", "c"]` to the regular completion engine, resulting in "c" being completed as a fileset ("cli" in the jj repo), rather than as a subcommand ("commit", "config"). So `resolve_default_command` needs to see the cursor token to prevent it from triggering.
> 
> * In contrast, the token which the cursor sits at really should be excluded from the resolution of the subcommand aliases because otherwise `["jj", "b"]` is resolved to `["jj", "bookmark"]`, omitting the other viable subcommand completion candidate, "bisect".

I see. So we prioritize "no default command" candidates when the word at the cursor position can be expanded to both global command name/args and default-command args, which is why `resolve_default_command()` needs the word at the cursor position.

I think this can be documented in the code.

> Already did that and it works on all of them.

Thanks for the explanation. It's good to know that we have tests for these edge cases.
