### PR TITLE
completion: avoid panic when completing non-normal paths

### LINKED ISSUE #6861: Completion of non-normalized file path does not produce candidates and may panic
## Description

When invoking dynamic completion on any fileset command line argument, the current implementation assumes that the file path that is being completed is a prefix of all the candidates found through `jj file list`. For instance, in the jj repo, typing `CHANGELOG`<kbd>&lt;TAB&gt;</kbd>, will produce `CHANGELOG.md` as the only matching path, and `CHANGELOG.md` indeed starts with `CHANGELOG`.

However, this assumption breaks down once the fileset argument is not normalized. For example, typing `./CHANGELOG`<kbd>&lt;TAB&gt;</kbd> does not produce any completion candidates because `jj file list` resolves the glob to the normalized `CHANGELOG.md` which does not start with `./CHANGELOG` and is discarded.

Worse still, when the non-normalized fileset is longer than the completed path it resolves to, it produces a panic due to the unchecked slicing in this function:
https://github.com/jj-vcs/jj/blob/34b0961c940e1ad3be5cd9c5f5e608b0aa0ba859/cli/src/complete.rs#L628-L632
This panic could be easily avoided by using [`str::strip_prefix()`](https://doc.rust-lang.org/std/primitive.str.html#method.strip_prefix) instead of slicing which would spell out this assumption and additionally verify that we're slicing away the expected `current.len()` bytes. However, this would still lead to the legitimate completion candidate being discarded.

A more thorough solution would probably need to use something like the [normalize-path crate](https://docs.rs/normalize-path/latest/normalize_path/). In contrast, [`std::fs::canonicalize()`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) requires files to exist to resolve symlinks which precludes it from being used on revisions other than `@`.

## Steps to Reproduce the Problem

Taking the jj repo as an example
1. `jj file show ./CHANGELOG`<kbd>&lt;TAB&gt;</kbd> → no completion results
2. `jj file show ./CHANGELOG.md`<kbd>&lt;TAB&gt;</kbd> panics
```
thread 'main' panicked at cli/src/complete.rs:629:9:
byte index 14 is out of bounds of `CHANGELOG.md`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
3. `RUST_BACKTRACE=1 jj file show cli/../CHANG`<kbd>&lt;TAB&gt;</kbd> panics
```
thread 'main' panicked at cli/src/complete.rs:629:9:
byte index 13 is out of bounds of `CHANGELOG.md`
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
   4: jj_cli::complete::dir_prefix_from
   5: <itertools::adaptors::coalesce::CoalesceBy<I,F,C> as core::iter::traits::iterator::Iterator>::next
   6: jj_cli::complete::all_files_from_rev
   7: <F as clap_complete::engine::custom::ValueCompleter>::complete
   8: clap_complete::engine::complete::complete_arg_value
   9: clap_complete::engine::complete::complete_arg
  10: clap_complete::engine::complete::complete
  11: <clap_complete::env::shells::Fish as clap_complete::env::EnvCompleter>::write_complete
  12: jj_cli::cli_util::CliRunner::run
  13: jj::main
```

## Expected Behavior
Ideally, triggering completion on non-normalized paths should produce candidates which preserve the typed path, i.e. completing to `./CHANGELOG.md` in the first two cases and to `cli/../CHANGELOG.md` in the third. 

Alternatively, I guess it would be acceptable to use the path as returned by `jj file list` which would replace the argument with `CHANGELOG.md` in all three cases.

## Specifications

- Platform: reproduced on macOS & Linux; probably Windows affected, too. (Possibly, Windows accepting both `/` and `\` as path separators may introduce another failure mode, but I cannot check at the moment.)
- Version: reproduced with jj 0.30.0 and jj 0.28.2.

### PR DESCRIPTION
**Pull request by jgreitemann**
Fixes #6861

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/complete.rs [hunk 1]
```diff
@@ -739,14 +740,57 @@ pub fn branch_name_equals_any_revision(current: &std::ffi::OsStr) -> Vec<Complet
...
 
-fn dir_prefix_from<'a>(path: &'a str, current: &str) -> Option<&'a str> {
-    let remainder = path.strip_prefix(current).unwrap_or(path);
-    remainder
-        .split_once(std::path::MAIN_SEPARATOR)
-        .map(|(next, _)| {
-            path.split_at(path.len() - remainder.len() + next.len() + 1)
-                .0
-        })
+fn is_path_separator(c: char) -> bool {
```
Comment (scott2000) [inline cli/src/complete.rs]: It might be better to use `std::path::is_separator` instead of manually defining this function

**Comment by yuja** [comment]
Maybe it's easier to normalize input to `RepoPath` and strip prefix from repo-relative path output (i.e. `path` instead of `path.display()` in template)? That will also fix Windows Bash issue. https://github.com/jj-vcs/jj/issues/7024

**Comment by jgreitemann** [comment]
Easier in the sense that RepoPath uses `/` on either platform? Yes, unless we ever want to support completion on Powershell at some point. Idk, maybe slashes would be permissible there too, I've never understood when `/` works on Windows and when you _need_ to use `\`... I also don't have a Windows machine to test that with.

If it's just Git Bash (and other POSIX shells in MinGW et al. environments), I'd lean towards sticking with the native path separator in general and fix the Git Bash issue separately by using `slash_path` on the result if `COMPLETE=bash` is used on `cfg!(windows)`.

**Comment by yuja** [comment]
> Easier in the sense that RepoPath uses `/` on either platform?

Easier because the command output is also normalized (to repo-relative paths.) Post-processing would be simple if both inputs and outputs are in the canonical form. We can convert them back to backslash paths if needed.

File: cli/src/complete.rs (hunk 1 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: Thanks, I was not aware this existed. I went ahead with yuja's suggestion of using `RepoPath` and thus am able to use a plain `'/'` pattern, but there is still one instance where I'm now using `std::path::is_separator`.

**Comment by jgreitemann** [comment]
@yuja, I went with your suggestion and switched to `RepoPath`. Took me a moment to realize, but this is actually much better on Windows as it allows mixing and matching forward slashes with backslashes. The completion will now always use forward slashes which indeed fixes #7024. I've verified this in Git Bash on Windows, but also using dynamic completion in PowerShell (on both Windows and Linux, actually). As PowerShell doesn't mind forward slashes even on Windows, I agree that this is preferable and there's probably no need to try to convert back to backslash-separated paths.

File: cli/src/complete.rs [hunk 2]
```diff
@@ -739,10 +742,54 @@ pub fn branch_name_equals_any_revision(current: &std::ffi::OsStr) -> Vec<Complet
...
-        .map(|(next, _)| path.split_at(current.len() + next.len() + 1).0)
+fn path_completion_candidate_from(
+    current_prefix: &str,
+    path: &RepoPath,
+    mode: Option<&str>,
+) -> Option<CompletionCandidate> {
+    // The user-provided completion string might not prefix `path` unless cast in
+    // normal form.
+    let normalized_prefix =
+        RepoPathBuf::from_relative_path(normalize_path(Path::new(current_prefix))).ok()?;
```
Comment (yuja) [inline cli/src/complete.rs]: Perhaps, we'll have to use `RepoPathBuf::parse_fs_path()`. I think the `current_prefix` path is relative to cwd, not to workspace root.

It's also good to do normalize the input path once by caller instead of in the loop.

File: cli/src/complete.rs [hunk 3]
```diff
@@ -739,10 +742,54 @@ pub fn branch_name_equals_any_revision(current: &std::ffi::OsStr) -> Vec<Complet
...
+        Ok(file_completion) => (
+            file_completion?,
+            mode.map(|mode| match mode {
+                "modified" => "Modified".into(),
+                "removed" => "Deleted".into(),
+                "added" => "Added".into(),
+                "renamed" => "Renamed".into(),
+                "copied" => "Copied".into(),
+                _ => format!("unknown mode: '{mode}'").into(),
+            }),
```
Comment (yuja) [inline cli/src/complete.rs]: nit: I think the help text can be generated by caller.

Comment (jgreitemann) [reply cli/src/complete.rs]: Done. Passing `mode` now as `Option<clap::builder::StyledStr>` to avoid allocating `String` for known modes.

File: cli/src/complete.rs (hunk 2 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: Yikes. I did not realize that the `path` template always produces repo-relative paths and `.display()` changes that to be cwd-relative. Good thing you caught that because it was missing for the tests. I've now added a test case for that.

I tried to use `parse_fs_path()`, but I couldn't figure out a good way to get the repository root which I would've needed to pass as `base`. Or at least, I did find a way to express that in the templating language. Shelling out to `jj workspace root` would be an option but that would obviously mean spawning another process.

All things considered, I now reworked the PR in such a way that it uses both `normalize_path` and `slash_path` on the cwd-relative `display()` path and the completion input. That way, the root path is gone from the equation again. Unfortunately, that means that I'm back to using `&str`, so the normalization (both w.r.t. `.`/`..` and separators) is not encoded in the type system.

File: cli/src/complete.rs [hunk 4]
```diff
@@ -739,10 +740,51 @@ pub fn branch_name_equals_any_revision(current: &std::ffi::OsStr) -> Vec<Complet
...
+    mode: Option<clap::builder::StyledStr>,
+) -> Option<CompletionCandidate> {
+    // The user-provided completion string might not prefix `path` unless cast in
+    // normal form.
+    let normalized_prefix_path = normalize_path(Path::new(current_prefix));
+    let normalized_prefix = match normalized_prefix_path.to_str() {
+        None => current_prefix,
+        Some(".") => "", // `.` cannot be normalized further, but doesn't prefix `path`.
+        Some(normalized_prefix) => normalized_prefix,
+    };
```
Comment (yuja) [inline cli/src/complete.rs]: nit: since `current_prefix` never changes in the loop, I think normalization can be done by caller. Perhaps, a trailing slash can be added there.

File: cli/src/complete.rs [hunk 5]
```diff
@@ -811,36 +848,26 @@ fn modified_files_from_rev_with_jj_cmd(
...
+        .lines()
+        .filter_map(|line| line.split_once(' '))
+        .filter_map(|(mode, path)| {
+            let mode = match mode {
                 "modified" => "Modified".into(),
                 "removed" => "Deleted".into(),
                 "added" => "Added".into(),
-                "renamed" => "Renamed".into(),
+                "renamed" | "renamed.source" => {
+                    include_renames = true;
```
Comment (yuja) [inline cli/src/complete.rs:867]: nit: it's not needed to set `include_renames` by `"renamed"`. It only matters when `"renamed.source"` matches the current prefix.

File: cli/src/complete.rs (hunk 2 above)
Comment (yuja) [reply cli/src/complete.rs]: True, the workspace root is resolved by `get_jj_command()`, but it isn't passed in to completion functions. Maybe we can add `workspace_root: Option<PathBuf>` to `JjBuilder`, but I'm not sure if that is better than relying on cwd-relative paths.

File: cli/tests/test_completion.rs [hunk 6]
```diff
@@ -1535,16 +1535,18 @@ fn test_files() {
...
-    [EOF]
-    ");
+    insta::assert_snapshot!(
+        output.normalize_stdout_with(|s| s.replace(std::path::MAIN_SEPARATOR, "→")),
+        @r"
+        f_dir→dir_file_1	Added
+        f_dir→dir_file_2	Added
+        f_dir→dir_file_3	Added
+        f_dir→f_renamed_3	Renamed
+        [EOF]
```
Comment (yuja) [inline cli/tests/test_completion.rs:1550]: Can you add a comment what we're testing here?

File: cli/src/complete.rs (hunk 4 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: That comment is on a previous version. I've already moved normalization to the caller in the latest revision.
