### PR TITLE
revset: expand all() set to include all referenced commits

### LINKED ISSUE #5871: Incorrect revsets involving hidden commits and negation
## Description

Hidden revisions are not always included in a revset when they are explicitly mentioned by commit id.

## Steps to Reproduce the Problem

Here are some commands that demonstrate the issue
```
# The hidden commit is logged as normal
jj log --no-graph --template builtin_log_oneline --revisions 'e59f122f'
zksmnskl hidden dta 2 hours ago e59f122f (empty) <redacted description>
# The hidden commit is not logged when unioned a revset containing no revisions
jj log --no-graph --template builtin_log_oneline --revisions '(none() ~ empty()) | e59f122f'
# The hidden commit is still not logged when the negation does not match it
jj log --no-graph --template builtin_log_oneline --revisions '(none() ~ description(exact:"does not match actual description")) | e59f122f'
# Not all revsets cause this bug in conjunction with negation
jj log --no-graph --template builtin_log_oneline --revisions '(none() ~ description(exact:"does not match actual description")) | e59f122f'
jj log --no-graph --template builtin_log_oneline --revisions '(none() ~ all()) | e59f122f'
zksmnskl hidden dta 2 hours ago e59f122f (empty) <redacted description>
```

## Expected Behavior

Hidden revisions are always included in a revset when they are unioned with another revset

## Actual Behavior

This is not always the case

## Specifications

- Platform: Mac OSX
- Version: 0.26.0

### PR DESCRIPTION
**Pull request by yuja**
Fixes #5871

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/revset.rs [hunk 1]
```diff
@@ -1908,7 +1915,7 @@ fn fold_heads_range<St: ExpressionState>(
                     roots: filtered_range.roots,
                     heads: filtered_range
                         .heads
-                        .unwrap_or_else(RevsetExpression::visible_heads),
+                        .unwrap_or_else(|| Rc::new(RevsetExpression::ReferencedHeads)),
```
Comment (martinvonz) [inline lib/src/revset.rs]: nit: add a `referenced_heads()` (or `all_heads()` if you agree with my other comment) constructor in the same vein as `all()` etc and use that here and below?

File: lib/src/revset.rs [hunk 2]
```diff
@@ -231,6 +231,9 @@ pub type ResolvedRevsetExpression = RevsetExpression<ResolvedExpressionState>;
 pub enum RevsetExpression<St: ExpressionState> {
     None,
     All,
+    /// Visible heads and all referenced commits within the current expression
+    /// scope. Used as the default of `Range`/`DagRange` heads.
+    ReferencedHeads,
```
Comment (martinvonz) [inline lib/src/revset.rs]: I think `AllHeads` seems like a better name

File: docs/revsets.md [hunk 3]
```diff
@@ -52,10 +59,10 @@ only symbols.
 
 * `x-`: Parents of `x`, can be empty.
 * `x+`: Children of `x`, can be empty.
-* `x::`: Descendants of `x`, including the commits in `x` itself. Shorthand for
-  `x::visible_heads()`.
-* `x..`: Revisions that are not ancestors of `x`. Shorthand for
-  `x..visible_heads()`. Equivalent to `~::x`.
+* `x::`: Descendants of `x`, including the commits in `x` itself. Equivalent to
+  `x::visible_heads()` if no hidden revisions are mentioned.
```
Comment (martinvonz) [inline docs/revsets.md:63]: optional: If we make an `all_heads()` function available in the revset language, this can again be simplified to say that `x::` is a shorthand for `x::all_heads()`.

File: lib/src/revset.rs [hunk 4]
```diff
@@ -1523,6 +1545,18 @@ where
             operation,
             candidates,
         } => folder.fold_at_operation(operation, candidates)?,
+        RevsetExpression::WithinReference {
+            candidates,
+            commits,
+        } => {
+            let candidates = folder.fold_expression(candidates)?;
+            let commits = commits.clone();
```
Comment (martinvonz) [inline lib/src/revset.rs:1559]: nit: for consistency, inline here or un-inline on line 1339

File: lib/src/revset.rs (hunk 2 above)
Comment (yuja) [reply lib/src/revset.rs]: I avoided `AllHeads` because it sounds like all historical heads. How about `ReferencedOrVisibleHeads`?

File: lib/src/revset.rs (hunk 4 above)
Comment (yuja) [reply lib/src/revset.rs:1559]: I copied the style of the surrounding code. Maybe I choose un-inlined version here because it looked better in binary expression nodes.

File: lib/src/revset.rs (hunk 1 above)
Comment (yuja) [reply lib/src/revset.rs]: I could add a private function. I don't think there will be external callers.

File: docs/revsets.md (hunk 3 above)
Comment (scott2000) [reply docs/revsets.md:63]: Just a thought: if we define `all()` as `::all_heads()`, it might also be nice to also have `visible()` as `::visible_heads()` in the future (since now there's better support for hidden commits).

File: lib/src/revset.rs (hunk 2 above)
Comment (martinvonz) [reply lib/src/revset.rs]: I would not make the connection to historical heads, so I still prefer `AllHeads`. It matches `All` (which I also had not thought might include historical commits). If we add expressions for all historical heads, then `HistoricalHeads` sounds like a good name to me.

File: lib/src/revset.rs (hunk 1 above)
Comment (martinvonz) [reply lib/src/revset.rs]: I would slightly prefer that for consistency.

File: lib/src/revset.rs (hunk 4 above)
Comment (martinvonz) [reply lib/src/revset.rs:1559]: Leaving as is makes sense then. I only noticed the context lines shown by default.

File: docs/revsets.md (hunk 3 above)
Comment (yuja) [reply docs/revsets.md:63]: Yeah, `visible()` could be added. I'm not sure if we should add `all_heads()`, though, because I don't have any use cases other than documenting purpose, and we'll need to calculate `Heads(visible + referenced)` to remove non-head commits.

File: lib/src/revset.rs (hunk 2 above)
Comment (yuja) [reply lib/src/revset.rs]: In context of https://github.com/jj-vcs/jj/pull/6782#discussion_r2155998760, if we're going to add `all_heads()`, this `ReferencedHeads` should have to be named differently since `AllHeads = Heads(ReferencedHeads)`.

Comment (martinvonz) [reply lib/src/revset.rs]: I see. Since this is not just the heads of the combined set, I think `VisibleHeadsOrReferenced` is better (i.e. reverse from your suggestion), because the `Heads` made me think that this only refers to heads.

What would it take to make this expression refer to only the heads?

Comment (yuja) [reply lib/src/revset.rs]: > What would it take to make this expression refer to only the heads?

Basically we'll need to evaluate `index.heads(referred + visible)`.

Comment (yuja) [reply lib/src/revset.rs]: Renamed to `VisibleHeadsOrReferenced`, and added constructor fn.
