### PR TITLE
completion: only suggest set options for `jj config unset`

### LINKED ISSUE #7774: Dynamic completion for `config unset` does not complete aliases and shows many other not set keys
## Steps to Reproduce the Problem

1. `jj config set --user aliases.foo bar`
1. `jj config unset --user <TAB><TAB>`

## Expected Behavior

All config items that are set in the user file are provided as options, not more not less.

## Actual Behavior

- many config items that are not even set in the file are provided
- no aliases are provided

## Specifications

- Platform: Git Bash in Windows Terminal
- Version: 0.34.0-22900c9a9ba362efa442fed2dd4e6e1d5c22cc7a

### PR DESCRIPTION
**Pull request by jgreitemann**
Fixes #7774.

For a config option to be used with `jj config unset`, it has to have been given a user-defined value in either of the user, repo, or workspace config files. It does not make any sense to unset an option which has not been set. However, the dynamic completions previously completed config options in the same way for both `jj config set` and `jj config unset`, using the config schema as the static list of viable options. Aside from the multitude of potentially irrelevant defaulted options, this also meant that user-defined options such as (revset-)aliases or templates were not completed.

This is fixed now by drawing on the information provided by `jj config list` to get the user-defined options. Unfortunately, clap_complete does not provide a way to inspect the preceding arguments, so in order to whittle down the list according to the specified config "level" (`--user`, `--repo`, `--workspace`), the completer function has to attempt some rudimentary manual command line argument parsing. If no level has been specified yet (i.e., to the left of the cursor's position when triggering completion), options from all three levels are suggested. However, the user will have to add the corresponding flag explicitly for the unset command to succeed.

In shells which support completion candidate help (Zsh, Fish, PowerShell with PSCompletions), the help string includes both the applicable config level and the value that would be unset.

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- ~~[ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)~~
- ~~[ ] I have updated the config schema (`cli/src/config-schema.json`)~~
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/complete.rs [hunk 1]
```diff
@@ -755,6 +755,48 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
     }
 }
 
+pub fn unsettable_config_keys() -> Vec<CompletionCandidate> {
```
Comment (yuja) [inline cli/src/complete.rs]: nit: "unsettable" sounds like "cannot be set". maybe `config_keys_to_unset` work?

File: cli/src/complete.rs [hunk 2]
```diff
@@ -755,6 +755,48 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
...
+    let config_level_flags = std::env::args_os()
+        .skip_while(|arg| arg != "--")
+        .skip_while(|arg| arg != "config")
+        .skip_while(|arg| arg != "unset")
```
Comment (yuja) [inline cli/src/complete.rs]: nit: no need to skip until `unset`? other completion hack appears to scan the entire `std::env::args()`.

File: cli/src/complete.rs [hunk 3]
```diff
@@ -755,6 +755,48 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
...
+                arg.as_encoded_bytes(),
+                b"--user" | b"--repo" | b"--workspace"
+            )
+        });
+
+    with_jj(|jj, _| {
+        let mut config_level_specified = false;
+        let config_level_flags = config_level_flags.inspect(|_| {
+            config_level_specified = true;
+        });
```
Comment (yuja) [inline cli/src/complete.rs]: nit: this side-effect looks scary

File: cli/src/complete.rs [hunk 4]
```diff
@@ -755,6 +755,48 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
...
+        let list_output = jj
+            .build()
+            .args(["config", "list"])
+            .args(config_level_flags)
```
Comment (yuja) [inline cli/src/complete.rs]: I think we should only pass `--user`|`--repo`|`--workspace`. If we add other flag to `config unset`, `config list <unknown-flag>` wouldn't work.

File: cli/src/complete.rs [hunk 5]
```diff
@@ -755,6 +755,48 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
...
+            // Only suggest unsetting overridden config options if the corresponding level is already specified.
+            .args(config_level_specified.then_some("--include-overridden"))
+            .args([
+                "--template",
+                r#"name ++ "\n" ++ source ++ "\n" ++ stringify(value).lines().map(|line| line.trim()).join("") ++ "\n""#,
```
Comment (yuja) [inline cli/src/complete.rs]: nit: just use the first line of the value? The output of multi-line templates wouldn't be readable anyway.

fwiw, other completion functions use `\t` as a field separator. I think it would work better when there are unexpected lines in output.

File: cli/src/complete.rs [hunk 6]
```diff
@@ -755,6 +755,48 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
...
+            ])
+            .output()
+            .map_err(user_error)?;
+        Ok(String::from_utf8_lossy(&list_output.stdout)
+            .lines()
+            .tuples()
+            .filter(|(_, source, _)| matches!(*source, "user" | "repo" | "workspace"))
```
Comment (yuja) [inline cli/src/complete.rs:785]: Perhaps, we don't have to return candidates when config level isn't set.

File: cli/src/complete.rs (hunk 2 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: Yeah agreed. I was originally concerned about global of config-subcommand-level conflicting options, but that's probably never going to be a problem and it precludes `config_keys_to_unset` from being used in a different context.

File: cli/src/complete.rs (hunk 3 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: But is it really? Rust would catch all of the pitfalls that would make this scary in other languages. If I flip around the order of `.args(config_level_flags)` and `.args(config_level_specified.then_some(...))`, the borrow checker would rightfully complain. It also guarantees that `config_level_flags` has to have been consumed (if it ever is) by the time `.args()` returns. `inspect()` is explicitly allowed to have side-effects by the `FnMut` bound.

I could `collect` the args first and then use `is_empty()` to check if `--include-overridden` is needed, but that would incur extra overhead which is not really necessary. Sure, this is not a critical path, so I'd be happy to do it if you think it would be more _readable_, but I don't actually think it is less readable, it would just be really easy to mess up in, say, C++.

File: cli/src/complete.rs (hunk 4 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: `config_level_flags` will only ever produce those three flags because of the filter. The reason why I'm potentially passing multiple ones and not just the first (or last, or ...?) is that I actually think it is correct for `config unset --repo --user` to not produce any candidates because that would be invalid anyway. `config list --repo --user` does have that effect precisely.

File: cli/src/complete.rs (hunk 5 above)
Comment (jgreitemann) [reply cli/src/complete.rs]: Yeah I thought about this too. But then a multiline string value might result in something like `user: '''` as a help message. At least this way you get some impression of the value, even if it's truncated by the shell. I think the shell should decide what amount of presentation is appropriate.

I've switched to using `\t`.

File: cli/src/complete.rs (hunk 6 above)
Comment (jgreitemann) [reply cli/src/complete.rs:785]: The reason why I thought that it would make sense to suggest candidates from all levels was that I can see a situation where you don't remember if a setting was on the workspace, repo, or user level. Or you might have forgotten about a workspace-level or repo-level setting and wonder why you cannot unset the supposedly user-level setting. Personally, I think this is quite helpful behavior.

Obviously, it would be ideal if we could complete the key and the corresponding level flag at the same time, but that's not possible, unfortunately.

File: cli/src/complete.rs (hunk 3 above)
Comment (yuja) [reply cli/src/complete.rs]: I would say it's not as easy to follow as collected version, something like:

```rust
let config_level = config_level_flags.next();
if config_level.is_some() {
    ...
}
...
.args(config_level)
```

If the performance really matters, I agree it's good to write tricky code.

Comment (jgreitemann) [reply cli/src/complete.rs]: Ok, I've given it another pass. I went with itertools', `at_most_one()` rather than `next()` to keep the behavior of not suggesting anything in case of multiple level flags.

File: cli/src/complete.rs [hunk 7]
```diff
@@ -755,6 +755,40 @@ pub fn leaf_config_key_value(current: &std::ffi::OsStr) -> Vec<CompletionCandida
...
+    with_jj(|jj, _| {
+        let list_output = jj
+            .build()
+            .args(["config", "list"])
+            // Only suggest unsetting overridden config options if the corresponding level is already specified.
+            .args(config_level_flag.is_some().then_some("--include-overridden"))
+            .args(config_level_flag)
+            .args([
+                "--template",
+                r#"name ++ "\t" ++ source ++ "\t" ++ stringify(value).lines().map(|line| line.trim()).join("") ++ "\n""#,
```
Comment (yuja) [inline cli/src/complete.rs]: nit: extract it to `let template = "..."` for readability?

File: cli/tests/test_completion.rs [hunk 8]
```diff
@@ -1188,6 +1188,146 @@ fn test_config() {
...
+    template-aliases."format_time_range(time_range)"	user: 'time_range.start() ++ " - " ++ time_range.end()'
+    git.colocate	user: false
+    --user	Target the user-level config
+    --repo	Target the repo-level config
+    --workspace	Target the workspace-level config
+    [EOF]
+    "#);
+
+    test_env.add_config(
+        r#"
```
Comment (yuja) [inline cli/tests/test_completion.rs]: nit: we can use `indoc! {r#"..."#}` to indent this.

File: cli/src/complete.rs (hunk 5 above)
Comment (yuja) [reply cli/src/complete.rs]: Hmm, how about `.replace(regex:'\n\s*', ' ')` then?
