### PR TITLE
cli config edit: Rollback to previous config when invalid TOML is saved

### LINKED ISSUE #3905: `jj config edit` doesn't reject invalid TOML
## Steps to Reproduce the Problem

1. Edit user config `jj config edit --user` 
1. Add some invalid cargo like:
```
[ui]
editor = vim
```
Note the lack of quotes around `vim` 
1. quit your editor

## Expected Behavior

`jj config edit --user` quits with a message like "could not save, invalid toml"

## Actual Behavior

Any `jj` command (including  `jj config edit --user`) fails with: 

```
Config error: newline in string found at line 7 column 14 in ../../../../../Library/Application Support/jj/config.toml
```

Until you fix the problem. 

## Specifications

- Version: 0.18.0

### PR DESCRIPTION
**Pull request by tdaron**
This should fix #3905.

If applicable:

- [x] I have updated CHANGELOG.md.
- [x] I have added tests to cover my changes

My implementation is quite simple: if an error is added to the config, jj will prompt the user if he wants to keep editing the config. If the user don't want to, then the bad config is overwritten with the previous working one (Without the need of any temporary file). Otherwise, the user can fix the error

### CODE REVIEW

**Comment by PhilipMetzger** [comment]
please adhere to the commit style outlined in our documentation, thanks.

File: cli/src/commands/config/edit.rs [hunk 1]
```diff
@@ -41,5 +42,17 @@ pub fn cmd_config_edit(
         file.save()?;
     }
     editor.edit_file(file.path())?;
+
+    // Trying to load back config. If error, saves the old config and warn the user.
+    if let Err(e) = ConfigLayer::load_from_file(file.layer().source, file.path().to_path_buf()) {
+        writeln!(
+            ui.error_with_heading("Error: "),
+            "An error has been found inside your config. Restoring previous one."
+        )?;
```
Comment (yuja) [inline cli/src/commands/config/edit.rs:51]: nit: use `user_error_with_message()` or something to error out. (or use `ui.warning_default()` to print warning and continue.)

File: cli/src/commands/config/edit.rs [hunk 2]
```diff
@@ -41,5 +42,17 @@ pub fn cmd_config_edit(
...
+
+        // Saving back previous config
+        file.save()?;
```
Comment (yuja) [inline cli/src/commands/config/edit.rs:54]: We'll probably need to copy the bad file to temporary file. The user wouldn't want to start editing from scratch.

Comment (tdaron) [reply cli/src/commands/config/edit.rs:54]: it would mean the user would have to manually copy from the temp file to the "true" config file, idk if it's something wanted 🤔

What about saving the old "working" config in a temp file, and if the actual config file don't work then we show a warning and load the last working config from this temp file? So the user could simply do `jj config edit` to edit the non-working config and as soon as it works jujutsu stars re-using it ?

File: cli/src/commands/config/edit.rs [hunk 3]
```diff
@@ -40,6 +41,36 @@ pub fn cmd_config_edit(
...
+        {
+            let command_error: CommandError = e.into();
+            print_error(
+                ui,
+                "Config error: ",
+                &command_error.error,
+                &command_error.hints,
+            )?;
+            edit_config = ui.prompt_yes_no(
+                "Do you want to keep editing the file ? If not, previous config will be restored. ",
```
Comment (tdaron) [inline cli/src/commands/config/edit.rs:63]: I had to use print_error here so i can print precise TOML error without exiting jj. i don't know if there is a cleaner way to do this (without having print_error going `pub`)

Comment (yuja) [reply cli/src/commands/config/edit.rs:64]: You can use `writeln!(ui.warning_default(), ..)` (and `print_error_sources()` if needed.)

File: cli/src/commands/config/edit.rs (hunk 2 above)
Comment (yuja) [reply cli/src/commands/config/edit.rs]: > Seems like a good solution to simply prompt the user to keep editing, it's simpler

Yes.

File: cli/src/commands/config/edit.rs (hunk 3 above)
Comment (tdaron) [reply cli/src/commands/config/edit.rs]: oh nice print_error_sources is much simpler. I used it as it allows user to directly see where the error is (even if it's pretty obvious that it's coming from what the user just added to the config)

File: cli/src/commands/config/edit.rs [hunk 4]
```diff
@@ -40,6 +42,34 @@ pub fn cmd_config_edit(
     if !file.path().exists() {
         file.save()?;
     }
-    editor.edit_file(file.path())?;
+
+    // Editing again and again until
+    // 1. The config is OK
+    // 2. The user restore previous one
+    let mut edit_config = true;
+    while edit_config {
```
Comment (yuja) [inline cli/src/commands/config/edit.rs:50]: nit: I would simply use `loop {` with `return` or `break`.

File: cli/src/commands/config/edit.rs [hunk 5]
```diff
@@ -40,6 +42,34 @@ pub fn cmd_config_edit(
...
+        // Trying to load back config. If error, prompt to continue editing
+        if let Err(e) = ConfigLayer::load_from_file(file.layer().source, file.path().to_path_buf())
+        {
+            writeln!(
+                ui.warning_default(),
+                "An error has been found inside the config:"
+            )?;
+            print_error_sources(ui, Some(&e))?;
+            edit_config = ui.prompt_yes_no(
+                "Do you want to keep editing the file ? If not, previous config will be restored. ",
```
Comment (yuja) [inline cli/src/commands/config/edit.rs:62]: nit: remove space before `?` and after `.`

File: cli/src/commands/config/edit.rs
Comment (yuja) [inline cli/src/commands/config/edit.rs:1]: Can you add a basic test? I think you can copy some bits from `test_next_prev_commands.rs` and `test_describe_command.rs` for prompt and editor interaction respectively.

**Review by yuja — COMMENTED** [review]
The implementation looks good, thanks.

File: cli/src/commands/config/edit.rs
Comment (tdaron) [reply cli/src/commands/config/edit.rs:1]: Just added a test to check if the config error is well detected. However, I don't know if it is possible to change config file content as `jj_run_with` is still running to test if the re-edit works well.

File: cli/src/commands/config/edit.rs [hunk 6]
```diff
@@ -40,6 +42,34 @@ pub fn cmd_config_edit(
...
+    // Editing again and again until
+    // 1. The config is OK
+    // 2. The user restore previous one
+    loop {
+        editor.edit_file(file.path())?;
+
+        // Trying to load back config. If error, prompt to continue editing
+        if let Err(e) = ConfigLayer::load_from_file(file.layer().source, file.path().to_path_buf())
+        {
+            writeln!(
```
Comment (yuja) [inline cli/src/commands/config/edit.rs:55]: nit: this could be better expressed as `let Err(e) = ... else { break; };`, but I don't feel strongly.

**Review by yuja — APPROVED** [review]

File: cli/src/commands/config/edit.rs (hunk 6 above)
Comment (tdaron) [reply cli/src/commands/config/edit.rs:55]: I left the previous explicit if statement as I found it more readable

File: cli/src/commands/config/edit.rs
Comment (tdaron) [reply cli/src/commands/config/edit.rs:1]: Nice to know ! The test is updated :)

**Comment by tdaron** [comment]
everything should be all good :)

File: cli/src/commands/config/edit.rs [hunk 7]
```diff
@@ -40,6 +42,34 @@ pub fn cmd_config_edit(
...
+                ui.warning_default(),
+                "An error has been found inside the config:"
+            )?;
+            print_error_sources(ui, Some(&e))?;
+            let contine_editing = ui.prompt_yes_no(
```
Comment (cenviity) [inline cli/src/commands/config/edit.rs:60]: nit: continue

File: cli/src/commands/config/edit.rs [hunk 8]
```diff
@@ -40,6 +42,34 @@ pub fn cmd_config_edit(
     if !file.path().exists() {
         file.save()?;
     }
-    editor.edit_file(file.path())?;
+
+    // Editing again and again until
+    // 1. The config is OK
+    // 2. The user restore previous one
```
Comment (cenviity) [inline cli/src/commands/config/edit.rs:48]: nit: restores

File: cli/src/commands/config/edit.rs [hunk 9]
```diff
@@ -40,6 +42,34 @@ pub fn cmd_config_edit(
     if !file.path().exists() {
         file.save()?;
     }
-    editor.edit_file(file.path())?;
+
+    // Editing again and again until
```
Comment (cenviity) [inline cli/src/commands/config/edit.rs:46]: Perhaps change to ‘[…] until either of these conditions is met:’ for clarity?

File: cli/tests/test_config_command.rs [hunk 10]
```diff
@@ -950,6 +951,48 @@ fn test_config_edit_repo() {
...
+    1: Configuration cannot be parsed as TOML document
+    2: TOML parse error at line 1, column 9
+      |
+    1 | invalid config here
+      |         ^
+    expected `.`, `=`
+
+    Do you want to keep editing the file? If not, previous config will be restored. (Yn): [EOF]
+    ");
+    std::fs::write(&edit_script, "write\n[revset-aliases]").unwrap();
```
Comment (yuja) [inline cli/tests/test_config_command.rs:985]: nit: add test sample for the restore, which was previously implicitly tested by the subsequent `config edit`.

File: cli/src/commands/config/edit.rs (hunk 6 above)
Comment (yuja) [reply cli/src/commands/config/edit.rs:55]: If you like explicit control flow, `match` would look nicer.

File: cli/tests/test_config_command.rs (hunk 10 above)
Comment (tdaron) [reply cli/tests/test_config_command.rs]: tests should be complete now i think. i removed the "valid config" test as it overlap with others tests that already test that.

File: cli/tests/test_config_command.rs [hunk 11]
```diff
@@ -950,6 +951,89 @@ fn test_config_edit_repo() {
...
+    Do you want to keep editing the file? If not, previous config will be restored. (Yn): [EOF]
+    ");
+
+    let output = work_dir.run_jj_with(|cmd| {
+        force_interactive(cmd)
+            .arg("config")
+            .arg("get")
+            .arg("test")
+            .write_stdin("Y\n")
+    });
```
Comment (yuja) [inline cli/tests/test_config_command.rs:994]: nit: you can use `run_jj(["config", "get", "test"])` here.

you can also use `.args([..])` to save vertical space in interactive case.

**Comment by tdaron** [comment]
should be okay now :dancing_men:

File: CHANGELOG.md [hunk 12]
```diff
@@ -127,6 +127,8 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 * `jj resolve` now accepts new built-in merge tools `:ours` and `:theirs`.
   These merge tools accept side #1 and side #2 of the conflict respectively.
 
+* `jj config edit` will now rollback to previous version if an error has been induced in the new config.
```
Comment (yuja) [inline CHANGELOG.md:130]: Just reminder. You'll need to move the changelog entry.

**Review by yuja — COMMENTED** [review]
@tdaron I thought this would have been merged. If you don't have a permission to push the merge button, please let us know.

cc @martinvonz

**Comment by martinvonz** [comment]
> @tdaron I thought this would have been merged. If you don't have a permission to push the merge button, please let us know.

Looks like I had missed that. I've invited @tdaron now. Thanks for letting me know!

**Comment by tdaron** [comment]
thanks. didn't know if I had to wait for another review ahah

File: CHANGELOG.md (hunk 12 above)
Comment (tdaron) [reply CHANGELOG.md:130]: Into fixed bugs ? Already moved it into New features

Comment (martinvonz) [reply CHANGELOG.md:130]: Into "[Unreleased]"

Comment (tdaron) [reply CHANGELOG.md:130]: ooh ok my bad. I'll fix and merge asap
