### PR TITLE
cli show: add `--no-patch` flag

### LINKED ISSUE #5036: `jj show -T` always generates diff
## Description

When I use `-T` with `jj show`, the diff is always generated and printed after the template output.

## Steps to Reproduce the Problem

In a jj repository with changes to the working copy.

```sh
jj show -T 'self.empty()'
```

## Expected Behavior

Outputs only `true` or `false`.

## Actual Behavior

Outputs `true` or `false` followed by the entire diff of changes in the working copy.

## Specifications

- Platform: Linux x86_64
- Version: jj 0.24.0-32d2a85539254e9d96f9819072fa5c6ac70dd1e4

### PR DESCRIPTION
**Pull request by gechr**
Closes #5036

### CODE REVIEW

**Comment by yuja** [comment]
As I said, `-T` shouldn't be the flag to control the diff output. If we really need this behavior, we should add `--no-patch` or something (or make `jj show` not imply `-p` by default.)

File: cli/src/commands/show.rs [hunk 1]
```diff
@@ -50,6 +50,9 @@ pub(crate) struct ShowArgs {
     template: Option<String>,
     #[command(flatten)]
     format: DiffFormatArgs,
+    /// Do not show the patch.
+    #[arg(long, short = 'P')]
```
Comment (yuja) [inline cli/src/commands/show.rs:54]: nit: 

* add `conflicts_with = "DiffFormatArgs"` to reject `--no-patch --git`, etc.
* remove period from summary line of help text
* remove short flag for now? I'm not sure if we need short flag.

File: cli/src/commands/show.rs [hunk 2]
```diff
@@ -65,11 +68,15 @@ pub(crate) fn cmd_show(
         None => workspace_command.settings().get_string("templates.show")?,
     };
     let template = workspace_command.parse_commit_template(ui, &template_string)?;
-    let diff_renderer = workspace_command.diff_renderer_for(&args.format)?;
-    ui.request_pager();
+    if !args.no_patch {
+        ui.request_pager();
+    }
```
Comment (yuja) [inline cli/src/commands/show.rs:73]: I don't think it makes sense to suppress pager by `--no-patch`.

File: cli/src/commands/show.rs [hunk 3]
```diff
@@ -65,11 +68,15 @@ pub(crate) fn cmd_show(
         None => workspace_command.settings().get_string("templates.show")?,
     };
     let template = workspace_command.parse_commit_template(ui, &template_string)?;
-    let diff_renderer = workspace_command.diff_renderer_for(&args.format)?;
```
Comment (yuja) [inline cli/src/commands/show.rs:68]: nit: better to check configuration error here (before spawning pager)

**Review by yuja — COMMENTED** [review]
Thanks. I think `show --no-patch` is good, but I'll leave this open for a while to gather comments.

File: cli/src/commands/show.rs (hunk 1 above)
Comment (yuja) [reply cli/src/commands/show.rs]: Out of curiosity, what's your use case? (I assumed `show --no-patch -T` could be useful in scripting, but wouldn't be used much as interactive command.)

I don't have strong feeling either, but `jj show -P` doesn't sound like an option to suppress patch.

File: cli/tests/test_show_command.rs [hunk 4]
```diff
@@ -255,6 +255,52 @@ fn test_show_with_template() {
...
 }
 
+#[test]
+fn test_show_with_template_no_patch() {
+    let test_env = TestEnvironment::default();
+    test_env.run_jj_in(".", ["git", "init", "repo"]).success();
+    let repo_path = test_env.env_root().join("repo");
+
+    test_env
+        .run_jj_in(&repo_path, ["new", "-m", "a new commit"])
```
Comment (martinvonz) [inline cli/tests/test_show_command.rs:265]: nit: use the new `test_env.work_dir()` API

File: CHANGELOG.md [hunk 5]
```diff
@@ -132,6 +132,8 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 * `jj resolve` now accepts new built-in merge tools `:ours` and `:theirs`.
   These merge tools accept side #1 and side #2 of the conflict respectively.
 
+* `jj show` patches can now be suppressed with `--no-patch`.
```
Comment (yuja) [inline CHANGELOG.md:135]: reminder: you'll need to relocate the changelog entry.

We'll have a point release today or tomorrow, so please hold this change until then.

**Review by yuja — APPROVED** [review]
Looks good, thanks.
