### PR TITLE
file_util: fix broken symlink on Windows

### LINKED ISSUE #8185: Windows symlink is not correctly created
## Description

The symlink created by `jj` uses the wrong separator `/`, which makes the symlink broken.

This can be fixed by the following patch:

```
diff --git a/lib/src/file_util.rs b/lib/src/file_util.rs
index 683a996d7c..01d22c138f 100644
--- a/lib/src/file_util.rs
+++ b/lib/src/file_util.rs
@@ -347,6 +347,8 @@
         // note: if developer mode is not enabled the error code will be 1314,
         // ERROR_PRIVILEGE_NOT_HELD

+        let original = original.as_ref();
+        let original = original.components().fold(std::path::PathBuf::new(), |res, component| res.join(component));
         symlink_file(original, link)
     }
 }
```

## Steps to Reproduce the Problem

1. jj git clone https://github.com/jj-vcs/jj.git
1. jj new a1c9c3daff5c43243be5623b5621c75e0eeb652f 

## Expected Behavior

`docs/governance/GOVERNANCE.md` file, should be a symlink to `..\..\GOVERNANCE.md`.

## Actual Behavior

`docs/governance/GOVERNANCE.md` is a broken symlink to `../../GOVERNANCE.md`. Note the difference in the separators.

## Specifications

- Platform: Windows
- Version: jj 0.34.0-22900c9a9ba362efa442fed2dd4e6e1d5c22cc7a

### PR DESCRIPTION
**Pull request by 06393993**
... due to using incorrect separators.

Fix #8185.

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/file_util.rs [hunk 1]
```diff
@@ -347,6 +347,13 @@ mod platform {
         // note: if developer mode is not enabled the error code will be 1314,
         // ERROR_PRIVILEGE_NOT_HELD
 
+        // Use the main separator to reformat the input path to avoid creating a broken symlink with the incorrect separator "/". See https://github.com/jj-vcs/jj/issues/8185 for the releavant bug.
```
Comment (PhilipMetzger) [inline lib/src/file_util.rs]: nit: "releavant" => "relevant"

Comment (06393993) [reply lib/src/file_util.rs]: Done.

**Comment by yuja** [comment]
Directory separators in symlink content will have to be transformed back and forth by local working copy. See https://github.com/jj-vcs/jj/pull/6977#discussion_r2203727518 for the previous discussion.

**Comment by 06393993** [comment]
> Directory separators in symlink content will have to be transformed back and forth by local working copy. See [#6977 (comment)](https://github.com/jj-vcs/jj/pull/6977#discussion_r2203727518) for the previous discussion.

Then I have a question. What's the plan for handling absolute paths?

**Comment by yuja** [comment]
> > Directory separators in symlink content will have to be transformed back and forth by local working copy. See [#6977 (comment)](https://github.com/jj-vcs/jj/pull/6977#discussion_r2203727518) for the previous discussion.
> 
> Then I have a question. What's the plan for handling absolute paths?

What's different between relative and absolute paths? Absolute paths (and symlinks pointing to out of the tree) wouldn't work on different machines, but I don't think it's wrong to translate `/foo/bar` to `\foo\bar` (or `c:\foo` to `c:/foo`.)

**Comment by 06393993** [comment]
> What's different between relative and absolute paths?

On Windows, absolute paths don't always start with a drive ID(e.g. `C:`). There are [many possible prefixes](https://doc.rust-lang.org/stable/std/path/enum.Prefix.html). For verbatim paths (i.e., prefixed with `\\?\`), `/` should *not* be treated as a separator.

However, given the [Windows path name convention](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), `/` can't be part of a file name or a directory name, so I also don't think there can be an actual issue with just always applying the slash conversion on snapshot and update on Windows. But we should just do a stirng level character replacement so that the following Windows absolute paths won't get messed up on the same machine[^1]:

[^1]: The example paths come from https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#example-ways-to-refer-to-the-same-file, so they are very likely to be valid paths.

* `c:\temp\test-file.txt` <-> `c:/temp/test-file.txt`
* `\\127.0.0.1\c$\temp\test-file.txt` <-> `//127.0.0.1/c$/temp/test-file.txt`
* `\\LOCALHOST\c$\temp\test-file.txt` <-> `//LOCALHOST/c$/temp/test-file.txt`
* `\\.\c:\temp\test-file.txt` <-> `//./c:/temp/test-file.txt`
* `\\?\c:\temp\test-file.txt` <-> `//?/c:/temp/test-file.txt`
* `\\.\UNC\LOCALHOST\c$\temp\test-file.txt` <-> `//./UNC/LOCALHOST/c$/temp/test-file.txt`

Partial conversion can be incorrect. For example, for `\\?\c:\temp\test-file.txt`, if we convert it to `\\?\c:/temp/test-file.txt` in `Store`, and use the following `try_symlink` implementation:
```rust
        let original = original
            .as_ref()
            .components()
            .fold(std::path::PathBuf::new(), |res, component| {
                res.join(component)
            });
        symlink_file(original, link)
```

an incorrect symink to `\\?\c:/temp/test-file.txt` will be created, because the `components` functions will yield `\\?\c:`, `\`, and `temp/test-file.txt`. For the same reason, the existing `file_util::slash_path` function can't be used.

**Comment by yuja** [comment]
> But we should just do a stirng level character replacement so that the following Windows absolute paths won't get messed up on the same machine

Yes, I meant textual conversion. We might have to fix `slash_path()` to do that. I think we use `path.components()` there just because string manipulation over `OsStr` isn't easy.

**Comment by 06393993** [comment]
> Yes, I meant textual conversion.

Done. Also added test to guard the usage of absolute symlinks on Windows which fails if we use `std::pah::Path::components`(https://doc.rust-lang.org/std/path/struct.Path.html#method.components).

File: lib/src/file_util.rs [hunk 2]
```diff
@@ -288,6 +288,32 @@ impl<R: Read + Unpin> AsyncRead for BlockingAsyncReader<R> {
...
+    if cfg!(windows) {
+        // Use the main separator to reformat the input path to avoid creating a broken
+        // symlink with the incorrect separator "/".
+        //
+        // See https://github.com/jj-vcs/jj/issues/6934 for the relevant bug.
+        PathBuf::from(path.replace("/", "\\"))
+    } else {
+        PathBuf::from(path)
+    }
+}
```
Comment (yuja) [inline lib/src/file_util.rs]: nit: these function names are very specific to the working copy implementation. Can you either
* rename to something similar to `slash_path()` (so we'll eventually merge these functions into one)
* or move them to local_working_copy.rs?

File: lib/src/file_util.rs [hunk 3]
```diff
@@ -288,6 +288,32 @@ impl<R: Read + Unpin> AsyncRead for BlockingAsyncReader<R> {
     }
 }
 
+pub fn symlink_target_convert_to_store(path: &Path) -> Option<String> {
+    let res = if cfg!(windows) {
```
Comment (yuja) [inline lib/src/file_util.rs]: nit: we can use `std::path::MAIN_SEPARATOR` instead of `cfg!(windows)` and `\\`.

File: lib/src/file_util.rs [hunk 4]
```diff
@@ -347,6 +373,23 @@ mod platform {
...
+        debug_assert_ne!(
+            original
+                .as_ref()
+                .as_os_str()
+                .to_str()
+                .map(|path| path.contains("/")),
+            Some(true),
+            "Invalid symlink target: {}.",
+            original.as_ref().display()
+        );
```
Comment (yuja) [inline lib/src/file_util.rs]: I wouldn't add this assertion because it's not wrong to create a dead symlink. It's up to caller whether to interpret symlink target as a disk path.

File: lib/tests/test_local_working_copy.rs [hunk 5]
```diff
@@ -2131,3 +2133,175 @@ fn test_snapshot_max_new_file_size() {
...
+    }
+    let mut test_workspace = TestWorkspace::init();
+    let workspace_root = test_workspace.workspace.workspace_root().to_owned();
+    let target = repo_path("target/link/target.txt");
+    let target_path = target.to_fs_path(&workspace_root).unwrap();
+    std::fs::create_dir_all(target_path.parent().unwrap()).unwrap();
+    std::fs::write(&target_path, "a\n").unwrap();
+    let link = repo_path("link/link.txt");
+    let link_path = link.to_fs_path(&workspace_root).unwrap();
+    let link_contents = file_util::relative_path(link_path.parent().unwrap(), &target_path);
```
Comment (yuja) [inline lib/tests/test_local_working_copy.rs]: nit: use literal string since this test doesn't check if the symlink can be traversed.

File: lib/tests/test_local_working_copy.rs [hunk 6]
```diff
@@ -2131,3 +2133,175 @@ fn test_snapshot_max_new_file_size() {
...
+fn test_snapshot_and_update_valid_symlink(get_link_target: impl FnOnce(&Path, &Path) -> PathBuf) {
+    if !file_util::check_symlink_support().unwrap() {
+        eprintln!("Symlink not supported. Skip the test.");
+    }
+    let mut test_workspace = TestWorkspace::init();
+    let workspace_root = test_workspace.workspace.workspace_root().to_owned();
+    let target = repo_path("target/link/target.txt");
+    let target_path = target.to_fs_path(&workspace_root).unwrap();
+    std::fs::create_dir_all(target_path.parent().unwrap()).unwrap();
+    let file_contents = b"18bHZD165T@C\n";
```
Comment (yuja) [inline lib/tests/test_local_working_copy.rs:2255]: nit: what's this `18bHZD165T@C\n` mean? Can you add comment if the content matters?

File: lib/src/file_util.rs (hunk 3 above)
Comment (06393993) [reply lib/src/file_util.rs]: Changed to use `std::path::MAIN_SEPARATOR_STR`.

However, the old implementation ensures that:

1. on non-Windows platform we don't pay the extra cost of calling `replace` - shouldn't have actual performance impact.
2. on platforms that don't use `/` and `\` as the path separator, and `/` can be a valid file name(I frankly don't know the existence of such platform), we don't perform the replacement, keeping the old behavior. I was asked to also respect platforms outside Unix and Windows in a PR.

Are we Ok with those potential issues?

File: lib/src/file_util.rs (hunk 2 above)
Comment (06393993) [reply lib/src/file_util.rs]: I chose to move to `local_working_copy.rs`, because I don't have extra time investigating what the consequences will be to merge these functions to `slash_path()` and what test I need to add to ensure the correct behavior.

File: lib/src/file_util.rs (hunk 4 above)
Comment (06393993) [reply lib/src/file_util.rs]: Ok. I move this to the caller side then.

While it's not wrong to create a dead symlink(the file can be created after the symlink is created), it's certainly not reasonable to create a symlink to a path with `/` on Windows:

1. symlink to a path with `/` is always a dead symlink. It's not possible that this path becomes valid.
2. In Rust, `Path` uses `/` as the separator unless it's a verbatim path, so given that the type of the argument is `Path`, the intention here is that `/` should be treated as a separator unless it's a verbatim path, otherwise the type of the argument should just be `OsStr`. For example, the following code won't panic on Windows:
    ```rust
    assert_eq!(PathBuf::from(r"C:\a.txt"), PathBuf::from(r"C:/a.txt"));
    ```
4. Even if we allow the creation of such symlink, it won't be preserved after a snapshot and an update in `jj`, and I don't think we want to support such symlink in `jj`. Therefore, it's reasonable to make the assumption clear with the assertion.

WDYT?

File: lib/tests/test_local_working_copy.rs (hunk 5 above)
Comment (06393993) [reply lib/tests/test_local_working_copy.rs]: Done.

The original code was to make sure that it's easy to change the test by only having to modify the least code(in this case the `"target/link/target.txt"` literal, and the `"link/link.txt"` literal), and every other variables will just follow.

File: lib/tests/test_local_working_copy.rs (hunk 6 above)
Comment (06393993) [reply lib/tests/test_local_working_copy.rs:2255]: Added the comment. It's unique contents that it's unlikely that we match accidentally.

File: lib/src/file_util.rs (hunk 3 above)
Comment (yuja) [reply lib/src/file_util.rs]: Oh, I meant something like:
```rust
if MAIN_PATH_SEPARATOR == '/' { // instead of cfg!(..)
    path
} else {
    path.replace('/', MAIN_PATH_SEPARATOR)
}
```
Optimizer should be able to remove unreachable code.

File: lib/src/file_util.rs (hunk 4 above)
Comment (yuja) [reply lib/src/file_util.rs]: A symlink (on Unix at least) can also be used as a file that stores arbitrary data. I know little about Windows, but suppose the semantics of Windows symlinks is similar to the one on Unix, I think it's valid to use this `file_util` function to create a symlink containing slash.

(3) is about how we handle symlinks in working copy.

Comment (06393993) [reply lib/src/file_util.rs]: If we do allow the symlink to store arbitrary bytes, we should change the signature of `try_symlink` to `fn try_symlink(original: &[u8], link: impl AsRef<Path>) -> io::Result<()>`. The type of arguments should be bytes instead of `Path`. While I do feel strong about changing the signature and leave a comment for this assumption, I don't think we need to agree on this issue before this PR could be merged.

Nevertheless, we all agree that, in working copy, we shouldn't create a definitely invalid symlink in test, so I think we are all Ok with leaving the assertion in working copy. Is my understanding correct?

File: lib/src/file_util.rs (hunk 3 above)
Comment (06393993) [reply lib/src/file_util.rs]: Changed to:

```rust
fn symlink_target_convert_to_store(path: &Path) -> Option<Cow<'_, str>> {
    let path = path.to_str()?;
    if std::path::MAIN_SEPARATOR == '/' {
        Some(Cow::Borrowed(path))
    } else {
        // When storing the symlink target on Windows, convert "\" to "/", so that the
        // symlink remains valid on Unix.
        //
        // Note that we don't use std::path to handle the conversion, because it
        // performs poorly with Windows verbatim paths like \\?\Global\C:\file.txt.
        Some(Cow::Owned(path.replace(std::path::MAIN_SEPARATOR_STR, "/")))
    }
}

fn symlink_target_convert_to_disk(path: &str) -> PathBuf {
    let path = if std::path::MAIN_SEPARATOR == '/' {
        Cow::Borrowed(path)
    } else {
        // Use the main separator to reformat the input path to avoid creating a broken
        // symlink with the incorrect separator "/".
        //
        // See https://github.com/jj-vcs/jj/issues/6934 for the relevant bug.
        Cow::Owned(path.replace("/", std::path::MAIN_SEPARATOR_STR))
    };
    PathBuf::from(path.as_ref())
}
```

WDYT?

File: lib/src/file_util.rs (hunk 4 above)
Comment (yuja) [reply lib/src/file_util.rs]: > If we do allow the symlink to store arbitrary bytes,

I think `&Path` or `&OsStr` is good because Windows API wouldn't accept arbitrary bytes, but that's minor detail. (Unix version wouldn't also work if the `original` contained NUL bytes.)

> Nevertheless, we all agree that, in working copy, we shouldn't create a definitely invalid symlink in test, so I think we are all Ok with leaving the assertion in working copy

I don't think it makes sense to assert what `symlink_target_convert_to_disk()` would do immediately after the function call, but I'm not strongly against the assertion, yes.
