### PR TITLE
cli: resolve: do not use .with_new_file_ids() to construct resolved file value

### LINKED ISSUE #6250: `jj resolve` panics when resolving conflicts involving deleted files
## Description

`jj resolve` panics whenever resolving a conflict involving deleted files using an external merge tool (or `:ours` or `:theirs`).

This was found by [saber on Discord][discord] for `:ours` and `:theirs`, but I tested it and the same issue occurs with external merge tools as well.

[discord]: https://discord.com/channels/968932220549103686/968932220549103689/1357751780133306408

## Steps to Reproduce the Problem

1. Create a modify-delete conflict (`2-sided conflict including 1 deletion`).
1. Run `jj resolve` with an external merge tool (or with `:ours` or `:theirs`).
1. Resolve the conflict using the merge tool.

## Expected Behavior

The resolution of the conflict is saved in the working copy. Due to executable bit handling, it may not be possible to resolve the conflict fully, but at least it shouldn't panic. Alternatively, we could just disallow `jj resolve` when one of the sides is a deletion.

## Actual Behavior

A panic like this when the resolution doesn't delete the file (which is normally the case for external merge tools):

```
thread 'main' panicked at lib/src/merge.rs:626:21:
assertion failed: file_id.is_none()
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: jj_lib::merge::Merge<core::option::Option<T>>::with_new_file_ids::{{closure}}
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   5: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   6: <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
   7: core::iter::traits::iterator::Iterator::collect
   8: jj_lib::merge::Merge<core::option::Option<T>>::with_new_file_ids
   9: jj_cli::merge_tools::external::run_mergetool_external_single_file
  10: jj_cli::merge_tools::external::run_mergetool_external
  11: jj_cli::merge_tools::MergeEditor::edit_files
  12: jj_cli::commands::resolve::cmd_resolve
```

Otherwise, a panic like this when the resolution deletes the file (which may be the case for `:ours` or `:theirs`):

```
thread 'main' panicked at lib/src/merge.rs:621:46:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: jj_lib::merge::Merge<core::option::Option<T>>::with_new_file_ids::{{closure}}
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   6: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   7: <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
   8: core::iter::traits::iterator::Iterator::collect
   9: jj_lib::merge::Merge<core::option::Option<T>>::with_new_file_ids
  10: jj_cli::merge_tools::pick_conflict_side
  11: jj_cli::merge_tools::MergeEditor::edit_files
  12: jj_cli::commands::resolve::cmd_resolve
```

## Specifications

- Platform: NixOS
- Version: `jj 0.28.0-29f24ad2d8746e497abb701a99ba00b874f0cea7`

### PR DESCRIPTION
**Pull request by yuja**
Fixes #6250

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
I think we should instead make it an error to try to resolve the content-level conflict before resolving the executable-bit-level conflict. I think we should do the same when merging copy records, i.e. we should not pick one side but instead make the user decide which copy id to keep.

**Comment by martinvonz** [comment]
Yes. I think it's fine to use `.with_new_file_ids()` after checking that there's no conflict in the executable bit (or copy id later). Maybe we can update the API somehow to reduce the risk of bugs like this one but I haven't thought about it.

File: cli/src/merge_tools/external.rs [hunk 1]
```diff
@@ -310,13 +311,19 @@ fn run_mergetool_external_single_file(
...
+
+    let new_tree_value = match new_file_ids.into_resolved() {
+        Ok(new_file_id) => Merge::normal(TreeValue::File {
+            id: new_file_id.unwrap(),
+            executable: conflict
+                .to_executable_merge()
+                .as_ref()
+                .and_then(Merge::resolve_trivial)
+                .copied()
+                .unwrap_or_default(),
```
Comment (martinvonz) [inline cli/src/merge_tools/external.rs]: I think instead of using "not executable" as default here, we should make it an error and tell the user to run `jj file chmod` to choose whether it should be executable.

> Since exec bit has only two states, it can always be trivially resolved.

If a file was added as executable in one commit and added as non-executable in another commit and then you rebase on of them onto the other, it would result in a conflict in the executable bit. This is the kind of conflict I think we should inform the user of and make them resolve with `jj file chmod`. Another example is modify/delete conflicts where the modification changed the executable bit. Sorry that I wasn't clear about this before.

Does that make sense?

Comment (yuja) [reply cli/src/merge_tools/external.rs]: > If a file was added as executable in one commit and added as non-executable in another commit and then you rebase on of them onto the other, it would result in a conflict in the executable bit. This is the kind of conflict I think we should inform the user of and make them resolve with `jj file chmod`. Another example is modify/delete conflicts where the modification changed the executable bit. Sorry that I wasn't clear about this before.

Do you mean we should change `.to_executable_merge()` to be tri-state? An absent file is interpreted as non-executable, so `[exec, absent, no-exec]` can be resolved to `exec`. I assumed the rationale here is that setting exec bit is an explicit operation, so `[(add file, set exec), (), (add file)]` can be merged as `(add file, set exec)`.

Comment (martinvonz) [reply cli/src/merge_tools/external.rs]: > Do you mean we should change `.to_executable_merge()` to be tri-state?

It already is:

```
match value.to_executable_merge().map(|merge| merge.resolve_trivial()) {
  None => // some sides are trees or symlinks
  Some(Some(true)) => // executable
  Some(Some(false)) => // not executable
  Some(None) => // conflict in executable bit
}
```

It's for the last case I think we should tell the user to run `jj file chmod` first. Or, even better, have `jj resolve` ask the user whether they want the file to be executable.

Comment (martinvonz) [reply cli/src/merge_tools/external.rs]: No, you're not misunderstanding. I was just blind. I really thought `to_executable_merge()` returned a `Option<Merge<Option<bool>>>` even after looking at it. I feel like it should return that type but I haven't checked what other consequences that would have.

Comment (yuja) [reply cli/src/merge_tools/external.rs]: Ok, I'll take a look then. Perhaps, `jj resolve` will check if executable can be merged first, and error out immediately.

Comment (yuja) [reply cli/src/merge_tools/external.rs]: Inserted patches to detect `[no-exec, exec, absent]` conflicts.

**Review by martinvonz — APPROVED** [review]
Thank you!
