### PR TITLE
git: reject remotes with forward slashes

### LINKED ISSUE #5731: `jj git fetch` can’t handle remotes with slashes in the name
## Description

As issue title. This is with the (newly‐default) `git.subprocess`; I don’t know whether `git2` is affected or not.

## Steps to Reproduce the Problem

```
yuyuko:/v/f/y/m/T/tmp.nn8ESRTV6z
❭ jj git init --colocate
Initialized repo in "."

yuyuko:/v/f/y/m/T/tmp.nn8ESRTV6z  (empty) (no description set)
❭ jj git remote add test/jj https://github.com/jj-vcs/jj.git

yuyuko:/v/f/y/m/T/tmp.Dba7YWIbpU  (empty) (no description set)
❭ jj git fetch --remote test/jj --bookmark main --debug
2025-02-17T17:02:34.661492Z  INFO jj_cli::cli_util: debug logging enabled
2025-02-17T17:02:34.668605Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main")], remotes: ["test/jj"], all_remotes: false }}:workspace_helper:workspace_helper_with_stats:maybe_snapshot_impl:snapshot_working_copy:base_ignores: globset: glob converted to regex: Glob { glob: "**/._*", re: "(?-u)^(?:/?|.*/)\\._[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('_'), ZeroOrMore]) }
2025-02-17T17:02:34.668633Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main")], remotes: ["test/jj"], all_remotes: false }}:workspace_helper:workspace_helper_with_stats:maybe_snapshot_impl:snapshot_working_copy:base_ignores: globset: glob converted to regex: Glob { glob: "**/.*.kak.*", re: "(?-u)^(?:/?|.*/)\\.[^/]*\\.kak\\.[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('.'), ZeroOrMore, Literal('.'), Literal('k'), Literal('a'), Literal('k'), Literal('.'), ZeroOrMore]) }
2025-02-17T17:02:34.668654Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main")], remotes: ["test/jj"], all_remotes: false }}:workspace_helper:workspace_helper_with_stats:maybe_snapshot_impl:snapshot_working_copy:base_ignores: globset: built glob set; 0 literals, 16 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 2 regexes
2025-02-17T17:02:34.670841Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main")], remotes: ["test/jj"], all_remotes: false }}:fetch{remote_name="test/jj" branch_names=[Exact("main")] depth=None}: jj_lib::git_subprocess: spawning a git subprocess cmd=LC_ALL="C" "git" "--bare" "--git-dir" "/private/var/folders/yd/mh726b5d2vqfyp132jtzq9t80000gn/T/tmp.Dba7YWIbpU/.git" "fetch" "--prune" "--progress" "--" "test/jj" "+refs/heads/main:refs/remotes/test/jj/main"
remote: Enumerating objects: 59317, done.
remote: Total 59317 (delta 97), reused 67 (delta 59), pack-reused 59156 (from 2)
2025-02-17T17:02:40.527972Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main")], remotes: ["test/jj"], all_remotes: false }}:import_refs: jj_lib::git: import_refs
2025-02-17T17:02:40.575574Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main")], remotes: ["test/jj"], all_remotes: false }}:import_refs:import_head_commits: jj_lib::git_backend: import extra metadata entries heads_count=31
tag: v0.10.0 [new]
tag: v0.11.0 [new]
tag: v0.12.0 [new]
tag: v0.13.0 [new]
tag: v0.14.0 [new]
tag: v0.15.0 [new]
tag: v0.15.1 [new]
tag: v0.16.0 [new]
tag: v0.17.0 [new]
tag: v0.17.1 [new]
tag: v0.18.0 [new]
tag: v0.19.0 [new]
tag: v0.20.0 [new]
tag: v0.21.0 [new]
tag: v0.22.0 [new]
tag: v0.23.0 [new]
tag: v0.24.0 [new]
tag: v0.25.0 [new]
tag: v0.26.0 [new]
tag: v0.3.0  [new]
tag: v0.3.1  [new]
tag: v0.3.2  [new]
tag: v0.3.3  [new]
tag: v0.4.0  [new]
tag: v0.5.0  [new]
tag: v0.5.1  [new]
tag: v0.6.0  [new]
tag: v0.6.1  [new]
tag: v0.7.0  [new]
tag: v0.8.0  [new]
tag: v0.9.0  [new]
Warning: No branch matching `main` found on any specified/configured remote
```

## Expected Behavior

With Git:

```
yuyuko:/v/f/y/m/T/tmp.zjfjFoHqKn
❭ git init
Initialized empty Git repository in /private/var/folders/yd/mh726b5d2vqfyp132jtzq9t80000gn/T/tmp.zjfjFoHqKn/.git/

yuyuko:/v/f/y/m/T/tmp.zjfjFoHqKn
❭ git remote add test/jj https://github.com/jj-vcs/jj.git

yuyuko:/v/f/y/m/T/tmp.zjfjFoHqKn
❭ git fetch test/jj main
remote: Enumerating objects: 59316, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 59316 (delta 95), reused 64 (delta 57), pack-reused 59159 (from 2
Receiving objects: 100% (59316/59316), 24.61 MiB | 4.28 MiB/s, done.
Resolving deltas: 100% (48773/48773), done.
From https://github.com/jj-vcs/jj
 * branch              main       -> FETCH_HEAD
 * [new branch]        main       -> test/jj/main

yuyuko:/v/f/y/m/T/tmp.zjfjFoHqKn
❭ git show-ref refs/remotes/test/jj/main
4ed0e1330a7ac8cf6ca3cc70db70ffb78ddb76c4 refs/remotes/test/jj/main
```

## Actual Behavior

As above.

## Specifications

- Platform: macOS 15.3.1
- Version: 539cd75f with https://github.com/jj-vcs/jj/pull/5553 and a couple other changes merged in. (The `.git/config` matches what `git(1)` produces, so I don’t think my PR is relevant here.)

### PR DESCRIPTION
**Pull request by bsdinis**
Although this behaviour is accepted by git, it's a degenerate case. Especially because we implicitely rely on being able to parse out the remote from the refname (i.e., `refs/remotes/<remote>/<branch>`).

Branches can have forward slashes, but if remotes can also have them, parsing the refname becomes ambiguous, and a pain. Especially because it would be totally legal to have a branch "c" on remote "a/b" and a branch "b" on remote "a".

Fixes #5731

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by bsdinis** [comment]
Implements the alternative discussed in #5736

File: cli/src/command_error.rs [hunk 1]
```diff
@@ -537,6 +537,7 @@ jj currently does not support partial clones. To use jj with this repository, tr
             }
             match err {
                 GitFetchError::NoSuchRemote(_) => user_error(err),
+                GitFetchError::RemoteWithSlash(_) => user_error(err),
```
Comment (yuja) [inline cli/src/command_error.rs:540]: nit: maybe we can copy the hint from `GitImportError`.

> "Run `jj git remote rename` to give different name."

File: lib/src/git.rs [hunk 2]
```diff
@@ -1293,6 +1293,8 @@ pub enum GitRemoteManagementError {
     NoSuchRemote(String),
     #[error("Git remote named '{0}' already exists")]
     RemoteAlreadyExists(String),
+    #[error("Git remotes with slashes are invalid: '{0}'")]
```
Comment (yuja) [inline lib/src/git.rs:1296]: nit: "invalid" sounds too strong. Maybe we can say something like "cannot be used", "is not compatible with jj", etc.?

btw, I would remove quotes from `'{0}'` if the parameter is separated by `: `.

**Review by yuja — APPROVED** [review]
Thanks.

File: cli/tests/test_git_clone.rs [hunk 3]
```diff
@@ -761,7 +761,10 @@ fn test_git_clone_with_remote_named_git(subprocess: bool) {
         &["git", "clone", "--remote=git", "source", "dest"],
     );
     insta::allow_duplicates! {
-    insta::assert_snapshot!(stderr, @"Error: Git remote named 'git' is reserved for local Git repository");
+    insta::assert_snapshot!(stderr, @r"
+    Error: Git remote named 'git' is reserved for local Git repository
+    Hint: Run `jj git remote rename` to give a different name.
+    ");
```
Comment (yuja) [inline cli/tests/test_git_clone.rs:767]: Wait, it's mostly wrong to suggest `rename` on creation. The remote `git` doesn't exist.

Revert this patch?

Comment (bsdinis) [reply cli/tests/test_git_clone.rs:767]: you are right. should i revert it or just push a fix?

Comment (bsdinis) [reply cli/tests/test_git_clone.rs:767]: ok, here's the problem:
1. This is an important hint IMO
2. It's the case that it doesn't make much sense on git clone.

My suggestion here is to say `Run jj git remote rename or give the remote a different name.`

Comment (bsdinis) [reply cli/tests/test_git_clone.rs:767]: @yuja #5737
