### PR TITLE
working_copy: existing submodule directory is ok. Fixes submodule history traversion issue.

### LINKED ISSUE #8065: Cannot untrack rediscovered git submodule
## Description

Setup: Git repo with submodules. One moves back in history past the submodule creation and then forward to the future again. The submodule is no longer ignored and the directory shows up as "D submodule". It seems impossible to get out of this state, without commiting to the submodule directory being removed. Trying exclude files and untrack does not help.

## Steps to Reproduce the Problem

```
#!/bin/bash

set -ex

git clone https://github.com/thomasa88/jj-submodule-bug.git
cd jj-submodule-bug
jj git init
jj bookmark track main@origin
jj new 258c2b20
jj st
jj new 3ef6b442
jj st
echo sub >> .git/info/exclude
jj file untrack sub
jj new 3ef6b442
jj st
jj abandon

```

## Expected Behavior

Way to recover from the submodule directory not being ignored any longer.

## Actual Behavior

```
> jj abandon
Abandoned 1 commits:
  kkmqxzlx cf2309a1 (no description set)
Working copy  (@) now at: wszxoryo 59e34e67 (empty) (no description set)
Parent commit (@-)      : lmywpurl 3ef6b442 main | Add simple test runner script
Added 1 files, modified 0 files, removed 0 files
Warning: 1 of those updates were skipped because there were conflicting changes in the working copy.
Hint: Inspect the changes compared to the intended target with `jj diff --from 59e34e679671`.
Discard the conflicting changes with `jj restore --from 59e34e679671`.

> jj st
Working copy changes:
D sub
Working copy  (@) : wszxoryo 1c8d0bb7 (no description set)
Parent commit (@-): lmywpurl 3ef6b442 main | Add simple test runner script
```

Cannot get rid of the change by abandon or `new` to the past.

## Specifications

- Platform: Ubuntu 25.04
- Version: 0.35.0-aa2b76978c4a23cb01c61629a11b1254af3ad0d9

### PR DESCRIPTION
**Pull request by thomasa88**
Replaces https://github.com/jj-vcs/jj/pull/8176

Fixes #8065.

This commit fixes the problem of jj marking a git submodule as a deleted path,
after the user moves (edit/new) to a commit where the submodule did not exist
and then back to a commit where it existed. Failure to remove a
submodule's directory is no longer considered a conflict - if it was not going
to be replaced by another file.

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- N/A I have updated the documentation (`README.md`, `docs/`, `demos/`)
- N/A I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/local_working_copy.rs [hunk 1]
```diff
@@ -1967,21 +1992,45 @@ impl TreeState {
...
             if !present_file_deleted && !can_create_new_file(&disk_path)? {
-                changed_file_states.push((path, FileState::placeholder()));
-                stats.skipped_files += 1;
-                continue;
+                /////// This should only print if files will be found as added --- so check if the submodule path is ignored? How? Can UI print it instead?
+                if matches!(before.as_normal(), Some(TreeValue::GitSubmodule(_))) {
+                    eprintln!(
+                        "Files from the submodule will appear as added. Add the submodule to `.git/info/exclude` and run `jj file untrack` to ignore the directory contents."
+                    );
+                }
```
Comment (thomasa88) [inline lib/src/local_working_copy.rs]: This `if` needs correct logic to check if the path is ignored. Or we just drop the print.

Ideally, I guess some UI code should do the print, but submodule warnings are already printed from the current file and real submodule support is coming to jj in the future.

Comment (thomasa88) [reply lib/src/local_working_copy.rs]: Removed, since jj 0.36 completely ignores directories containing .git.

**Comment by chris13524** [comment]
This fixed the issue for me! I checked out the change with the `D submodule` and reverted that change and it stayed disappeared.

```bash
cargo install --git=https://github.com/thomasa88/jj.git --branch=existing-submod-ok --locked --bin jj jj-cli
```

**Comment by thomasa88** [comment]
I dropped the commit paragraph about jj not automatically ignoring submodules, as it does since v0.36. Rebased on main and fixed conflicts.

**Comment by gaojunran** [comment]
I'm not sure about the internal mechanism of jj, and I'm doing:
```
jj new @ b
```
while b has new submodules comparing to @.

Using your fix I still see a `Removed Git submodule`.

Is this case what you want to fix? What should I do now?

**Comment by joyously** [comment]
Does it address this : [jj is convinced that files in nested repositories are deleted](https://github.com/jj-vcs/jj/issues/8285) ?

**Comment by thomasa88** [comment]
@gaojunran I wanted to fix the case of moving backwards to where a submodule doesn't exist and then moving forward again

From https://github.com/jj-vcs/jj/issues/8065 :
```
#!/bin/bash

set -ex

git clone https://github.com/thomasa88/jj-submodule-bug.git
cd jj-submodule-bug
jj git init
jj bookmark track main@origin
jj new 258c2b20
jj st
jj new 3ef6b442
jj st
echo sub >> .git/info/exclude
jj file untrack sub
jj new 3ef6b442
jj st
jj abandon
```

@joyously I'm not sure and at least not intentionally. My PR was created before v0.36 and the PR discussed in that issue.

---

The cases I have tested for is listed in:
[submodtest.sh](https://github.com/user-attachments/files/24263137/submodtest.sh) 

I now however note that, after correctly rebasing on jj main and not my fork.. :flushed: , my change does no longer fix the problem it intended to fix :( . I will look into it. 

Especially, jj once again sees an existing left-over directory from a submodule as a conflicting path and not the submodule directory:
```
 +++++ GO FORWARD AFTER SUBMODULE +++++
+ /home/thomas/src/jj/target/debug/jj new @-++
Working copy  (@) now at: tvqmtuql 40cd5871 (empty) (no description set)
Parent commit (@-)      : vyrtmlmt 0fa74b58 main | Modify parentfile.txt
Added 2 files, modified 1 files, removed 0 files
Warning: 1 of those updates were skipped because there were conflicting changes in the working copy.
Hint: Inspect the changes compared to the intended target with `jj diff --from 40cd5871e4f5`.
Discard the conflicting changes with `jj restore --from 40cd5871e4f5`.
+ /home/thomas/src/jj/target/debug/jj st
Working copy changes:
D child            <--- ❗This should not happen, as well as the conflict print above.
Working copy  (@) : tvqmtuql 968939ba (no description set)
Parent commit (@-): vyrtmlmt 0fa74b58 main | Modify parentfile.txt
+ git submodule
 e9c5e0431c097bbbab5274c322be7f5415e34e44 child (heads/main)
+ git status
Not currently on any branch.
nothing to commit, working tree clean
+ ls child
childfile.txt
+ set +x
```

**Comment by thomasa88** [comment]
So it turns out that my rebase was not correct. I accidentally dropped half of the implementation during conflict resolution :sweat_smile: . Fixed now!

**Comment by thomasa88** [comment]
@gaojunran I popped in a test at the end of my script, where I edit a commit without the submodule `newmod`  and then merge it with a commit creating `newmod`.

I did not see the string you wrote ('Removed Git submodule') while running it  :shrug: 

I got the exact same prints whether I used jj 0.36.0 or my PR change.

```
+++++ EDIT COMMIT W/O SUBMOD AND MERGE W SUBMOD COMMIT +++++
+ /home/thomas/src/jj/target/debug/jj edit @----
ignoring git submodule at "child"
Working copy  (@) now at: tkskklom f65cff27 main | Modify parentfile.txt
Parent commit (@-)      : ymxxqlxn 59f8bbfb Add child submodule
Added 0 files, modified 2 files, removed 0 files
+ /home/thomas/src/jj/target/debug/jj new @ @+
ignoring git submodule at "newmod"
Working copy  (@) now at: prtqxwpt 0c5c9efa (empty) (no description set)
Parent commit (@-)      : tkskklom f65cff27 main | Modify parentfile.txt
Parent commit (@-)      : srsusxsv 5bddc94f Add newmod submodule
Added 1 files, modified 1 files, removed 0 files
+ /home/thomas/src/jj/target/debug/jj
Hint: Use `jj -h` for a list of available commands.
Run `jj config set --user ui.default-command log` to disable this message.
@    prtqxwpt  2025-12-19 20:17:59 0c5c9efa
├─╮  (empty) (no description set)
│ │ ○  npmszoml  2025-12-19 20:17:58 9e75f7dd
│ │ │  Change child submodule to a file
│ │ ○  ozttzvst 2025-12-19 20:17:57 ceff6e45
│ ├─╯  Remove newmod submodule
│ ○  srsusxsv 2025-12-19 20:17:57 5bddc94f
├─╯  Add newmod submodule
○  tkskklom 2025-12-19 20:17:56 main f65cff27
│  Modify parentfile.txt
○  ymxxqlxn 2025-12-19 20:17:56 59f8bbfb
│  Add child submodule
○  moukswqt 2025-12-19 20:17:56 81426338
│  Add parentfile.txt
◆  zzzzzzzz root() 00000000
+ /home/thomas/src/jj/target/debug/jj st
The working copy has no changes.
Working copy  (@) : prtqxwpt 0c5c9efa (empty) (no description set)
Parent commit (@-): tkskklom f65cff27 main | Modify parentfile.txt
Parent commit (@-): srsusxsv 5bddc94f Add newmod submodule
```

**Comment by thomasa88** [comment]
Rebased on 0.38.

Linux binary (musl linker build for maximum compatibility):
[jj-e553956c-fix-submod](https://www.lysator.liu.se/~axl/jj/jj-e553956c-fix-submod)
[jj-e553956c-fix-submod.sha256](https://www.lysator.liu.se/~axl/jj/jj-e553956c-fix-submod.sha256)

And `cargo install --git=https://github.com/thomasa88/jj.git --branch=existing-submod-ok --locked --bin jj jj-cli` should still work.

**Comment by thomasa88** [comment]
Rebased on 0.39

**Comment by thomasa88** [comment]
Rebased on 0.40, then main.

File: lib/src/local_working_copy.rs [hunk 2]
```diff
@@ -744,6 +744,31 @@ fn remove_old_file(disk_path: &Path) -> Result<bool, CheckoutError> {
...
 
+/// Removes existing submodule directory named `disk_path` if any. Returns
+/// `Ok(true)` if the directory was there and got removed, meaning that new file
+/// can be safely created.
+///
+/// The directory will not be removed if it is not empty, as it could contain
+/// untracked or modified files. This is in line with Git's behavior.
+///
+/// If the existing directory points to ".git" or ".jj", this function returns
+/// an error.
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs]: This would mean that there used to be a submodule called `.git` or `.jj`. If that was the case, it still seems fine to delete an empty directory by that name, or what do you think?

File: lib/src/local_working_copy.rs [hunk 3]
```diff
@@ -2309,6 +2340,11 @@ impl TreeState {
                 }
                 MaterializedTreeValue::GitSubmodule(_) => {
                     eprintln!("ignoring git submodule at {path:?}");
+                    // Git behavior: Create the submodule directory but don't
+                    // populate/overwrite the contents.
+                    if fs::create_dir_all(&disk_path).is_err() {
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs]: nit: `fs::create_dir()` instead of `create_dir_all()`? The parent directory should already exist at this point

File: lib/src/local_working_copy.rs [hunk 4]
```diff
@@ -2309,6 +2340,11 @@ impl TreeState {
...
+                        eprintln!("warning: failed to create submodule directory {path:?}");
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs]: nit: Maybe better to propagate the error?

File: lib/src/local_working_copy.rs [hunk 5]
```diff
@@ -2294,9 +2293,21 @@ impl TreeState {
 
             // If not, create temporary file to test the path validity.
             if !present_file_deleted && !can_create_new_file(&disk_path)? {
-                changed_file_states.push((path, FileState::placeholder()));
-                stats.skipped_files += 1;
-                return Ok(());
+                if disk_path.is_dir() && matches!(after, MaterializedTreeValue::GitSubmodule(_)) {
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs]: nit: Swap the operands so we do the cheap in-memory check on `after` before the more expensive system call for `is_dir()`

File: lib/src/local_working_copy.rs [hunk 6]
```diff
@@ -2294,9 +2293,21 @@ impl TreeState {
...
+                    // Failing to materalize submodule, over a directory which
+                    // is presumably the submodule before it was added in a
+                    // commit, is ok.
+                } else if matches!(before.as_normal(), Some(TreeValue::GitSubmodule(_)))
+                    && after.is_absent()
+                {
+                    // Failing to delete un-tracked submodule directory is ok,
+                    // as the, possibly untracked, contents would otherwise be
+                    // lost.
```
Comment (martinvonz) [inline lib/src/local_working_copy.rs]: It wasn't obvious to me that falling through in these two cases was right, but it does seem to be. We want to delete parent directories if there was no submodule directory here, for example. (No action requested.)

File: lib/src/local_working_copy.rs (hunk 2 above)
Comment (thomasa88) [reply lib/src/local_working_copy.rs]: That's true! Check for reserved directories removed (and the function comment updated).

File: lib/src/local_working_copy.rs (hunk 3 above)
Comment (thomasa88) [reply lib/src/local_working_copy.rs]: Sneakily, the target directory might also already exist and `create_dir_all()` will ignore that it does, not leading to "failed to create submodule directory" being printed. That is, if the directory already exists, we don't warn about failing to create it.

This very much relates to the fall-through conversation in https://github.com/jj-vcs/jj/pull/8225/changes#r3068634734 .

File: lib/src/local_working_copy.rs (hunk 4 above)
Comment (thomasa88) [reply lib/src/local_working_copy.rs]: It does not change any state that jj cares about, so I think I'm inclined to let an error like this slip and let the user change to another commit even though an empty directory could not be created.

File: lib/src/local_working_copy.rs (hunk 5 above)
Comment (thomasa88) [reply lib/src/local_working_copy.rs]: Done!

File: lib/src/local_working_copy.rs (hunk 6 above)
Comment (thomasa88) [reply lib/src/local_working_copy.rs]: I had to get this fully into context again to understand my reasoning.

I think that the case you mention is valid if `present_file_deleted = false` due to the directory not existing at all and a new test file (`can_create_new_file()`) cannot be created in its place ((Closest) parent directory not existing, or possibly hitting max path depth or the parent being an r/o directory).

The cases I mainly wanted to hit:

1. I want to hit `let file_state = match ...... FileState::for_gitsubmodule()` and `changed_file_states.push((path, file_state));` at the end of the lambda. I just saw that this is only relevant for a submodule coming into existence.

2. Also, for a submodule directory coming into existence, I want to hit `eprintln!("ignoring git submodule at {path:?}");` (about line 2349), to get info to the user.

I tried to improve the comments now. Also, I dropped the use of the word "ok", as it kept leading my thougths to `return Ok()`.

File: lib/src/local_working_copy.rs (hunk 3 above)
Comment (thomasa88) [reply lib/src/local_working_copy.rs]: I pondered a bit whether to skip the fall-throughs, but especially the parent deletion code did not feel nice to duplicate inside the current fall-through code.

I added a comment to motivate create_dir_all().

Comment (martinvonz) [reply lib/src/local_working_copy.rs]: I see. Could avoid the comment by making the code clearer like this then?

```rust
match fs::create_dir(&disk_path) {
    Ok(()) | Err(err) if err.kind() == ErrorKind::AlreadyExists => {},
    Err(_) => eprintln!("warning: failed to create submodule directory {path:?}"),
}
```

Comment (thomasa88) [reply lib/src/local_working_copy.rs]: Good point. Done! (I had to split out the Ok due to the guard)

**Comment by thomasa88** [comment]
Thanks for the review! I implemented your last suggestion about create_dir/_all() and I also touched up the message of the last commit a bit, seeing it with fresh eyes.

Rebased on main. I will let it putter in my head a bit before doing the merge.
