### PR TITLE
lock: use std File::lock() on Windows

### LINKED ISSUE #8868: git_import_export.lock and working_copy.lock get stuck dozens of times a day
## Description

On Windows, on a repo I cloned with `jj git clone`, even after a reboot / making sure there have not been any other `jj` processess spawned & that all the lock files have been deleted:

`git_import_export.lock` gets stuck:
```
PS C:\src\ $$$ jj parallelize lzyrxsly::urrqxnqk
Error: Failed to take lock for Git import/export
Caused by:
1: Timed out while trying to create lock file: C:\src\.jj\repo\git_import_export.lock
2: The file exists. (os error 80)

PS C:\src\ $$$ del C:\src\.jj\repo\git_import_export.lock

PS C:\src\ $$$ jj parallelize lzyrxsly::urrqxnqk
Error: Failed to take lock for Git import/export
Caused by:
1: Timed out while trying to create lock file: C:\src\.jj\repo\git_import_export.lock
2: The file exists. (os error 80)

```
or `working_copy.lock` gets stuck

```powershell
PS C:\src\ $$$ jj git colocation status
Internal error: Failed to access working copy state
Caused by:
1: Failed to lock working copy
2: Timed out while trying to create lock file: C:\src\.jj\working_copy\working_copy.lock
3: The file exists. (os error 80)
PS C:\src\ $$$ del C:\src\.jj\working_copy\working_copy.lock

PS C:\src\ $$$ jj git colocation status
Workspace is currently colocated with Git.
Last imported/exported Git HEAD: ce0d4518286173169ac64d18bc3be98682d8b8b4
Hint: To disable colocation, run: `jj git colocation disable
```

## Steps to Reproduce the Problem

1. running any `jj` command regularly triggers this for most repos

## Expected Behavior
jj commands works

## Actual Behavior
jj commands regularly error on a lock file 

## Specifications

- Platform: Windows
- Version: 0.38.0
- watchman is disabled

### PR DESCRIPTION
**Pull request by sheremetyev**
Fixes #8868

### CODE REVIEW

**Comment by PhilipMetzger** [comment]
related PR here https://github.com/jj-vcs/jj/pull/8015

**Comment by sheremetyev** [comment]
> related PR here #8015

Thank you @PhilipMetzger - haven't seen it! @judemille could you have a look at this implementation maybe? I think the main difference is that we don't delete lock file to avoid race condition.

File: lib/src/lock/fallback.rs [hunk 1]
```diff
@@ -12,96 +12,63 @@
...
+        self.file
+            .unlock()
+            .inspect_err(|err| tracing::warn!(?err, ?self.path, "Failed to unlock lock file"))
             .ok();
+        // Note: We intentionally don't delete the lock file here. Deleting
+        // would cause a race condition where another process waiting
+        // for the lock could acquire a lock on the deleted file, while
+        // a third process creates a new file with the same path -
+        // breaking mutual exclusion. The unix.rs impl handles this with
+        // an st_nlink check, but that's not portable.
```
Comment (yuja) [inline lib/src/lock/fallback.rs]: Can we somehow delete the lock file in a similar way to unix version? Windows has exclusive file access, so it might be doable.

https://doc.rust-lang.org/stable/std/os/windows/fs/trait.OpenOptionsExt.html#tymethod.share_mode

File: cli/tests/common/test_environment.rs [hunk 2]
```diff
@@ -377,6 +377,11 @@ impl TestWorkDir<'_> {
         let head_entry = heads_dir
             .read_dir()
             .expect("TestWorkDir must point to the workspace root")
+            .filter(|entry| {
+                entry
+                    .as_ref()
+                    .is_ok_and(|e| e.file_name() != std::ffi::OsStr::new("lock"))
+            })
```
Comment (yuja) [inline cli/tests/common/test_environment.rs]: nit: use `filter_ok()`? An error shouldn't be filtered out.

**Comment by Ralith** [comment]
I explored a native Windows API approach in https://github.com/jj-vcs/jj/pull/8881. I found that, while the Windows API seems like it *should* allow for files to be cleaned up automatically, in practice this doesn't seem to work, at least not without dramatically more effort:
- You can't directly wait for a file to become available to be opened exclusively
- You can't delete an open file
- You can mark a file to be deleted on close, but this is not atomic: after the file is closed, there's a period where attempts to create a new file at the same location will fail with "Access denied".

I think the most practical approach is probably the one taken here, accepting the cost of leaving stale lock files around, provided that `File::lock` on windows is at least as well behaved as a raw `LockFileEx` call.

**Comment by yuja** [comment]
Thanks for the experiment. I agree it would be better to not attempt to delete lock files on Windows. One potential problem is that old `jj` command/UI would be blocked by a stale lock file. I don't have a good answer to this problem. Maybe it's okay to just document that as a breaking change?

> * You can mark a file to be deleted on close, but this is not atomic: after the file is closed, there's a period where attempts to create a new file at the same location will fail with "Access denied".

This reminds me of zombie file issue.

https://foss.heptapod.net/mercurial/mercurial-devel/-/blob/7.2/mercurial/win32.py?ref_type=tags#L724

**Comment by sheremetyev** [comment]
@yuja looks like we can delete lock file and avoid race on Windows if we open file without `FILE_SHARE_DELETE` - please see f6f9cf9cc1e8785fc56f8c905555c48031070b3f

**Comment by yuja** [comment]
> @yuja looks like we can delete lock file and avoid race on Windows if we open file without `FILE_SHARE_DELETE` - please see [f6f9cf9](https://github.com/jj-vcs/jj/commit/f6f9cf9cc1e8785fc56f8c905555c48031070b3f)

Shouldn't we delete the file while the file is still open (or the process has exclusive access to the file)? My understanding is that `FILE_FLAG_DELETE_ON_CLOSE` is the flag for that purpose, but it didn't work reliably.

**Comment by sheremetyev** [comment]
> Shouldn't we delete the file while the file is still open (or the process has exclusive access to the file)? My understanding is that `FILE_FLAG_DELETE_ON_CLOSE` is the flag for that purpose, but it didn't work reliably.

With our share_mode (no FILE_SHARE_DELETE), we can't delete while any handle is open - that's the invariant that prevents race conditions - so we close first, and the delete simply fails if another process has since opened the file.

**Comment by yuja** [comment]
> With our share_mode (no FILE_SHARE_DELETE), we can't delete while any handle is open - that's the invariant that prevents race conditions

Hmm, makes sense, thanks.

**Comment by Aziks0** [comment]
Note that, like unix, removing the file while still holding the lock is possible on Windows. So, at this point, wouldn't using `std::fs` instead of `rustix` and using the same implementation for unix OSes and Windows be better? Because the only difference between those two would be the way they check for file existence (`fs::metadata` for unix and something else for Windows?).

**Comment by Ralith** [comment]
> removing the file while still holding the lock is possible on Windows

I don't think this is true at all. The file must be open to be locked, and open files cannot ever be deleted on Windows.

> we close first, and the delete simply fails if another process has since opened the file.

Are you absolutely certain that an explicit delete doesn't have the same weird "Access denied" race with concurrent attempts to create-or-open the file that `FILE_FLAG_DELETE_ON_CLOSE` does?

**Comment by Aziks0** [comment]
> > removing the file while still holding the lock is possible on Windows
> 
> I don't think this is true at all. The file must be open to be locked, and open files cannot ever be deleted on Windows.

I've tried this snippet and it worked:

```rust
use std::fs::{self, OpenOptions};

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/test");

fn main() {
    let mut options = OpenOptions::new();
    options.create(true).truncate(false).write(true);

    let file = options.open(PATH).unwrap();
    file.lock().unwrap();

    fs::remove_file(PATH).unwrap();

    file.unlock().unwrap();
}
```

I've also tried with another binary waiting for the lock, and it gets it when `file.unlock()` is called.

**Comment by sheremetyev** [comment]
> Are you absolutely certain that an explicit delete doesn't have the same weird "Access denied" race with concurrent attempts to create-or-open the file that `FILE_FLAG_DELETE_ON_CLOSE` does?

`FILE_FLAG_DELETE_ON_CLOSE` is different - it [requires](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) all existing handles to have been opened with `FILE_SHARE_DELETE` - which creates the problematic "pending delete" state.

Our DeleteFileW call happens after we've closed the handle. Since all openers use share mode without `FILE_SHARE_DELETE`, DeleteFileW atomically either succeeds (no other handles exist) or fails (another process has the file open). There's no intermediate "pending delete" state that could race with a concurrent open.

FWIW, tested on Windows by running `jj st` and `jj prev` in tight loops concurrently - no lock errors observed.

**Comment by Ralith** [comment]
> I've tried this snippet and it worked:

I think this is marking the file to be deleted on close, not actually deleting it.

> it [requires](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) all existing handles to have been opened with FILE_SHARE_DELETE - which creates the problematic "pending delete" state.

I don't follow. Where does the extra state come from? The file should be "pending delete" in an abstract sense, perhaps different from what you meant, as soon as it's created with that flag, and it *should* remain in that state until no open handles to it remain, at which point it no longer exists.

If it seems to work when we empirically hammer at it, that's probably an improvement over the status quo which is certainly broken in cases people hit often enough, but it'd be nice to be confident we're not just exchanging race conditions.

**Comment by sheremetyev** [comment]
> Note that, like unix, removing the file while still holding the lock is possible on Windows.

@Aziks0 it is possible (Rust opens with `FILE_SHARE_DELETE` by default), but it has the same race as Unix: process B acquires the lock on the deleted file while process C creates a new file at the same path - breaking mutual exclusion. Unix solves this with an `st_nlink == 0` retry loop, but Windows has no documented equivalent. Approach in commit f6f9cf9cc1e8785fc56f8c905555c48031070b3f (excluding FILE_SHARE_DELETE) sidesteps this entirely: deletion is impossible while any handle is open, so there's no stale-file race to detect.

**Comment by sheremetyev** [comment]
> The file should be "pending delete" in an abstract sense [...]

@Ralith by "pending delete" state I mean when a file has been marked for deletion (via DeleteFileW or closing a DELETE_ON_CLOSE handle) while other handles are still open - the file still exists in the directory but new CreateFile calls fail with ERROR_ACCESS_DENIED.

**Comment by Ralith** [comment]
That's not quite what happens -- future `CreateFileW` calls with `OPEN_ALWAYS` will succeed just fine, and per docs should cause it to remain created.

**Comment by sheremetyev** [comment]
> That's not quite what happens -- future `CreateFileW` calls with `OPEN_ALWAYS` will succeed just fine, and per docs should cause it to remain created.

@Ralith can you explain please. Do you see a problem with implementation in f6f9cf9cc1e8785fc56f8c905555c48031070b3f?

**Comment by Ralith** [comment]
No. I think the theory for why it *should* work is sound, and empirically it seems to be the best behaved of everything we've tried so far. I'm not satisfied that we have a good explanation for why `FILE_FLAG_DELETE_ON_CLOSE` shouldn't work just as well, but it seems clear that it doesn't, so it's mainly an academic concern.

**Comment by yuja** [comment]
Since the new implementation depends on Windows behavior of `~FILE_SHARE_DELETE`, I think we'll have to move it to `lock/windows.rs` module. Other than that, the idea sounds good to me.

**Comment by sheremetyev** [comment]
> I think we'll have to move it to `lock/windows.rs` module.

@yuja, I've moved implementation into `lock/windows.rs`

File: lib/src/lock/windows.rs [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+    file: Option<File>,
+}
+
+impl FileLock {
+    pub fn lock(path: PathBuf) -> Result<Self, FileLockError> {
+        tracing::info!("Attempting to lock {path:?}");
+
+        let file = OpenOptions::new()
+            .create(true)
+            .truncate(false)
```
Comment (yuja) [inline lib/src/lock/windows.rs]: nit: can you add inline comment if `.truncate(false)` matters?

File: lib/src/lock/windows.rs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+            path,
+            file: Some(file),
+        })
+    }
+}
+
+impl Drop for FileLock {
+    #[instrument(skip_all)]
+    fn drop(&mut self) {
+        if let Some(file) = &self.file {
```
Comment (yuja) [inline lib/src/lock/windows.rs]: nit: I would do `self.file.take()` here.

**Review by yuja — APPROVED** [review]
Thanks.

File: lib/src/lock/windows.rs (hunk 3 above)
Comment (sheremetyev) [reply lib/src/lock/windows.rs]: it's not required - removed

File: lib/src/lock/windows.rs (hunk 4 above)
Comment (sheremetyev) [reply lib/src/lock/windows.rs]: moved dropping inside `if let`

**Comment by martinvonz** [comment]
@sheremetyev: I haven't followed this PR closely and I don't know much about Windows file locks. What do you think is going on in https://github.com/jj-vcs/jj/actions/runs/22581995532/job/65416352603#step:8:7365?

**Comment by Ralith** [comment]
That looks like exactly the same delete/create race I saw in #8881 :(

I suspect the practical solution is to check for that specific error condition and retry for a while.

**Comment by sheremetyev** [comment]
Yep, it looks like a brief race while `std::fs::remove_file` opens a new handle to delete the file. Looping for a few milliseconds is probably the right fix (rather than bringing `windows-sys` dependency) - I'll open a PR.

**Comment by Ralith** [comment]
To be clear, I found nothing in windows-sys that could help -- I think this is a kernel limitation.
