### PR TITLE
cli: ignore `$PAGER` in environment by default

### LINKED ISSUE #3502: Setting PAGER=less in the environment causes ANSI escape sequences to appear by default
Just tinkering with jj locally for the first time. I set `PAGER=less` in my environment. This seems to override the default pager 'less -FRX' and hence ANSI escape sequences are not rendered properly (since -FRX is not passed).

## Steps to Reproduce the Problem

Run `PAGER=less jj --help` with a clean configuration

## Expected Behavior

Help is rendered either in plain text or with escape sequences processed properly

## Actual Behavior

ANSI escape sequences are shown:
```
$ PAGER=less jj --help
Jujutsu (An experimental VCS)

To get started, see the tutorial at https://github.com/martinvonz/jj/blob/main/docs/tutorial.md.

ESC[1mESC[4mUsage:ESC[0m ESC[1mjjESC[0m [OPTIONS] <COMMAND>
[...]
```

Note that `env -u PAGER jj --help` works as intended.

## Specifications

- Platform: Linux
- Version: 0.16.0

### PR DESCRIPTION
**Pull request by spectral54**
When `$PAGER` is set in the environment, jj uses that instead of the default (`:builtin` on Windows, `less -FRX` everywhere else). Commonly, users will have `PAGER=less` in their environment for various reasons, and this is respected by jj. This means that every jj command, even one that only outputs one or two lines, will still invoke a full screen pager. It also means that every jj command which uses escape sequences for color, which is most of them, will be output through a pager that doesn't handle that well, so users see output that looks like this, which isn't very readable:

```
ESC[1mESC[38;5;2m@ESC[0m  ESC[1mESC[38;5;13mspmESC[38;5;8mwzlkq...
```

To fix this issue that new users stumble upon, ignore `$PAGER` from the environment, and always use our per-platform default. Users can override this and select whatever pager they want by setting ui.pager in their jj config.

This seems like the least bad option for resolving #3502. The cases I considered were:

1. User doesn't have `PAGER` set. No change.
2. User has `PAGER=less` in their environment. We'll still run `less`, just with `-FRX`, so this seems fine. This case is surprisingly common.
3. User has `PAGER` set because they prefer another pager. We'll ignore that preference and run `less -FRX`.
4. User has `PAGER` set because `less` isn't available on their platform. This is uncommon except for Windows, where we'll run `:builtin` instead of `less -FRX` by default anyway.

This may cause some users who have intentionally set and configured `PAGER` to be frustrated that we aren't respecting that value, but it's generally not possible to respect that value in all cases _and_ have a consistent and usable experience out of the box for the majority of users.

#### Alternatives considered

1. Disable color and OSC8 hyperlinks if `PAGER` is set, since we can't be sure the pager supports the color codes.
2. Don't paginate by default if `PAGER` is set. This seems counterintuitive, but would at least resolve the problem. Users would assume that the `jj` CLI doesn't support paginating, and either wrap it in a pager themselves (this is a bad outcome) or find `ui.pager` and change the setting.
3. Set `LESS` (iff it's not set already), then invoke `PAGER`. This means that users setting things like `LESS=i` breaks our output as well, and cases where `PAGER` isn't 'less' aren't fixed.

Fixes #3502

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [ ] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/config.rs [hunk 1]
```diff
@@ -670,14 +670,12 @@ fn env_base_layer() -> ConfigLayer {
...
     }
-    if let Ok(value) = env::var("PAGER") {
-        layer.set_value("ui.pager", value).unwrap();
-    }
     if let Ok(value) = env::var("VISUAL") {
         layer.set_value("ui.editor", value).unwrap();
     } else if let Ok(value) = env::var("EDITOR") {
         layer.set_value("ui.editor", value).unwrap();
     }
+    // [#3502] Intentionally NOT respecting $PAGER here.
```
Comment (martinvonz) [inline cli/src/config.rs]: Need to update at least config.md

File: CHANGELOG.md [hunk 2]
```diff
@@ -19,6 +19,9 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
   - `core.watchman.register_snapshot_trigger`
   - `diff.format`
 
+* `jj` now ignores `$PAGER` set in the environment. To override the default
+  pager, set this via the `ui.pager` config instead.
```
Comment (martinvonz) [inline CHANGELOG.md]: Do you think it's useful to suggest running `jj config set --user ui.pager "$PAGER"` here for users who have the variable set?

File: cli/src/config.rs [hunk 3]
```diff
@@ -670,14 +670,12 @@ fn env_base_layer() -> ConfigLayer {
         // should override $NO_COLOR." https://no-color.org/
         layer.set_value("ui.color", "never").unwrap();
     }
-    if let Ok(value) = env::var("PAGER") {
-        layer.set_value("ui.pager", value).unwrap();
-    }
```
Comment (PhilipMetzger) [inline cli/src/config.rs:678]: nit: I think we can sensibly deprecate this in 3 releases, so currently adding a warning here may be the option before straight up removing it. I'm up making the removal processes shorter if you deem this to hard for Google.

File: cli/src/config.rs (hunk 1 above)
Comment (PhilipMetzger) [inline cli/src/config.rs]: nit: Move the comment to the place where you removed the code and explain the decision a bit more.

Comment (spectral54) [reply cli/src/config.rs]: Updated config.md.

File: CHANGELOG.md (hunk 2 above)
Comment (spectral54) [reply CHANGELOG.md]: I think here we can (I'd be wary about doing this in a deprecation warning because it'll likely be run blindly and perpetuate problems). We could also theoretically suggest something like:

```
jj config set --user ui.pager '["sh", "-c", "$PAGER"]'
```

to make `jj` respect the `$PAGER` value as it is in the environment when executing `jj` (instead of locking it in). I'm really reluctant to suggeset this because it relies on `sh` and I really don't think this is going to come up often at all :)

File: cli/src/config.rs (hunk 3 above)
Comment (spectral54) [reply cli/src/config.rs:678]: Is there a reason we need a deprecation process and multiple releases? I consider the current behavior to be a bug. The only ones who would benefit from a deprecation warning would be those that intentionally set `$PAGER` to some non-`less` value. I don't have any actual metrics, but this is likely relatively small (vanishingly small amongst the general population, but only 'relatively' small amongst early jj adopters, I'm assuming).

Contrast with the number of users broken by this bug, whose first experience with `jj` is that it's completely unusable and they start off with a very negative experience. We can override this at Google and never show the deprecation warning at all, so there's no pressure to shorten this time period from us. But as `jj` usage is growing outside of Google, I think we should have the out-of-the-box experience be the best it can be, even if it means a sudden change in behavior (a slight regression) for a small subset of current users.

(Also, I'm just not sure how to even implement the deprecation warning: we can't check here because we don't know what the value of `ui.pager` is going to be from the user's config; we can't check that `$PAGER` is set when _using_ `ui.pager`, because if users follow the advice to preserve `$PAGER`, they'll set `ui.pager` to be `$PAGER`... what we'd need is a check when loading the user configs that `ui.pager` ISN'T set in that config layer but IS set in `$PAGER`; I don't know if we have anything like that kind of logic already)

File: cli/src/config.rs (hunk 1 above)
Comment (spectral54) [reply cli/src/config.rs]: Elaborated a little bit and converted `[#3502]` to a link to the issue. I intentionally put it at the bottom because if someone is going to come and try to re-add `$PAGER` handling, they're most likely to put it at the bottom of the function, so it's more likely to be seen here.

Let me know if you disagree, I don't mind moving it back to the original location, it's where I had it originally.

**Comment by ilyagr** [comment]
I have mixed feelings about this (might go into more details later about various use-cases; I'm not sure how common they are or even a good idea), but it seems worth trying just to see if it makes people happier or angrier and from the general principle I like of trying to make more people's first impression of `jj` better.

One suggestion I have is to create a new `:envpager` "pager", in addition to `:builtin`, that uses the old logic and `$PAGER`. Then, it'd be easier for people to restore the old behavior (also for us to change our mind about what the default should be on different systems, if needed).

I'm not sure that this is absolutely necessary, but it seems like an easy addition with upsides.

**Update:** There are two main motivations I have for suggesting this:

- It provides a form answer to anyone unhappy about this change: "set `pager=":envpager"` in your config".
- I might want to in fact do that. In brief, my use-case is that I set up `less -FR` as my pager. I then have

```
# In ~/.config/lesskey
^q toggle-option -redraw-screen\nq
```

Now, I can quit `less` with `q` to clear the screen, or I can quit `less` with `^q` to keep the output of `less` on the screen. I keep meaning to write up this trick.

Of course, I could configure `jj` with `less -FR`, but I want this to work the same for `git`, `jj`, `delta`, `bat`, ...

**Comment by spectral54** [comment]
> One suggestion I have is to create a new `:envpager` "pager", in addition to `:builtin`, that uses the old logic and `$PAGER`. Then, it'd be easier for people to restore the old behavior (also for us to change our mind about what the default should be on different systems, if needed).

Good idea. Done!

File: CHANGELOG.md [hunk 4]
```diff
@@ -88,6 +93,9 @@ edits the change twice in some cases.
 * Fixed parsing of `files(expr)` revset expression including parentheses.
   [#7747](https://github.com/jj-vcs/jj/issues/7747)
 
+* Fixed `PAGER` being set in the environment causing ANSI escape sequences to be
+  displayed to the terminal. [#3502](https://github.com/jj-vcs/jj/issues/3502)
```
Comment (ilyagr) [inline CHANGELOG.md]: I'm not sure I'd call this a bugfix. Perhaps delete this and add "See \[#3502\](...) for motivation" to the item in "Breaking Changes"?

File: cli/src/config.rs [hunk 5]
```diff
@@ -670,14 +670,14 @@ fn env_base_layer() -> ConfigLayer {
         // should override $NO_COLOR." https://no-color.org/
```
Comment (ilyagr) [inline cli/src/config.rs:673]: Re commit message: a reminder for later to sync it up with what the commit actually does before merging. Right now, it doesn't mention `:envpager` AFAICT.

File: cli/src/config.rs [hunk 6]
```diff
@@ -670,14 +670,14 @@ fn env_base_layer() -> ConfigLayer {
...
-    if let Ok(value) = env::var("PAGER") {
-        layer.set_value("ui.pager", value).unwrap();
-    }
     if let Ok(value) = env::var("VISUAL") {
         layer.set_value("ui.editor", value).unwrap();
     } else if let Ok(value) = env::var("EDITOR") {
         layer.set_value("ui.editor", value).unwrap();
     }
+    // Intentionally NOT respecting $PAGER here as it's very likely to create a bad
+    // out-of-the-box experience for users, see http://github.com/jj-vcs/jj/issues/3502.
```
Comment (ilyagr) [inline cli/src/config.rs:682]: I'd perhaps edit this to "... as it often creates a bad out-of-the-box experience for new users, ..."

File: docs/config.md [hunk 7]
```diff
@@ -711,28 +711,29 @@ show-cryptographic-signatures = true
...
-a `$`):
+By default, jj will paginate output that would scroll off the screen. It does
+this by passing output through `less -FRX` on most platforms (on Windows it uses
+[the pager](#builtin-pager) that is built-in to jj). It is possible the default
+will change to `:builtin` for all platforms in the future.
 
-`ui.pager` > `$PAGER`
+Which pager to use can be customized by setting `ui.pager`. When choosing a
+pager, ensure that it either supports color codes or that you disable color (see
+[Colorizing output](#colorizing-output)).
```
Comment (ilyagr) [inline docs/config.md:721]: I'd add something like: "Unlike some other Unix tools, `jj` does not respect the `PAGER` environment variable by default. You can set `ui.pager` to `:envpager` to make `jj` respect `PAGER`.

File: cli/src/ui.rs [hunk 8]
```diff
@@ -329,10 +330,10 @@ impl PagerConfig {
             return Ok(Self::Disabled);
         };
         let args: CommandNameAndArgs = config.get("ui.pager")?;
-        if args.as_str() == Some(BUILTIN_PAGER_NAME) {
-            Ok(Self::Builtin(config.get("ui.streampager")?))
-        } else {
-            Ok(Self::External(args))
+        match (args.as_str(), env::var("PAGER")) {
+            (Some(BUILTIN_PAGER_NAME), _) => Ok(Self::Builtin(config.get("ui.streampager")?)),
+            (Some(ENV_PAGER_NAME), Ok(pager_env)) => Ok(Self::External((&pager_env).into())),
```
Comment (ilyagr) [inline cli/src/ui.rs]: It's probably better to error if `env::var("PAGER")` is not OK, or is there some reason not to?

This might require finagling with the error types a little bit, you could change the return type to `CommandError` or perhaps abuse ``ConfigGetError::NotFound("`PAGER` environment variable")``. The former is probably nicer.

File: cli/src/ui.rs [hunk 9]
```diff
@@ -46,6 +46,7 @@ use crate::formatter::LabeledScope;
 use crate::formatter::PlainTextFormatter;
 
 const BUILTIN_PAGER_NAME: &str = ":builtin";
+const ENV_PAGER_NAME: &str = ":envpager";
```
Comment (yuja) [inline cli/src/ui.rs]: nit: just ":env"?

File: docs/config.md [hunk 10]
```diff
@@ -711,28 +711,29 @@ show-cryptographic-signatures = true
 
 ## Pager
 
-The default pager is can be set via `ui.pager` or the `PAGER` environment
-variable. The priority is as follows (environment variables are marked with
-a `$`):
+By default, jj will paginate output that would scroll off the screen. It does
+this by passing output through `less -FRX` on most platforms (on Windows it uses
+[the pager](#builtin-pager) that is built-in to jj). It is possible the default
+will change to `:builtin` for all platforms in the future.
```
Comment (ilyagr) [inline docs/config.md]: I'd delete the last sentence, since you haven't introduced the `ui.pager` variable yet, and this PR takes us in a different direction anyway. If we decide to, we can change the default to `:builtin` later either way.

File: cli/src/ui.rs (hunk 8 above)
Comment (yuja) [inline cli/src/ui.rs]: ":envpager" should be an error if `$PAGER` isn't set.

BTW, I personally don't think we need `:envpager`. Since the user has to configure it manually, they can just set their pager command as usual. I don't think it's common to temporarily override `$PAGER`. If they do, they can use `sh -c $PAGER` or something.

File: cli/src/config.rs (hunk 5 above)
Comment (ilyagr) [reply cli/src/config.rs:673]: Ah, I think I didn't read it carefully enough. Perhaps swap the first and the second paragraph of the commit message? Or just keep it as is if you prefer, it's fine.

File: cli/src/ui.rs (hunk 9 above)
Comment (ilyagr) [reply cli/src/ui.rs]: I wondered about this, and thought that `:envpager` might be nice since it answers the question of "what part of the environment is relevant here?". Environment could also refer to a dotfile, or something weird.

But my opinion is not very strong, and `:env` is undeniably shorter. The downside of `envpager` is that it can be confused with `pagerenv` or `env-pager`. We can go with whatever you and Kyle agree on.

File: cli/src/ui.rs (hunk 8 above)
Comment (ilyagr) [reply cli/src/ui.rs]: The `sh` command is a good point. Apparently, this was already discussed in https://github.com/jj-vcs/jj/pull/7821#discussion_r2456005797.

I would still prefer having `:env`/`:envpager`. That `sh` command can take some quoting if you want to put it into a `jj config set` command and can be messed up by putting extra quotes around `$PAGER`, both mistakes resulting in subtle problems that may not be immediately apparent. It doesn't work on Windows.

But I'm not entirely sure; if your or others' preference against it is strong enough, we'll probably manage without `:env` as well.

Comment (yuja) [reply cli/src/ui.rs]: My feeling is that many users who previously relied on `$PAGER` would be happy with the new default or configuring `ui.pager` to their preferred pager. Maybe we can add `:envpager` later if there are complaints about that?

BTW, I don't have concern about platform compatibility of `sh -c` because `$PAGER` is very Unix thing.

Comment (spectral54) [reply cli/src/ui.rs]: I've removed :env because my initial implementation was bad, and everyone missed that it was bad, so it seemed too subtle to have for now. I would not be at all opposed to a separate PR adding it, however.

File: docs/config.md (hunk 7 above)
Comment (spectral54) [reply docs/config.md:721]: I skipped this because I removed :env for now. Let me know if you'd like me to still include a sentence like this.

File: cli/src/ui.rs (hunk 8 above)
Comment (spectral54) [reply cli/src/ui.rs]: I was thinking that some users may share their jj configuration across machines but not their `PAGER` configuration (for whatever reason: maybe it's not available on that particular machine or platform).

What I wrote here clearly doesn't work, however ;) If we wanted to support this fallback, we'd need to somehow get at the lower layers of config and it doesn't look like StackedConfig makes that trivial. I've removed :env for now, it can be added in a separate PR.

Comment (ilyagr) [reply cli/src/ui.rs]: >  because my initial implementation was bad, and everyone missed that it was bad,

Do you mean https://github.com/jj-vcs/jj/pull/7821#discussion_r2471194139?

Yuya clearly prefers the lack of `:env`, I can live with it. Guess we'll see how people respond.

File: docs/config.md (hunk 7 above)
Comment (ilyagr) [reply docs/config.md:721]: It might be worth documenting Yuya and Martin's `sh -c $PAGER` workaround, but that's a bit subtle because of quoting. I'll leave that up to you and Yuya.

Comment (yuja) [reply docs/config.md:721]: FWIW, if we document that, `"sh", "-c", "exec $PAGER"` might be better.

File: cli/src/config.rs (hunk 3 above)
Comment (PhilipMetzger) [reply cli/src/config.rs:678]: > Is there a reason we need a deprecation process and multiple releases?

Because it's user-friendly and a good way to remove things. 

> I consider the current behavior to be a bug. The only ones who would benefit from a deprecation warning would be those that intentionally set `$PAGER` to some non-`less` value. I don't have any actual metrics, but this is likely relatively small (vanishingly small amongst the general population, but only 'relatively' small amongst early jj adopters, I'm assuming).

I mean it's working as intended (its just a wrong default for most people). We also have done a similar thing with moving away from `Application Support/config` for our Mac users (https://github.com/jj-vcs/jj/pull/6300).  

> (Also, I'm just not sure how to even implement the deprecation warning: we can't check here because we don't know what the value of `ui.pager` is going to be from the user's config; we can't check that `$PAGER` is set when _using_ `ui.pager`, because if users follow the advice to preserve `$PAGER`, they'll set `ui.pager` to be `$PAGER`... what we'd need is a check when loading the user configs that `ui.pager` ISN'T set in that config layer but IS set in `$PAGER`; I don't know if we have anything like that kind of logic already)

I mean you can emit a warning that `$PAGER` was read and that it will be ignored in the future.

Comment (spectral54) [reply cli/src/config.rs:678]: > Because it's user-friendly and a good way to remove things.

I generally agree with that sentiment. But not here. I struggle to define the current behavior as anything besides a bug, and taking three releases to fix a bug that makes new users unable to use your software doesn't make sense to me.

> I mean you can emit a warning that $PAGER was read and that it will be ignored in the future.

I don't think that works, because the only solution to make the nag go away would be to unset `$PAGER`. Setting `ui.pager` wouldn't make the nag go away because we can't read the user's `ui.pager` setting here.

Comment (PhilipMetzger) [reply cli/src/config.rs:678]: Sorry, for not getting back to you. It should be fine although a warning would've been nice.

**Comment by spectral54** [comment]
I'm not super familiar with GitHub etiquette, so my apologies if I'm about to do the wrong thing (and if so, feel free to back it out), but I'm going to click the merge button some time tomorrow. Thanks for the review!

File: CHANGELOG.md [hunk 11]
```diff
@@ -19,6 +19,11 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
   - `core.watchman.register_snapshot_trigger`
   - `diff.format`
 
+* `jj` now ignores `$PAGER` set in the environment and uses `less -FRX` on most
+  platforms (`:builtin` on Windows). See [the docs](docs/config.md#pager) for
+  more information, and [#3502](https://github.com/jj-vcs/jj/issues/3502) for
+  motivation.
```
Comment (yuja) [inline CHANGELOG.md]: nit: since new version was released, you'll need to rebase this and move the changelog entry before merging.

Comment (spectral54) [reply CHANGELOG.md]: Thanks for the reminder! I would have forgotten about that. Done.
