### PR TITLE
git: always store the empty tree

### LINKED ISSUE #8480: JJ does not persist the empty tree object
## Description

When a commit has an empty tree (i.e. `tree 4b825dc6...`), jj does not persist the tree object. This breaks gitoxide pack file generation.

## Steps to Reproduce the Problem
Install `jj-cli` and `gitoxide` with Cargo.

In an empty directory:
```sh
jj git init
jj bookmark create main
gix free pack create main -o . -se tree-traversal
```

## Expected Behavior
A pack file is created in the current directory.

## Actual Behavior
An error is shown, indicating that gix cannot find the tree for the current commit.

```
Error: An object with id 4b825dc642cb6eb9a060e54bf8d69288fbee4904 could not be found
```

This might be a bug in gix, but it works fine when I use the git cli instead of jj:
```sh
git init
git commit --allow-empty -m empty
gix free pack create main -o . -se tree-traversal
```

## Specifications

- Platform: macOS 15.7.2 aarch64
- Version: jj 0.36.0-70fd8f7697fbc20a9329a6e2f790ef86a8e284d1, gix 0.49.0

### PR DESCRIPTION
**Pull request by Benjamin-Davies**
Fixes #8480

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [x] ~~I have updated the documentation (`README.md`, `docs/`, `demos/`)~~
- [x] ~~I have updated the config schema (`cli/src/config-schema.json`)~~
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/git_backend.rs [hunk 1]
```diff
@@ -1295,6 +1295,18 @@ impl Backend for GitBackend {
             ));
         }
 
+        if git_tree_id.is_empty_tree() {
```
Comment (scott2000) [inline lib/src/git_backend.rs]: We might want to check whether any of `tree_ids` is the empty tree, since it's possible that a conflicted tree could have an empty tree on one side only. I'm not sure how important that case is though since it should be pretty rare.

File: lib/src/git_backend.rs [hunk 2]
```diff
@@ -1295,6 +1295,18 @@ impl Backend for GitBackend {
             ));
         }
 
+        if tree_ids.iter().any(|id| id == &self.empty_tree_id) {
```
Comment (yuja) [inline lib/src/git_backend.rs:1298]: nit: can you add inline comment why we have to write an empty tree? It's nice to have a few examples that would otherwise fail. (e.g. object lookup through `gix` doesn't usually fail, but maybe a certain operation would fail? `git fsck` warns about missing tree?)

File: lib/src/git_backend.rs [hunk 3]
```diff
@@ -1295,6 +1295,18 @@ impl Backend for GitBackend {
...
+            let tree = gix::objs::Tree { entries: vec![] };
```
Comment (yuja) [inline lib/src/git_backend.rs]: nit: `gix::objs::Tree::empty()`

**Review by yuja — APPROVED** [review]

**Comment by PhilipMetzger** [comment]
nit: moves the fixes line into the commit description
