### PR TITLE
eol: fix binary check on files with a CRLF at the probe boundary

### LINKED ISSUE #8404: EOL conversion not performed on specific text files
## Description

Some autogenerated files are committed with CRLF endings, despite being text and `eol-conversion = input`

Problem file (in zip): [cmsis_armclang.zip](https://github.com/user-attachments/files/24329685/cmsis_armclang.zip)

## Steps to Reproduce the Problem

1. Commit the file in the attached zip with LF endings
2. Modify it to have CRLF endings
3. Commit it again. The file in the backend will be changed to CRLF

## Expected Behavior

Step 3 should generate no diff.

## Actual Behavior

Step 3 generates a diff on every line.

## Specifications

- Platform: Windows
- Version: 0.36.0-70fd8f7697fbc20a9329a6e2f790ef86a8e284d1

### PR DESCRIPTION
**Pull request by Eekle**
Fix #8404

`eol.rs` checks the first 8K bytes of a file to see if it's binary or not. If there is a null byte found, or a carriage return not followed by a newline, it's considered binary.

This breaks in cases where the 8K boundary is the middle of a `CRLF` pair, as the carriage return isn't followed by a newline (in the truncated data).

This change reads one extra byte only in the case where the last of the leading 8K is a carriage return.

# Checklist

If applicable:

- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: lib/src/eol.rs [hunk 1]
```diff
@@ -67,6 +67,11 @@ impl TargetEolStrategy {
                     .take(Self::PROBE_LIMIT)
                     .read_to_end(&mut peek)
                     .await?;
+                if peek.last() == Some(&b'\r') {
+                    // The peek limit may have split a CRLF sequence.
+                    // Try and read one more byte.
+                    (&mut contents).take(1).read_to_end(&mut peek).await?;
```
Comment (yuja) [inline lib/src/eol.rs]: Maybe we can do `stip_suffix()` if the length matches `PROBE_LIMIT`? I think it's slightly better than doing extra small read.

**Review by yuja — COMMENTED** [review]
Good catch.

Can you copy the PR description to commit message?

File: lib/src/eol.rs (hunk 1 above)
Comment (Eekle) [reply lib/src/eol.rs]: In the case where a file is _exactly_ 8K bytes and ends in a carriage return, the current way would give the correct result but stripping the suffix would not.

Comment (Eekle) [reply lib/src/eol.rs]: But I have changed it to only do the extra read in the case where the last character is `\r`, and `PROBE_LIMIT` characters were read. That saves the read call in the case of a short file ending in`\r`

Comment (yuja) [reply lib/src/eol.rs]: > In the case where a file is exactly 8K bytes and ends in a carriage return, the current way would give the correct result but stripping the suffix would not.

Does that really matter? If there are 8kB contents to test line ending, it should be okay to ignore the last line.

Comment (Eekle) [reply lib/src/eol.rs]: I doubt it matters. To me it's a bit more rigorous to say we will always correctly determine the binary-ness of files equal to or less than the probe limit.

But I defer to you. If you think saving the read call is more critical then I will change it.

Comment (martinvonz) [reply lib/src/eol.rs]: I don't care much whether we detect that particular case, but it seems better to always attempt to read 8001 bytes to avoid the additional read (which I assume might involve an additional system call).

Comment (yuja) [reply lib/src/eol.rs]: We can of course do `take(PROBE_LIMIT + 1).read_to_end()` and ignore the last byte. I don't care if `PROBE_LIMIT` were `8191` bytes (or even `8000` bytes), though.

Comment (Eekle) [reply lib/src/eol.rs]: Changed to do a single `PROBE_LIMIT` length read, and cut off a trailing suffix if it's a carriage return.

Documented `PROBE_LIMIT` to be clear about what is guaranteed at the boundary.

File: lib/src/eol.rs [hunk 2]
```diff
@@ -67,7 +71,18 @@ impl TargetEolStrategy {
...
+
+                // The probe limit may have sliced a CRLF sequence, which would cause
+                // misclassification as binary.
+                let slice_to_check = {
+                    if peek.get(Self::PROBE_LIMIT as usize - 1) == Some(&b'\r') {
+                        &peek[0..Self::PROBE_LIMIT as usize - 1]
+                    } else {
+                        &peek
+                    }
+                };
```
Comment (yuja) [inline lib/src/eol.rs]: nit: can you extract this to helper function (or move to `is_binary()`)?

File: lib/src/eol.rs [hunk 3]
```diff
@@ -255,6 +281,19 @@ mod tests {
         );
     }
 
+    const fn test_probe_limit_input_crlf() -> [u8; TargetEolStrategy::PROBE_LIMIT as usize + 1] {
+        let mut arr = [b'a'; TargetEolStrategy::PROBE_LIMIT as usize + 1];
```
Comment (yuja) [inline lib/src/eol.rs:279]: I think the test input should include some CRLFs within the probe range.

**Review by yuja — APPROVED** [review]
Thanks.

File: lib/src/eol.rs (hunk 2 above)
Comment (Eekle) [reply lib/src/eol.rs]: Done.

I didn't extract it to `is_binary` because that function doesn't know anything about the `PROBE_LIMIT`. But I factored out the general peek-and-decide block from both convert_eol funcs.

File: lib/src/eol.rs (hunk 3 above)
Comment (Eekle) [reply lib/src/eol.rs:279]: Added

File: lib/src/eol.rs [hunk 4]
```diff
@@ -52,9 +52,39 @@ impl TargetEolStrategy {
...
+
+        // The probe limit may have sliced a CRLF sequence, which would cause
+        // misclassification as binary.
+        let slice_to_check = {
+            if peek.get(Self::PROBE_LIMIT as usize - 1) == Some(&b'\r') {
+                &peek[0..Self::PROBE_LIMIT as usize - 1]
+            } else {
+                peek
+            }
+        };
```
Comment (yuja) [inline lib/src/eol.rs:81]: nit: remove redundant outer `{ .. }` block
