### PR TITLE
config: Implement secure-config design doc.

### LINKED ISSUE #1595: In-repo configs are a potential security risk
## Description

Git has longstanding security issues with .git/config being inside the repo. The config settings that specify which executable to run are extremely prone to abuse. Notably, core.fsmonitor is invoked on git status, which is run if the user has configured some sort of Git prompt and `cd`-s into a repo, but even more innocuous-looking settings like `core.pager` are quite prone to this sort of abuse. This is pretty scary because to perform an attack, the attacker only needs to convince the victim to unzip a repo with a poisoned config file and wait for them to run either `cd` or `git log`.

jj already has similar settings (`ui.merge-editor`, `ui.pager`, etc), so we're also prone to such attacks. if possible, i'd like to find a safer way around in-repo config before it becomes unsolvable. the problem of config in the repo has become pretty much unsolvable for Git already. recent security fixes in this area have focused on which repos to trust (e.g. `safe.directory` says that repos owned by another user are untrustworthy). see another discussion from a prominent Git contributor about limiting which executables Git can run  https://lore.kernel.org/git/6af83767-576b-75c4-c778-0284344a8fe7@github.com/ (See "Example Security Boundary Question: Unprotected Config and Executing Code").

Other proposals to fix this issue:

- Safe-listing which config that we will read from the repo config, and everything else will be ignored. This is probably doable at our current scale of config options, but it precludes some desirable features, e.g. configuring a different merge tool for a specialized repo.
- Keeping per-repo config outside of the repo. This could be made `mv`-resistant by associating a UUID with a repo (thanks @Ralith for the idea). This probably requires implementing an import/export workflow for copying repos, but this lets us sanitize possibly unsafe config, so this is a lot safer than relying on `zip`.

### LINKED ISSUE #3303: Implement repo ownership checks
Git has [a couple config variables](https://git-scm.com/docs/git-config#Documentation/git-config.txt-safebareRepository) around repositories that aren't owned by the current user. This speaks to a threat model that we should consider.

> By default, Git will refuse to even parse a Git config of a repository owned by someone else, let alone run its hooks, and this config setting allows users to specify exceptions

The main question is, should we mirror/adopt this behaviour?

### Update

While we might not run githooks, we might still run into the same security consideration as in the CVE linked below. Ergo, this is a prudent feature to add as a security measure

### PR DESCRIPTION
**Pull request by matts1**
See docs/design/secure-config.md for many more details.

Fixes #3303
Fixes #1595

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [X] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [X] I have updated the config schema (`cli/src/config-schema.json`)
- [X] I have added/updated tests to cover my changes

### CODE REVIEW

**Comment by matts1** [comment]
I've added Yuja as a reviewer since he's the one I strictly need approval from, but FYI @martinvonz and @PhilipMetzger in case you'd like to review as well.

**Comment by higgsd** [comment]
Some thoughts on the design doc:
- Missing noun: `The attacker can now see [???] stored in the repository`
- Content - explain more explicitly how the victim's signatures are misused (or if that's just A Bad Thing)
- Does anything problematic happen if the user's .config directory is itself a jj repo?
  - Is there a need to prevent a repo from storing its configs inside itself?
- Perhaps give users a preferred way to copy/restore a config, so they don't have to hand-correlate repos with config-ids
  - Maybe provide `jj config replace [scope] [PATH | --stdin]` to help?
- Perhaps provide a way to list known config-ids and the disposition of their repos/workspaces
  - Its an intermediate step (or alternative) to `jj config gc`, for review and manual cleanup

**Comment by matts1** [comment]
> * Missing noun: `The attacker can now see [???] stored in the repository`
> * Content - explain more explicitly how the victim's signatures are misused (or if that's just A Bad Thing)

This was a remnant of the old proposal. I've renamed it to "config / config signatures"

> * Does anything problematic happen if the user's .config directory is itself a jj repo?

Not really

>   * Is there a need to prevent a repo from storing its configs inside itself?

Yes, this is explained in the design doc in attack vector 1. Other attack vectors just build on top of this.

> * Perhaps give users a preferred way to copy/restore a config, so they don't have to hand-correlate repos with config-ids
>   * Maybe provide `jj config replace [scope] [PATH | --stdin]` to help?

This feature is supposed to be transparent to the user. The user does not have to hand-correlate repos with config IDs. It should happen for them automatically. If you did want to manually do it, it's as simple as writing the config id to .jj/repo-config-id, or just running `jj config edit` and copying the config from there.

> * Perhaps provide a way to list known config-ids and the disposition of their repos/workspaces
>   * Its an intermediate step (or alternative) to `jj config gc`, for review and manual cleanup

If someone wanted to implemented it, I wouldn't stop them, but I already mentioned in the design doc that GC was out of scope of the initial version, but that we might consider later.

File: lib/src/secure_config.rs [hunk 1]
```diff
@@ -0,0 +1,458 @@
...
+            // I considered making this readonly, but that would prevent you from
+            // updating the config with old versions of jj.
+            // In the future, we consider something a little more robust, where as
+            // the non-legacy config changes, we propagate that to the legacy config.
+            // However, it seems a little overkill, considering it only affects windows
+            // users who use multiple versions of jj at once, and only for a year.
+            let mut content = CONTENT_PREFIX.as_bytes().to_vec();
+            content.extend_from_slice(&config);
+            std::fs::write(&legacy_config, content).context(&legacy_config)?;
+        }
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: nit: create a helper for this, this is also missing a deprecation warning with the year long migration timeline.

File: lib/src/secure_config.rs [hunk 2]
```diff
@@ -0,0 +1,458 @@
...
+        )
+    }
+
+    fn generate_config(
+        &self,
+        config_id: &str,
+        content: &[u8],
+        metadata: &ConfigMetadata,
+    ) -> Result<PathBuf, SecureConfigError> {
+        let d = self.config_dir.join(config_id);
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: nit: `d` could be repo_dir since single char variables make for bad readabilty.

File: lib/src/secure_config.rs [hunk 3]
```diff
@@ -0,0 +1,458 @@
...
+
+"###;
+
+/// A mechanism to access config files for a repo securely.
+#[derive(Clone, Debug)]
+pub struct SecureConfig {
+    // We don't use JJRng because that depends on the seed, which comes
+    // from config files, so doing so would be circular.
+    rng: RefCell<ChaCha20Rng>,
+
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: nit: delete spurious newline here

File: lib/src/secure_config.rs [hunk 4]
```diff
@@ -0,0 +1,458 @@
...
+        config_id: &str,
+        content: &[u8],
+        metadata: &ConfigMetadata,
+    ) -> Result<PathBuf, SecureConfigError> {
+        let d = self.config_dir.join(config_id);
+        let config_path = d.join(CONFIG_FILE);
+        std::fs::create_dir_all(&d).context(&d)?;
+        self.update_metadata(&d, metadata)?;
+        if !content.is_empty() {
+            std::fs::write(&config_path, content).context(&config_path)?;
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: nit: import atleast `std` so its just `fs::write(...)` since this code isn't async where it otherwise could lead to a problem.

File: lib/src/secure_config.rs [hunk 5]
```diff
@@ -0,0 +1,458 @@
...
+                match std::fs::read(&metadata_path).context(&metadata_path) {
+                    Ok(buf) => {
+                        let (config_dir, metadata) = self.handle_metadata_path(
+                            config_dir,
+                            ConfigMetadata::decode(buf.as_slice())?,
+                        )?;
+                        (Some(config_dir.join(CONFIG_FILE)), metadata)
+                    }
+                    Err(e) if e.source.kind() == NotFound => {
+                        let (path, metadata) = self.generate_initial_config(s)?;
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: I think the deprecation warning belongs here

**Review by PhilipMetzger — COMMENTED** [review]
minor stuff, I think you also have missed implementing the deprecation warning.

**Comment by higgsd** [comment]
> > * Does anything problematic happen if the user's .config directory is itself a jj repo?
> 
> Not really
> 
> > * Is there a need to prevent a repo from storing its configs inside itself?
>
> Yes, this is explained in the design doc in attack vector 1. Other attack vectors just build on top of this.
> 

Sorry, I meant those as associated bullets.  If the user makes their .config directory a jj repo, all their secure configs will be then stored in that repo.

If a jj repo finds that it contains it's own secure config path, should it complain loudly or behave any differently?

File: lib/src/secure_config.rs (hunk 1 above)
Comment (matts1) [reply lib/src/secure_config.rs]: I don't think we need a deprecation warning here specifically. A warning should only be used to inform the user that they need to do something differently, or there's some gotcha they need to be aware of. Here, it's been automatically migrated for them, so they don't need to do anything differently.

**Comment by matts1** [comment]
> If a jj repo finds that it contains it's own secure config path, should it complain loudly or behave any differently?

There's good reason to do such a thing - uploading your jj config to a private repo would make a lot of sense. I think we answer no for now, and can consider circling back to it later if we really want.

File: lib/src/secure_config.rs [hunk 6]
```diff
@@ -0,0 +1,482 @@
...
+    // Technically this is either a repo or a workspace.
+    repo_dir: PathBuf,
+    // A directory containing subdirectories, each corresponding to a config id.
+    config_dir: PathBuf,
+    // The name of the config id file.
+    config_id_name: &'static str,
+    // The name of the legacy config file.
+    legacy_config_name: &'static str,
+    // A cache of the output of the config.
+    cache: RefCell<Option<(Option<PathBuf>, ConfigMetadata)>>,
```
Comment (yuja) [inline lib/src/secure_config.rs]: Can we instead pass global parameters (`rng` and `config_dir`) to `load_config()` functions?

It seems odd that both global and per-repo/workspace parameters are stored in the same type. If `config_dir` isn't a part of this struct, `ConfigEnv::reset_repo_path()` can set `self.repo_config` unconditionally. Then, `self.repo_path` can be replaced with `self.repo_config.repo_dir`.

File: lib/Cargo.toml [hunk 7]
```diff
@@ -45,6 +45,7 @@ futures = { workspace = true }
 gix = { workspace = true, optional = true }
 globset = { workspace = true }
 hashbrown = { workspace = true }
+hex = { workspace = true }
```
Comment (yuja) [inline lib/Cargo.toml]: nit: use `jj_lib::hex_util` instead

File: lib/src/secure_config.rs [hunk 8]
```diff
@@ -0,0 +1,482 @@
...
+        )?;
+        Ok(config_path)
+    }
+
+    fn generate_initial_config(
+        &self,
+        config_id: &str,
+    ) -> Result<(PathBuf, ConfigMetadata), SecureConfigError> {
+        let metadata = ConfigMetadata {
+            path: dunce::canonicalize(&self.repo_dir)?
```
Comment (yuja) [inline lib/src/secure_config.rs]: `repo_dir` should be canonicalized by caller. It's better to not do path canonicalization at random places.

File: lib/src/secure_config.rs [hunk 9]
```diff
@@ -0,0 +1,482 @@
...
+                .to_str()
```
Comment (yuja) [inline lib/src/secure_config.rs]: A repo path may be non-utf8 bytes. We'll have to use `file_util::path_to_bytes()` and propagate error instead of panicking.

File: lib/src/secure_config.rs [hunk 10]
```diff
@@ -0,0 +1,482 @@
...
+        warn: impl Fn(&str) -> std::io::Result<()>,
+    ) -> Result<(Option<PathBuf>, ConfigMetadata), SecureConfigError> {
+        if let Some(cache) = self.cache.borrow().as_ref() {
+            return Ok(cache.clone());
+        }
+        let config_id_path = self.repo_dir.join(self.config_id_name);
+        let value = match fs::read_to_string(&config_id_path).context(&config_id_path) {
+            Ok(s) => {
+                let s = s.trim_end();
+                let config_dir = self.config_dir.join(s);
```
Comment (yuja) [inline lib/src/secure_config.rs]: We shouldn't trust data loaded from `.jj/repo/config-id`. A malicious user may send repository with `config-id = ../../bad/path`.

I think the easiest option is to write bytes to `config-id` and hexilify here. It's also good to check the length of the id.

**Review by yuja — COMMENTED** [review]
Sorry for the delay. I just quickly reviewed the code, and left random comments.

File: lib/src/secure_config.rs (hunk 1 above)
Comment (PhilipMetzger) [reply lib/src/secure_config.rs]: > A warning should only be used to inform the user that they need to do something differently, or there's some gotcha they need to be aware of. Here, it's been automatically migrated for them, so they don't need to do anything differently.

A warning still is used to _inform_ of them of the actual change, instead of just doing it silently.

File: lib/src/secure_config.rs (hunk 10 above)
Comment (matts1) [reply lib/src/secure_config.rs]: I don't like the idea of writing bytes. I would like a human to be able to manually change the config ID if they find that the automated process is wrong.

Comment (yuja) [reply lib/src/secure_config.rs]: Fair.

BTW, we usually don't append or trim `\n` from text-based control files. I don't think `.trim_end()` is needed here. The user can just do `echo -n`.

File: cli/src/commands/git/init.rs [hunk 11]
```diff
@@ -263,8 +264,12 @@ fn init_git_refs(
 pub fn maybe_set_repository_level_trunk_alias(
     ui: &Ui,
     workspace_command: &WorkspaceCommandHelper,
+    config: &ConfigEnv,
```
Comment (yuja) [inline cli/src/commands/git/init.rs]: nit: pass `repo` instead of `workspace_command` to ensure that we won't get `config_env` from `workspace_command`.

I think `config_env` can be reinitialized by caller.

File: cli/src/commands/git/init.rs [hunk 12]
```diff
@@ -263,8 +264,12 @@ fn init_git_refs(
...
 ) -> Result<(), CommandError> {
     let git_repo = git::get_git_repo(workspace_command.repo().store())?;
+    // For repositories created by the current command, config_env.repo_path is None
+    let mut config = config.clone();
+    config.reset_repo_path(workspace_command.repo_path());
```
Comment (yuja) [inline cli/src/commands/git/init.rs]: Good catch. I think the reconfigured `config_env` can be returned from `command.settings_for_new_workspace(ui, wc_path)`.

File: cli/src/config.rs [hunk 13]
```diff
@@ -424,21 +440,40 @@ impl ConfigEnv {
     /// Sets the directory where repo-specific config file is stored. The path
     /// is usually `.jj/repo`.
     pub fn reset_repo_path(&mut self, path: &Path) {
+        if self.repo_path.as_deref() != Some(path) {
+            self.repo_config = Some(SecureConfig::new_repo(
+                dunce::canonicalize(path).unwrap_or_else(|_| path.to_owned()),
+            ));
+        }
```
Comment (yuja) [inline cli/src/config.rs]: nit: I think it's okay to reset `self.repo_config` unconditionally and invalidate cache.

File: cli/src/config.rs [hunk 14]
```diff
@@ -424,21 +440,40 @@ impl ConfigEnv {
     /// Sets the directory where repo-specific config file is stored. The path
     /// is usually `.jj/repo`.
     pub fn reset_repo_path(&mut self, path: &Path) {
+        if self.repo_path.as_deref() != Some(path) {
+            self.repo_config = Some(SecureConfig::new_repo(
+                dunce::canonicalize(path).unwrap_or_else(|_| path.to_owned()),
```
Comment (yuja) [inline cli/src/config.rs]: The `path` should have been canonicalized by caller.

File: cli/src/config.rs [hunk 15]
```diff
@@ -320,21 +329,24 @@ impl UnresolvedConfigEnv {
...
 }
 
 impl ConfigEnv {
     /// Initializes configuration loader based on environment variables.
     pub fn from_environment() -> Self {
         let config_dir = etcetera::choose_base_strategy()
             .ok()
-            .map(|s| s.config_dir());
+            .map(|s| s.config_dir())
+            .map(|d| dunce::canonicalize(&d).unwrap_or(d));
```
Comment (yuja) [inline cli/src/config.rs]: Why do we need to canonicalize the user config path? Can you document?

File: cli/src/config.rs [hunk 16]
```diff
@@ -424,21 +440,40 @@ impl ConfigEnv {
...
 
     /// Returns a path to the existing repo-specific config file.
-    fn existing_repo_config_path(&self) -> Option<&Path> {
-        match self.repo_config_path {
-            Some(ref path) if path.exists() => Some(path.as_path()),
+    pub fn repo_config_path(&self, ui: &Ui) -> Result<Option<PathBuf>, ConfigLoadError> {
+        Ok(match (&self.repo_config, self.root_config_dir.as_ref()) {
+            (Some(config), Some(root_config_dir)) => Some(
+                config
+                    .load_config(&self.rng, &root_config_dir.join("repos"), |s| {
```
Comment (yuja) [inline cli/src/config.rs]: I think `jj config path` should be a readonly operation (except for config migration), but I'm not pretty sure. It might be sometimes useful that `jj config path` initializes new config directory and print its path.

File: cli/src/config.rs [hunk 17]
```diff
@@ -464,35 +500,63 @@ impl ConfigEnv {
...
+        {
             config.as_mut().load_file(ConfigSource::Repo, path)?;
         }
         Ok(())
     }
 
-    /// Sets the directory for the workspace and the workspace-specific config
-    /// file.
+    /// Sets the directory where repo-specific config file is stored. The path
+    /// is usually `.jj/repo`.
```
Comment (yuja) [inline cli/src/config.rs]: nit: copy-paste error.

Also beware that the workspace root `path` here doesn't include `.jj`.

File: cli/tests/common/test_environment.rs [hunk 18]
```diff
@@ -32,6 +33,10 @@ use super::fake_diff_editor_path;
 use super::fake_editor_path;
 use super::to_toml_value;
 
+static CONFIG_NAME: LazyLock<Regex> = LazyLock::new(|| {
+    Regex::new(r#"(\$TEST_ENV/home/.config/jj/(:?repos|workspaces))/[0-9a-f]+"#).unwrap()
```
Comment (yuja) [inline cli/tests/common/test_environment.rs]: nit: maybe you mean `(?:` ?

Alternatively, we can initialize the RNG with `$JJ_RANDOMNESS_SEED`. Then, test outputs would be stable and we won't need `$CONFIG_ID` normalization. I think this is better, but I don't feel strongly.

File: docs/gerrit.md [hunk 19]
```diff
@@ -30,12 +30,13 @@ $ jj git clone https://review.gerrithub.io/your/project
...
-```toml
-[gerrit]
-default-remote = "gerrit"       # name of the Git remote to push to
-default-remote-branch = "main"  # target branch in Gerrit
+```shell
+# Name of the Git remote to push to
+jj config set --repo gerrit.default-remote "gerrit" 
+# Target branch in Gerrit
+jj config set --repo gerrit.default-remote-branch "main"
 ```
```
Comment (yuja) [inline docs/gerrit.md:40]: nit: I think we can suggest `jj config edit` instead.

File: lib/src/config.rs [hunk 20]
```diff
@@ -68,6 +69,10 @@ pub enum ConfigLoadError {
         /// Source file path.
         source_path: Option<PathBuf>,
     },
+
+    /// Failed to determine the path to the repo files.
+    #[error(transparent)]
+    SecureConfigError(#[from] SecureConfigError),
```
Comment (yuja) [inline lib/src/config.rs]: This isn't technically a `ConfigLoadError` of this module. I think `config_env` functions can instead return `CommandError`. That's unavoidable anyway because these functions prints warnings to `ui`, and `io::Error` of `ui` will have to be mapped to `BrokenPipe`, etc.

File: lib/src/secure_config.rs [hunk 21]
```diff
@@ -0,0 +1,571 @@
...
+#[derive(Clone, Debug)]
+pub struct SecureConfig {
+    // Technically this is either a repo or a workspace.
+    repo_dir: PathBuf,
+    // The name of the config id file.
+    config_id_name: &'static str,
+    // The name of the legacy config file.
+    legacy_config_name: &'static str,
+    // A cache of the output of the config.
+    cache: RefCell<Option<(Option<PathBuf>, ConfigMetadata)>>,
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: "the output of the config" sounds like a config content.

File: lib/src/secure_config.rs [hunk 22]
```diff
@@ -0,0 +1,571 @@
...
+If you work across multiple computers, you may want to keep your user config directory in sync."###;
+
+/// A mechanism to access config files for a repo securely.
+#[derive(Clone, Debug)]
+pub struct SecureConfig {
+    // Technically this is either a repo or a workspace.
+    repo_dir: PathBuf,
+    // The name of the config id file.
+    config_id_name: &'static str,
+    // The name of the legacy config file.
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: use `///` for doc comment

File: lib/src/secure_config.rs [hunk 23]
```diff
@@ -0,0 +1,571 @@
...
+            repo_dir,
+            config_id_name,
+            legacy_config_name,
+            cache: RefCell::new(None),
+        }
+    }
+
+    /// Creates a secure config for a repo. Takes the .jj/repo directory.
+    pub fn new_repo(repo_dir: PathBuf) -> Self {
+        Self::new(repo_dir, "repo-config-id", "config.toml")
```
Comment (yuja) [inline lib/src/secure_config.rs]: should be `.jj/repo/config-id`?

File: lib/src/secure_config.rs [hunk 24]
```diff
@@ -0,0 +1,571 @@
...
+        )
+    }
+
+    // If path_to_bytes failed, jj should not stop working.
+    // Instead, we simply treat all non-utf8 paths as empty.
+    fn encoded_path(&self) -> &[u8] {
+        path_to_bytes(&self.repo_dir).ok().unwrap_or_default()
+    }
+
+    fn generate_config_id(&self, rng: &RefCell<ChaCha20Rng>) -> String {
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: not depend on `self`. move to free function?

File: lib/src/secure_config.rs [hunk 25]
```diff
@@ -0,0 +1,571 @@
...
+        encode_hex(
+            &(0..CONFIG_ID_BYTES)
+                .map(|_| rng.borrow_mut().random::<u8>())
+                .collect::<Vec<_>>(),
+        )
+    }
+
+    fn generate_config(
+        &self,
+        config_dir: &Path,
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: rename to `root_config_dir`? It's confusing that this `config_dir` is different than the one of `update_metadata()`.

File: lib/src/secure_config.rs [hunk 26]
```diff
@@ -0,0 +1,571 @@
...
+        config_id: &str,
+        content: &[u8],
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: use `Option<&[u8]>`? It's probably better to migrate an empty legacy config file to an empty file.

File: lib/src/secure_config.rs [hunk 27]
```diff
@@ -0,0 +1,571 @@
...
+    ) -> Result<(PathBuf, ConfigMetadata), SecureConfigError> {
+        let metadata = ConfigMetadata {
+            path: self.encoded_path().to_vec(),
+        };
+        let path = self.generate_config(config_dir, config_id, &[], &metadata)?;
+        Ok((path, metadata))
+    }
+
+    fn update_metadata(
+        &self,
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: unused `self`

File: lib/src/secure_config.rs [hunk 28]
```diff
@@ -0,0 +1,571 @@
...
+            Some(path_from_bytes(&metadata.path)?)
+        };
+
+        if want == got {
+            return Ok((config_dir, metadata));
+        }
+        let got = match got {
+            Some(x) if x.is_dir() => x,
+            _ => {
+                // The old repo does not exist. Assume the user moved it.
```
Comment (yuja) [inline lib/src/secure_config.rs:207]: I think we should print a message when copy/rename gets detected and config location is updated accordingly.

Maybe we can return stats enum, struct, or list of enums and let caller print it?

File: lib/src/secure_config.rs [hunk 29]
```diff
@@ -0,0 +1,571 @@
...
+             can edit the new file with `jj config edit`"
+        ))?;
+        Ok((Some(config_file), metadata))
+    }
+
+    /// Determines the path to the config, and any metadata associated with it.
+    /// If no config exists, the path will be None.
+    pub fn maybe_load_config(
+        &self,
+        rng: &RefCell<ChaCha20Rng>,
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: pass by `&mut Chacha20Rng`? This module cannot guarantee that `rng` is borrowed elsewhere.

File: lib/src/secure_config.rs [hunk 30]
```diff
@@ -0,0 +1,571 @@
...
+        }
+        let config_id_path = self.repo_dir.join(self.config_id_name);
+        let value = match fs::read_to_string(&config_id_path).context(&config_id_path) {
+            Ok(config_id) => {
+                if config_id.len() != CONFIG_ID_BYTES * 2
+                    || !config_id.chars().all(|c| c.is_ascii_hexdigit())
+                {
+                    return Err(SecureConfigError::BadConfigIdError);
+                }
+                let root_config_dir = config_dir;
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: rename the function argument to `root_config_dir`

File: lib/src/secure_config.rs [hunk 31]
```diff
@@ -0,0 +1,571 @@
...
+                        let (config_dir, metadata) = self.handle_metadata_path(
+                            rng,
+                            root_config_dir,
+                            config_dir,
+                            ConfigMetadata::decode(buf.as_slice())?,
+                        )?;
+                        (Some(config_dir.join(CONFIG_FILE)), metadata)
+                    }
+                    Err(e) if e.source.kind() == NotFound => {
+                        warn(CONFIG_NOT_FOUND)?;
```
Comment (yuja) [inline lib/src/secure_config.rs]: This `io::Error` should be different from "I/O for a file failed".

File: lib/src/secure_config.rs [hunk 32]
```diff
@@ -0,0 +1,571 @@
...
+        root_config_dir: &Path,
+        config_dir: PathBuf,
+        mut metadata: ConfigMetadata,
+    ) -> Result<(PathBuf, ConfigMetadata), SecureConfigError> {
+        let (encoded, want) = if let Ok(encoded) = path_to_bytes(&self.repo_dir) {
+            (encoded, Some(self.repo_dir.as_path()))
+        } else {
+            Default::default()
+        };
+        let got = if metadata.path.is_empty() {
```
Comment (yuja) [inline lib/src/secure_config.rs]: Perhaps, we can mark the proto field as `optional bytes` and use `Option<Vec<u8>>`? That will help prevent misuse of paths that couldn't be encoded to bytes.

File: cli/src/config.rs [hunk 33]
```diff
@@ -320,21 +329,24 @@ impl UnresolvedConfigEnv {
...
     repo_path: Option<PathBuf>,
     workspace_path: Option<PathBuf>,
     user_config_paths: Vec<ConfigPath>,
-    repo_config_path: Option<ConfigPath>,
-    workspace_config_path: Option<ConfigPath>,
+    repo_config: Option<SecureConfig>,
+    workspace_config: Option<SecureConfig>,
     command: Option<String>,
     hostname: Option<String>,
+    rng: RefCell<ChaCha20Rng>,
```
Comment (yuja) [inline cli/src/config.rs]: Wrap in `Rc` so cloned `ConfigEnv` won't generate the same config ID.

File: cli/src/config.rs (hunk 16 above)
Comment (matts1) [reply cli/src/config.rs]: Making it readonly is impossible, given that the design makes config IDs lazy. We need a config ID regardless in order to print a path.

We could choose not to generate the directory, but I would have an expectation that a command like `echo 'blah' >> $(jj config path)` would work. This requires the directory be initialized.

File: lib/src/secure_config.rs (hunk 28 above)
Comment (matts1) [reply lib/src/secure_config.rs:207]: I've done this for copies. I won't do this for renames, however, for two reasons:
* Nothing changes from a user's perspective after a rename. The config file remains at the same location, the only thing that gets updated is metadata.binpb, which the user doesn't see.
* Renames can have a lot more false positives than copies. For example
  * In a dual-boot system, every time I switch between linux and windows
  * Every time I remount an external hard drive at a different location
  * Every time I run a command inside a chroot.

File: cli/src/commands/git/init.rs (hunk 11 above)
Comment (matts1) [reply cli/src/commands/git/init.rs]: See my response to https://github.com/jj-vcs/jj/pull/8222#discussion_r2605752446

File: cli/src/commands/git/init.rs (hunk 12 above)
Comment (matts1) [reply cli/src/commands/git/init.rs]: I looked at the implementation, and it's impossible to get an `&mut ConfigEnv` from the command without a `&mut CommandHelper`.

```rust
   pub fn settings_for_new_workspace(
        &self,
        workspace_root: &Path,
    ) -> Result<UserSettings, CommandError> {
        let mut config_env = self.data.config_env.clone();
        let mut raw_config = self.data.raw_config.clone();
        let repo_path = workspace_root.join(".jj").join("repo");
        config_env.reset_repo_path(&repo_path);
        config_env.reload_repo_config(&mut raw_config)?;
        config_env.reset_workspace_path(workspace_root);
        config_env.reload_workspace_config(&mut raw_config)?;
        let mut config = config_env.resolve_config(&raw_config)?;
        // No migration messages here, which would usually be emitted before.
        jj_lib::config::migrate(&mut config, &self.data.config_migrations)?;
        Ok(self.data.settings.with_new_config(config)?)
    }
```

As you can see, `settings_for_new_workspace` uses the same trick where it modifies a copy of the config_env, not the original, and it doesn't return the copy - it drops it after using it to resolve the config.

So unfortunately that idea won't work.

Comment (yuja) [reply cli/src/commands/git/init.rs]: Can't you return `config_env` from `settings_for_new_workspace()`?

```rust
let (settings, config_env) = command.settings_for_new_workspace(workspace_root)?;
...
maybe_set_repository_level_trunk_alias(ui, repo, &config_env)?;
```

File: cli/src/config.rs (hunk 16 above)
Comment (yuja) [reply cli/src/config.rs]: I mean it might be okay for `jj config path` print no paths if config-id and its associated directory wasn't initialized yet.

File: cli/src/commands/git/init.rs (hunk 12 above)
Comment (matts1) [reply cli/src/commands/git/init.rs]: I could, but that doesn't seem any cleaner than the current approach. If you prefer it that way though I can do it.

File: cli/src/config.rs (hunk 16 above)
Comment (matts1) [reply cli/src/config.rs]: IMO, the very fact that the user has ran `jj config path` means they want to do something with the path, so I don't think printing no paths is a good idea.

File: cli/src/commands/git/init.rs (hunk 12 above)
Comment (yuja) [reply cli/src/commands/git/init.rs]: I think it's better to not pass `workspace_command` when `config_env` shouldn't be obtained from. And if we pass `(repo, config_env)` in place of `workspace_command`, it seems natural to get properly-configured `(settings, config_env)` pair from `settings_for_new_workspace()`.

File: cli/src/config.rs (hunk 16 above)
Comment (yuja) [reply cli/src/config.rs]: I think there are two use cases of `jj config path`:
1. see where config files are potentially read from
2. get config file path to edit

For (2), we need to initialize the storage, and it wouldn't matter whether the target file is created or not (in addition to the storage directory.) For (1), I expect no config directory nor file would be created.

I'm not sure which use case is common, and I'm not strongly against making `jj config path` do (2). I think the command help should be updated if we choose (2), though.

File: lib/src/secure_config.rs [hunk 34]
```diff
@@ -0,0 +1,596 @@
...
+    #[error(transparent)]
+    BadPathEncoding(#[from] BadPathEncoding),
+
+    /// The config ID isn't CONFIG_ID_BYTES * 2 hex chars.
+    #[error("Found an invalid config ID")]
+    BadConfigIdError,
+}
+
+#[derive(Clone, Debug, Default)]
+/// The result of \[maybe_\]load_config.
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: nit: this description isn't really descriptive, also move the comment above the derives.

File: lib/src/secure_config.rs [hunk 35]
```diff
@@ -0,0 +1,596 @@
...
+        Ok(())
+    }
+
+    /// Migrates the legacy config, if it exists.
+    fn maybe_migrate_legacy_config(
+        &self,
+        rng: &mut ChaCha20Rng,
+        root_config_dir: &Path,
+    ) -> Result<LoadedSecureConfig, SecureConfigError> {
+        // TODO: This function should be updated at EOY 2026 to no longer
```
Comment (PhilipMetzger) [inline lib/src/secure_config.rs]: nit: EOY 2026 should be jj 0.49+, so add that

File: cli/src/config.rs [hunk 36]
```diff
@@ -260,6 +267,16 @@ fn create_dir_all(path: &Path) -> std::io::Result<()> {
...
+fn handle_secure_config(
+    ui: &Ui,
+    config: LoadedSecureConfig,
+) -> Result<LoadedSecureConfig, CommandError> {
+    for warning in &config.warnings {
+        writeln!(ui.warning_default(), "{warning}")?;
+    }
+    Ok(config)
+}
+
```
Comment (PhilipMetzger) [inline cli/src/config.rs]: nit: this should be called something like `hande_secure_config_warnings`, since it only displays the respective warnings and returns the config unmodified. This function also deserves a TODO for the slated removal in EOY 2026

**Review by PhilipMetzger — COMMENTED** [review]
another round of minor stuff, otherwise this looks great

File: cli/src/config.rs (hunk 36 above)
Comment (matts1) [reply cli/src/config.rs]: This function doesn't need a todo - it won't change at that point because there are still other warnings that get printed.

File: cli/src/commands/git/init.rs [hunk 37]
```diff
@@ -265,10 +269,9 @@ fn init_git_refs(
 // Checks "upstream" first, then "origin" as fallback.
 pub fn maybe_set_repository_level_trunk_alias(
     ui: &Ui,
-    workspace_command: &WorkspaceCommandHelper,
+    git_repo: &gix::Repository,
+    config: &ConfigEnv,
```
Comment (yuja) [inline cli/src/commands/git/init.rs]: nit: `config` -> `config_env`

File: cli/src/commands/git/mod.rs [hunk 38]
```diff
@@ -128,10 +128,16 @@ fn get_single_remote(store: &Store) -> Result<Option<RemoteNameBuf>, UnexpectedG
 /// Sets repository level `trunk()` alias to the specified remote symbol.
 fn write_repository_level_trunk_alias(
     ui: &Ui,
-    repo_path: &Path,
+    config: &ConfigEnv,
```
Comment (yuja) [inline cli/src/commands/git/mod.rs]: nit: `config` -> `config_env`

File: cli/src/config.rs [hunk 39]
```diff
@@ -260,6 +267,16 @@ fn create_dir_all(path: &Path) -> std::io::Result<()> {
...
 
+fn handle_secure_config_warnings(
+    ui: &Ui,
+    config: LoadedSecureConfig,
+) -> Result<LoadedSecureConfig, CommandError> {
+    for warning in &config.warnings {
+        writeln!(ui.warning_default(), "{warning}")?;
+    }
+    Ok(config)
+}
```
Comment (yuja) [inline cli/src/config.rs]: nit: just pass `&LoadedSecureConfig` to this function and return `Ok(())`. This function doesn't update `config`.

File: cli/src/config.rs [hunk 40]
```diff
@@ -419,24 +451,41 @@ impl ConfigEnv {
...
+            }
+            _ => None,
+        })
     }
 
     /// Returns a path to the existing repo-specific config file.
-    fn existing_repo_config_path(&self) -> Option<&Path> {
-        match self.repo_config_path {
-            Some(ref path) if path.exists() => Some(path.as_path()),
+    pub fn repo_config_path(&self, ui: &Ui) -> Result<Option<PathBuf>, CommandError> {
```
Comment (yuja) [inline cli/src/config.rs:488]: nit: Can you update the doc comment and help text of `jj config path`? It's important that this function can initialize new config store directory.

(also applies to `workspace_config_path()`)

File: cli/src/config.rs [hunk 41]
```diff
@@ -419,24 +451,41 @@ impl ConfigEnv {
...
+                let mut guard = self.rng.lock().unwrap();
+                handle_secure_config_warnings(
+                    ui,
+                    config.load_config(&mut guard, &root_config_dir.join("repos"))?,
+                )?
+                .config_file
+            }
             _ => None,
-        }
+        })
```
Comment (yuja) [inline cli/src/config.rs]: nit: maybe we can extract helper function like `repo_config_path_with(..., |config, rng, root| config.load_config(rng, root))`, but I don't feel strongly.

File: cli/tests/common/test_environment.rs [hunk 42]
```diff
@@ -284,6 +291,9 @@ impl TestEnvironment {
                     .to_string();
             };
         }
+        normalized = CONFIG_NAME
+            .replace_all(&normalized, "$1/$$CONFIG_ID")
+            .to_string();
```
Comment (yuja) [inline cli/tests/common/test_environment.rs]: delete normalization as config id should now be stable.

File: lib/src/protos/secure_config.proto [hunk 43]
```diff
@@ -0,0 +1,24 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+syntax = "proto3";
+
+package secure_config;
+
+// Metadata about the configuration files for jj
+message ConfigMetadata {
+  // The absolute path to the repo or workspace root.
```
Comment (yuja) [inline lib/src/protos/secure_config.proto]: nit: "workspace root" -> `<workspace_root>/.jj`

File: lib/src/secure_config.rs [hunk 44]
```diff
@@ -0,0 +1,598 @@
...
+    #[error(transparent)]
+    PathError(#[from] PathError),
+
+    /// Failed to decode the user configuration file.
+    #[error(transparent)]
+    DecodeError(#[from] prost::DecodeError),
+
+    /// I/O for a file failed
+    #[error(transparent)]
+    IoError(#[from] std::io::Error),
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: `IoError` is no longer used

File: lib/src/secure_config.rs [hunk 45]
```diff
@@ -0,0 +1,598 @@
...
+
+    /// Failed to persist the temporary file to disk
+    #[error(transparent)]
+    PersistError(#[from] PersistError),
```
Comment (yuja) [inline lib/src/secure_config.rs]: `PersistError` carries open file object. It's better to extract the inner `io::Error` and wrap it in `PathError`.

File: lib/src/secure_config.rs [hunk 46]
```diff
@@ -0,0 +1,598 @@
...
+    temp_file.persist(path)?;
+    Ok(())
+}
+
+fn generate_config_id(rng: &mut ChaCha20Rng) -> String {
+    encode_hex(
+        &(0..CONFIG_ID_BYTES)
+            .map(|_| rng.random::<u8>())
+            .collect::<Vec<_>>(),
+    )
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: `random::<[u8; CONFIG_ID_BYTES]>()` also works

File: lib/src/secure_config.rs [hunk 47]
```diff
@@ -0,0 +1,598 @@
...
+        atomic_write(
+            &self.repo_dir.join(self.config_id_name),
+            config_id.as_bytes(),
+        )?;
+        Ok(config_path)
+    }
+
+    fn generate_initial_config(
+        &self,
+        config_dir: &Path,
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: `config_dir` -> `root_config_dir`

File: lib/src/secure_config.rs [hunk 48]
```diff
@@ -0,0 +1,598 @@
...
+                    Some(&old_config_content),
+                    &metadata,
+                )?;
+                return Ok(LoadedSecureConfig {
+                    config_file: Some(config_path.clone()),
+                    metadata,
+                    warnings: vec![format!(
+                        "Your repo appears to have been copied from {got:?} to {:?}. The \
+                         corresponding repo config file has also been copied.",
+                        &self.repo_dir
```
Comment (yuja) [inline lib/src/secure_config.rs]: Use `.display()` instead of debug formatting. Windows directory separators would look ugly with `{:?}`.

File: lib/src/secure_config.rs [hunk 49]
```diff
@@ -0,0 +1,598 @@
...
+            &generate_config_id(rng),
+            Some(&config),
+            &metadata,
+        )?;
+        self.update_legacy_config_file(&config_file, &config)?;
+        Ok(LoadedSecureConfig {
+            warnings: vec![format!(
+                "Your config file has been migrated from {legacy_config:?} to {config_file:?}. \
+                 You can edit the new file with `jj config edit`"
+            )],
```
Comment (yuja) [inline lib/src/secure_config.rs:317]: nit: same here. `.display()` instead of `:?`

File: lib/src/secure_config.rs [hunk 50]
```diff
@@ -0,0 +1,598 @@
...
+            "config"
+        );
+        assert!(!loaded.warnings.is_empty());
+
+        // On unix, it should be a symlink.
+        #[cfg(unix)]
+        {
+            fs::write(loaded.config_file.as_deref().unwrap(), "new").unwrap();
+            assert_eq!(fs::read_to_string(&legacy_config).unwrap(), "new");
+        }
```
Comment (yuja) [inline lib/src/secure_config.rs:500]: nit: `if cfg!(unix)` is preferred so long as the code compiles.

**Review by yuja — COMMENTED** [review]
Looks generally good, thanks!

File: docs/design/secure-config.md [hunk 51]
```diff
@@ -2,6 +2,8 @@
 
 Author: [Matt Stark](mailto:msta@google.com)
 
+Status: Implemented
+
```
Comment (PhilipMetzger) [inline docs/design/secure-config.md]: nit: This is something I left unspecified when I initially formalized design docs, in https://github.com/jj-vcs/jj/pull/3940 so could you open another PR to discuss the respective changes to design docs _before_ doing it. Thanks. 

My current suggestion would be to move stuff to an implemented sub-directory but let's move that to the respective PR.

File: cli/src/config.rs [hunk 52]
```diff
@@ -43,10 +49,14 @@ use tracing::instrument;
 use crate::command_error::CommandError;
 use crate::command_error::config_error;
 use crate::command_error::config_error_with_message;
+use crate::ui::Ui;
 
 // TODO(#879): Consider generating entire schema dynamically vs. static file.
 pub const CONFIG_SCHEMA: &str = include_str!("config-schema.json");
 
+pub const REPO_CONFIG_DIR: &str = "repos";
+pub const WORKSPACE_CONFIG_DIR: &str = "workspaces";
```
Comment (yuja) [inline cli/src/config.rs]: nit: remove `pub` if we aren't going to use these constants out of this module

File: cli/src/config.rs [hunk 53]
```diff
@@ -419,24 +444,51 @@ impl ConfigEnv {
...
     pub fn reset_repo_path(&mut self, path: &Path) {
+        self.repo_config = Some(SecureConfig::new_repo(path.to_path_buf()));
         self.repo_path = Some(path.to_owned());
-        self.repo_config_path = Some(ConfigPath::new(path.join("config.toml")));
     }
 
-    /// Returns a path to the repo-specific config file.
-    pub fn repo_config_path(&self) -> Option<&Path> {
-        self.repo_config_path.as_ref().map(|p| p.as_path())
+    fn load_secure_config(
```
Comment (yuja) [inline cli/src/config.rs]: nit: move this function above or below so all `repo` functions and `workspace` functions are grouped.

File: cli/src/config.rs [hunk 54]
```diff
@@ -448,49 +500,53 @@ impl ConfigEnv {
     pub fn repo_config_files(
         &self,
         config: &RawConfig,
-    ) -> Result<Vec<ConfigFile>, ConfigLoadError> {
-        config_files_for(config, ConfigSource::Repo, || self.new_repo_config_file())
+        ui: &Ui,
+    ) -> Result<Vec<ConfigFile>, CommandError> {
```
Comment (yuja) [inline cli/src/config.rs:504]: nit: the parameter order `(ui, config)` seems more common

File: cli/tests/common/test_environment.rs [hunk 55]
```diff
@@ -176,6 +176,16 @@ impl TestEnvironment {
...
+        if cfg!(windows) {
+            // Windows uses `TEMP` to create temporary directories, which we need for some
+            // tests.
+            if let Ok(tmp_var) = std::env::var("TEMP") {
+                cmd.env("TEMP", tmp_var);
+            }
+            // Ensure that our tests don't write to the real %APPDATA%.
+            cmd.env("APPDATA", self.home_dir.join(".config"));
+        }
+
```
Comment (yuja) [inline cli/tests/common/test_environment.rs]: Looks like a bad merge. Can you remove `TEMP`? I think it's also better to move `APPDATA` closer to `HOME` so it can be overridden by `self.env_vars`.

File: docs/config.md [hunk 56]
```diff
@@ -13,11 +13,13 @@ These are the config settings available to jj/Jujutsu.
...
-located in `.jj/repo/config.toml`.
+- The repo settings. These can be edited with `jj config edit --repo`, or found
+  with `jj config path --repo`. For security reasons, they are not located inside
+  the repo.
 
-- The workspace settings. These can be edited with `jj config edit --workspace`
-and are located in `.jj/workspace-config.toml` in the workspace root.
+- The workspace settings. These can be edited with `jj config edit --workspace`,
+  or found with `jj config path --workspace`. For security reasons, they are not
+  located inside the workspace.
```
Comment (yuja) [inline docs/config.md:22]: nit: "the workspace" sounds like the working-copy directory, not the metadata directory. Maybe "the .jj directory" is better?

File: docs/gerrit.md [hunk 57]
```diff
@@ -29,8 +29,9 @@ $ jj git remote add gerrit https://review.gerrithub.io/yourname/yourproject
 $ jj git clone https://review.gerrithub.io/your/project
 ```
 
-If you used option 2 You can configure default values in your repository config
-by appending the below to `.jj/repo/config.toml`, like so:
+If you used option 2 you can configure default values in your repository config
```
Comment (yuja) [inline docs/gerrit.md]: nit: insert comma before "you can ..."

File: lib/gen-protos/src/main.rs [hunk 58]
```diff
@@ -22,6 +22,7 @@ fn main() -> Result<()> {
         "local_working_copy.proto",
         "simple_op_store.proto",
         "simple_store.proto",
+        "secure_config.proto",
```
Comment (yuja) [inline lib/gen-protos/src/main.rs]: nit: sort these

File: lib/src/secure_config.rs [hunk 59]
```diff
@@ -0,0 +1,590 @@
...
+    pub config_file: Option<PathBuf>,
+    /// The metadata for the config.
+    pub metadata: ConfigMetadata,
+    /// Any warnings that we want to be reported to the user.
+    pub warnings: Vec<String>,
+}
+
+fn atomic_write(path: &Path, content: &[u8]) -> Result<(), SecureConfigError> {
+    let mut temp_file = NamedTempFile::new_in(path.parent().unwrap()).context(path)?;
+    temp_file.write_all(content).context(path)?;
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: the context paths should be `path.parent()` and `temp_file.path()`

File: lib/src/secure_config.rs [hunk 60]
```diff
@@ -0,0 +1,590 @@
...
+        rng: &mut ChaCha20Rng,
+        root_config_dir: &Path,
+        config_dir: PathBuf,
+        mut metadata: ConfigMetadata,
+    ) -> Result<LoadedSecureConfig, SecureConfigError> {
+        let encoded = path_to_bytes(&self.repo_dir).ok();
+        let got = metadata
+            .path
+            .as_deref()
+            .map(|p| path_from_bytes(p))
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: `.map(path_from_bytes)`

File: lib/src/secure_config.rs [hunk 61]
```diff
@@ -0,0 +1,590 @@
...
+                    warnings: vec![],
+                });
+            }
+        };
+        // We attempt to create a temporary file in the new repo.
+        // If it fails, we have readonly access to a repo, so we do nothing.
+        if let Ok(tmp) = NamedTempFile::new_in(&self.repo_dir) {
+            // If we write to the new repo and it shows up in the old one,
+            // we can skip this step, since it's not a copy.
+            if !got.join(tmp.path().file_name().unwrap()).exists() {
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: at your option, these `if`s can be flattened

File: lib/src/secure_config.rs [hunk 62]
```diff
@@ -0,0 +1,590 @@
...
+                    config_file: Some(config_path.clone()),
+                    metadata,
+                    warnings: vec![format!(
+                        "Your repo appears to have been copied from {} to {}. The corresponding \
+                         repo config file has also been copied.",
+                        got.display(),
+                        &self.repo_dir.display()
+                    )],
+                });
+            };
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: unneeded `;`

File: lib/src/secure_config.rs [hunk 63]
```diff
@@ -0,0 +1,590 @@
...
+    fn maybe_migrate_legacy_config(
+        &self,
+        rng: &mut ChaCha20Rng,
+        root_config_dir: &Path,
+    ) -> Result<LoadedSecureConfig, SecureConfigError> {
+        // TODO: This function should be updated in jj 0.49 to no longer
+        // automatically migrate repos, but instead print out a warning.
+        let legacy_config = self.repo_dir.join(self.legacy_config_name);
+        let config = match fs::read(&legacy_config).context(&legacy_config) {
+            Ok(config) => config,
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: this can be called `content` or `config_content`? "config" in this context has various meanings.

File: lib/src/secure_config.rs [hunk 64]
```diff
@@ -0,0 +1,590 @@
...
+        _td: TempDir,
+        rng: ChaCha20Rng,
+        config: SecureConfig,
+        repo_dir: PathBuf,
+        config_dir: PathBuf,
+    }
+
+    impl TestEnv {
+        fn new() -> Self {
+            let td = TempDir::new().unwrap();
```
Comment (yuja) [inline lib/src/secure_config.rs]: nit: use `crate::tests::new_temp_dir()` instead

File: CHANGELOG.md [hunk 65]
```diff
@@ -105,6 +105,11 @@ to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 * `jj workspace forget` now warns about unknown workspaces instead of failing.
 
+* Per-repo and per-workspace config is now stored outside the repo, for security
+  reasons. This is not a breaking change because we automatically migrate
+  legacy repos to this new format. `.jj/repo/config.toml` and
+  `.jj/workspace-config.toml` should no longer be used.
```
Comment (yuja) [inline CHANGELOG.md]: nit: remember to rebase and move the changelog entry

**Review by yuja — APPROVED** [review]
Thanks!

File: docs/config.md (hunk 56 above)
Comment (matts1) [reply docs/config.md:22]: That was intended. The .jj directory is a subdirectory of the workspace, and it is neither contained in the .jj directory or the parent directory.

Comment (yuja) [reply docs/config.md:22]: I mean it seems obvious that putting config file in the workspace directory (e.g. `.jjconfig.toml`) is bad idea for different reasons.

**Comment by dzaima** [comment]
I know I'm rather late to this discussion... but would there be anything wrong with keeping the config file in-repo, and having `~/.config/jj/*` just contain a set of known-safe/approved config files (be it files themselves, or just hashes; potentially still using something like the `config-id` mechanism that v0.38.0 introduced)? Fairly certain that has exactly the same safety guarantees as the current approach (assuming users don't do the explicit approving without actually checking, equivalent to the current assumption of users not copying untrusted configs into `~/.config/jj/repos/*`).

About the only downside I can come up with is that manually modifying the in-repo file would need to result in a "error: config insecure; please mark it as safe or discard it" error which then would need to be handled, but compared to the current thing of needing to edit `~/.config/jj/repos/$(cat .jj/repo/config-id)/config.toml` I don't think that's meaningfully bad (and of course `jj config edit --repo` exists and makes this a rather moot point anyway); and all other cases where this error would appear would be cases where in current jj you'd just have data loss.

This would solve all the issues around moving/copying things (and/or switching machines s.t. `~/.config/jj` is lost; or `rsync` workflows) resulting in data loss of repo configs, and would allow for `~/.config/jj` being safely GC'd or even entirely removed/lost (only consequence would be needing to manually re-approve the configs in affected repositories (or whatever future trustedness selection), but that's still way better than losing an entire config file).

I think this would also integrate nicely with the managed configuration proposal, being a source for trusted/reviewed configs.

**Comment by matts1** [comment]
The main reason I didn't do this was that I didn't want to have to deal with unapproved config files. I'm now pretty convinced, however, that your idea is better.

However, that does sound pretty reasonable to me. I think if the hash doesn't match because the user manually edits the config file it's pretty acceptable to error out completely on the next command and ask you to run `jj config approve --repo`, for example.

Feel free to send a PR to make changes to the design doc (I think it's docs/design/secure-config.md) and send it out for review. That way we can get approval from jj maintainers before going ahead with it.

**Comment by martinvonz** [comment]
Is the suggestion to move the config file back to `.jj/repo/config.toml` and make `~/.config/jj/repos/<config id>/*` just be a bunch of empty (?) files with a name that indicates an approved hash?

**Comment by matts1** [comment]
My understanding is that we would use the existing `~/.config/jj/repos/<config_id>/metadata.binpb` file and just add a field to it for the hash of the content.

**Comment by yuja** [comment]
If we take hashing/signing approach, we'll need a workaround to load config file that is still editing. The current model doesn't have this problem.

https://github.com/jj-vcs/jj/issues/3905

**Comment by dzaima** [comment]
I don't really have any specific comment on how the hashes would be stored (there are a bunch of reasonable options up to bikeshedding); but yeah the idea is that the repo config gets to live back in `.jj/repo/config.toml`, with basic `~/.config/jj` agreement.

Good point on the mid-edit problem, that does add some annoyance and/or complication; I suppose the respective `~/.config/jj/repos/*` metadata file could have a "the config file is mid-edit, accept it as such" flag, if it's desired to allow such to work? (I personally wouldn't be against just letting an open edited `config edit` just result in other commands seeing it as untrusted, though it could be very annoying for quickly trying out a bunch of edits).  
With such, there's also the possible desire of adding a timeout such that it can't get perma-stuck trusted, but that ends up being rather confusing if actually encountered.  
That said, tracking editing status has a potential minor upside (or downside depending on desired usage, I guess) of being able to warn a user when they edit the same config from multiple places.

**Comment by matts1** [comment]
It took me a while to understand @yuja's comment, but I now do after reading the linked bug. The problem is:
1) jj config edit in one terminal
2) Make changes in my editor
3) Save the config (but don't quit the editor)
4) The config is now unapproved but written to disk
5) I expect to be able to test this (currently unapproved) config by running a jj command

I don't think this is technically difficult to solve, it's mostly just a UX decision with a few suboptimal options. Our options to solve this could be:
* Keep it as is
  * I'm not a huge fan of this option. I do agree with the concerns raised, and I never really liked having the config stored out of repo (just didn't have a better option).
* Ignore the config mid-edit
  * This isn't great from a UX perspective, users probably do have an expectation
* Trust mid-edit config
  * I think this is *mostly* fine. My main concern would be if a jj command is automatically run or something.
* Ignore the config mid-edit, but if they try and use a config mid-edit, print out a hint like `Config is actively being edited and may pose a security risk, run jj with "--ignore-mid-edit-config" to confirm`.
  * This could avoid the timeout issue that @dzaima brought up

I think the last two options are both pretty reasonable. I think the last option might be the best given that we wouldn't have to implement timeouts

**Comment by senekor** [comment]
Another idea: For `jj config edit`, copy the config to a tmpfile first, then start the editor on that as well as a file watcher. Whenever the file is saved, copy it to the real location and store its hash as trusted. That way, there is no risk of the "trust everything while editing" state getting stuck, which would reduce security. It's a bit more effort & complicated though.

Maybe the file watcher could even be used to immediately communicate errors to the user if the config is invalid. How jj would communnicate to the user while the editor is open, I'm not sure. Maybe a little TUI where the editor is temporarily shrunk in size to make space for jj to display an error message at the bottom? But that's just a luxury UX idea, shouldn't be part of a first step back to in-repo config files.
