### PR TITLE
metaedit: fix timestamp in help text

### LINKED ISSUE #8421: `jj metaedit --author-timestamp` incorrect help text
## Description

`jj metaedit --author-timestamp` doesn't accept the date given in the help text (currently: `Sun, 23 Jan 2000 01:23:45 JST`)

## Steps to Reproduce the Problem

1. `jj metaedit --author-timestamp "Sun, 23 Jan 2000 01:23:45 JST"`

## Expected Behavior

Succeeds, changes author date.

## Actual Behavior

```
error: invalid value '23 Jan 2000 01:23:45 JST' for '--author-timestamp <AUTHOR_TIMESTAMP>': input contains invalid characters
```

## Specifications

- Version: 0.36.0

### PR DESCRIPTION
**Pull request by bryceberger**
rfc2822, and by extension chrono's parser for rfc2822, only supports a limited number of timezones (4.3, "Obsolete Date and Time"). JST is not one of the enumerated zones.

Current fix is to just use a supported time zone in the example. It's still possible to use a non-enumerated timezone with a human-readable format by giving the timezone offset directly (`-0800` for PST).

fixes #8421

# Checklist

If applicable:

- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/src/commands/metaedit.rs [hunk 1]
```diff
@@ -94,8 +94,12 @@ pub(crate) struct MetaeditArgs {
     author: Option<(String, String)>,
 
     /// Set the author date to the given date either human
-    /// readable, eg Sun, 23 Jan 2000 01:23:45 JST) or as a time stamp, eg
-    /// 2000-01-23T01:23:45+09:00)
+    /// readable, ([RFC2822], eg 'Sun, 23 Jan 2000 01:23:45 PST') or as a time
+    /// stamp ([RFC3339], eg '2000-01-23T01:23:45-08:00').
```
Comment (yuja) [inline cli/src/commands/metaedit.rs]: nit: it's probably better to split the syntax details to new paragraph to kepp `jj metaedit -h` short.

**Review by yuja — APPROVED** [review]
Thanks.

Just for reference, there are open PRs to migrate date library to jiff.
https://github.com/jj-vcs/jj/pulls?q=is%3Apr+is%3Aopen+jiff

**Comment by bryceberger** [comment]
> open PRs to migrate date library to jiff

Verified the original help text is incorrect under jiff as well. Specifically, the timezone `JST` is treated as `-0000` instead of `+0900` (see https://github.com/BurntSushi/jiff/blob/2ef6045d57f530680e1b79a663c0490459b74c6b/src/fmt/rfc2822.rs#L908)
