### PR TITLE
arrange: make rows as high as needed for template

### LINKED ISSUE #9291: `template.arrange` config accepts values that clobber TUI output
## Description
It seems that the implicit assumption of `jj arrange` allocating at most 2 lines per change is not documented or accounted or when one sets a template requiring more lines.

## Steps to Reproduce the Problem
1. `jj git init`
1. `for i in {1..5}; do jj new; done`
1. `jj config set --repo templates.arrange builtin_log_detailed`
1. `jj arrange`

## Expected Behavior
There are a few I can think of:
1. The TUI emits a warning or error that the template can't be used, suggests `builtin_log_oneline`/`builtin_log_compact`/some equivalent template using no more than 2 lines and closes after the first commit resulted in more than 2 lines being written. Annoying, but explicit.
1. The TUI properly clears the space of a commit before drawing each commit. This would reduce the clobbering of the upper entries by simply making them appear truncated. This doesn't feel like a good solution.
1. The TUI dynamically allocates difference sizes for the selected changes depending on the template output. This seems like the most correct to me, but I'm unsure how easy the TUI framework we use makes it possible to do that. (I don't know if the selection list is some prebuilt component or if we would have to build our own for this).

## Actual Behavior
The TUI draws the log templates as expected, but because the size of the log is fixed the upper entries are overridden partially. Here's an example of how that looks:
```
▶ ○         keep      Commit ID: 2539a742408be17b057c4a449aba089f68b42fa9
  │                   Change ID: spuulwnvkqolpxpwymvqpvyoplkqtkxp
  ○         keep      Commit ID: 0e35ac31790687a8323c4d5fd8fc6824e12c44c59:10:02)
  │                   Change ID: yuonwwtkxxnwuxwkxvnrprkrwkvmrtvt-04-10 09:10:02)
  ○         keep      Commit ID: c11d23f9289cb7306eccc0f7a39d299409f013c19:10:02)
  │                   Change ID: xwvlwvnmorrzoomsopmlvssusykvulrm-04-10 09:10:02)
  ○         keep      Commit ID: 346ad1294d6b05dc8818e996e115266f025b2b669:10:02)
  │                   Change ID: qsvtlupxlksknqrmvwrlunuoqsyvlqpx-04-10 09:10:02)
  ○         keep      Commit ID: 5b611ceac16a3fde547d5b10daca24209ea74af59:10:02)
  │                   Change ID: prpslqzmuuqsknmpopypzzpttokprtsn-04-10 09:10:02)
  ○         keep      Commit ID: 5708914339b4528ad67ee532b1040e676570a7529:10:02)
  │                   Change ID: kstnvnzxzrpotkqkkolrmopzozmkwyzv-04-10 09:10:02)
  ~                   Author   : tinger <tinger@tinger.dev> (2026-04-10 09:09:55)
                      Committer: tinger <tinger@tinger.dev> (2026-04-10 09:09:55)

                          (no description set)
```

## Specifications
- Platform: Arch Linux (uname: `Linux ... 6.19.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Mar 2026 19:20:28 +0000 x86_64 GNU/Linux`)
- Version: `jj 0.39.0-d9689cd9b51b4139d2842fcf6c30f65f4eed8cd1`

### PR DESCRIPTION
**Pull request by martinvonz**
Fixes #9291.

# Checklist

If applicable:

- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [ ] I have added/updated tests to cover my changes
- [ ] I fully understand the code that I am submitting (what it does,
      how it works, how it's organized), including any code drafted by an LLM.
- [ ] For any prose generated by an LLM, I have proof-read and copy-edited with
      an eye towards deleting anything that is irrelevant, clarifying anything
      that is confusing, and adding details that are relevant. This includes,
      for example, commit descriptions, PR descriptions, and code comments.

### CODE REVIEW

File: cli/src/commands/arrange.rs [hunk 1]
```diff
@@ -629,6 +621,18 @@ fn render(
         drop(formatter);
         let text = ansi_to_tui::IntoText::into_text(&text_lines).unwrap();
         frame.render_widget(text, text_area);
+
+        // Make graph as tall as the text
+        let graph_message = text_lines.lines().map(|_| "").join("\n");
```
Comment (yuja) [inline cli/src/commands/arrange.rs]: nit: `"\n".repeat()` also works

**Review by yuja — APPROVED** [review]

File: cli/src/commands/arrange.rs (hunk 1 above)
Comment (martinvonz) [reply cli/src/commands/arrange.rs]: Ah, that's better. Done.
