### PR TITLE
parallelize: only check to-be-rewritten commits for rewritability

### LINKED ISSUE #6587: `jj parallelize` checks all commits for rewritability rather than only to-be-rewritten
## Description

I originally posted this [on the Discord](https://discord.com/channels/968932220549103686/1374100251459457037) for confirmation there was a bug.

> ```shell
> $ jj log
> @  ccc 333  (empty) (no description set)
> ◆  bbb 222  an unrelated local change
> ◆  aaa 111  A-PUSHED-BRANCH | some feature
> ```
> I wanted to parallelize `bbb` from `aaa` and after checking `jj help parallelize`, I ran:
> ```shell
> $ jj parallelize bbb aaa
> Error: Commit 111 is immutable
> Hint: Could not modify commit: aaa 111 A-PUSHED-BRANCH | some feature
> Hint: Immutable commits are used to protect shared history.
> Hint: For more information, see:
>       - https://jj-vcs.github.io/jj/latest/config/#set-of-immutable-commits
>       - `jj help -k config`, "Set of immutable commits"
> Hint: This operation would rewrite 1 immutable commits.
> ```
> (in case it matters I also tried with the args reversed, `aaa bbb` with the same result)
> 
> I was surprised to see this as I was not expecting to need to rewrite `aaa`. I ran it with `--ignore-immutable` and as far as I can tell it did exactly what I was hoping and did _not_ rewrite or change `aaa`/`111`:
> ```shell
> $ jj parallelize bbb aaa --ignore-immutable
> Working copy  (@) now at: ccc 555  (empty) (no description set)
> Parent commit (@-)      : aaa 111  A-PUSHED-BRANCH | some feature
> Parent commit (@-)      : bbb 444  an unrelated local change
> 
> $ jj log
> @    ccc 555  (empty) (no description set)
> ├─╮
> │ ○  bbb 444  an unrelated local change
> ◆ │  aaa 111  A-PUSHED-BRANCH | some feature
> ├─╯
> ```
> relevant config:
> ```toml
> [revset-aliases]
> # prevent changing pushed or other-author commits
> "immutable_heads()" = "builtin_immutable_heads() | remote_bookmarks() | (trunk().. & ~mine())"
> ```
> If needed can also try to make a small repro repo with actual values

(↑ note this is scrollable)

`@bryce_.` on the Discord [responded](https://discord.com/channels/968932220549103686/1374100251459457037/1374109148555382847) with the following thoughts:
> For parallelize, we currently check the entire set for rewritability, but only commits that are descendants of others in the set need to be rewritable. Specifically, for some revset `x`, I think we just need `x+:: & x` to be mutable

> Or, maybe simpler `x ~ roots(x)`

## Steps to Reproduce the Problem

1. Try to parallelize changes including one that is immutable and should be unchanged
2. Observe that an error is thrown about the immutable commit
3. Observe that running with `--ignore-immutable` works as expected and does not mutate the immutable change

## Expected Behavior

No error is thrown and the parallelize completes successfully, rewriting commits that are needed but not the immutable one (which is not necessary).

## Actual Behavior

Error is thrown.

## Specifications

- Platform:
```shell
$ sw_vers
ProductName:		macOS
ProductVersion:		15.3.2
BuildVersion:		24D81
```

- Version:
```shell
$ jj --version
jj 0.28.2
```

### PR DESCRIPTION
**Pull request by bryceberger**
closes #6587

Given a commit history like this:
```
○  ccc
○  bbb
◆  aaa
```

Parallelize *should* be able to create this:
```
○  ccc
│ ○  bbb
├─╯
│ ◆  aaa
├─╯
```

This is fine because `aaa` will not be rewritten --- its children will, but neither `aaa`'s parents nor author information needs to be changed.

However, the current implementation checks _all_ commits in the target set for rewritability, instead of only the commits that will be rewritten.

This commit changes that. Now, only the commits whose parents *will* change are checked for rewritability.

# Checklist

If applicable:

- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (`README.md`, `docs/`, `demos/`)
- [ ] I have updated the config schema (`cli/src/config-schema.json`)
- [x] I have added/updated tests to cover my changes

### CODE REVIEW

File: cli/tests/test_parallelize_command.rs [hunk 1]
```diff
@@ -664,6 +664,115 @@ fn test_parallelize_complex_nonlinear_target() {
...
+    │ ○  6411b5818334 x2 parents: x1
+    │ ○  6d01ab1fb731 x1 parents: x
+    │ ◆  8ceb28e1dc31 x parents:
+    ├─╯
+    ◆  000000000000 parents:
+    [EOF]
+    ");
+
+    work_dir
+        .run_jj(["parallelize", "description(x)::", "description(y)::"])
```
Comment (martinvonz) [inline cli/tests/test_parallelize_command.rs:708]: nit: since `description()` uses substring matching by default, you can drop the `::` operators

**Review by martinvonz — APPROVED** [review]

File: cli/tests/test_parallelize_command.rs [hunk 2]
```diff
@@ -664,6 +664,115 @@ fn test_parallelize_complex_nonlinear_target() {
...
+    insta::assert_snapshot!(get_log_output(&work_dir), @r"
+    @  d6c30fecfe88 x3 parents: x2
+    ○  6411b5818334 x2 parents: x1
+    ◆  6d01ab1fb731 x1 parents: x
+    ◆  8ceb28e1dc31 x parents:
+    ◆  000000000000 parents:
+    [EOF]
+    ");
+
+    let output = work_dir.run_jj(["parallelize", "description(x)::"]);
```
Comment (martinvonz) [inline cli/tests/test_parallelize_command.rs:761]: nit: drop the `::` here too for consistency. should work, right?
