### PR TITLE
git: skip running pre-push hooks when subprocessing to match git2 behaviour

### LINKED ISSUE #5610: Git operations with `git.subprocess=true` fail if hook prints unexpected text
JJ should ignore hooks when `git.subprocess=true`, since some of my Git hooks output information.

Example:

```
$ jj git push
Changes to push to origin:
  Move sideways bookmark zx8/ntmyzyrvtzwu from 7de2273ab713 to 1febf55ed2b2
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
Error: Git process failed: Git push output unfamiliar:

 ␛[1;97mhttps://github.com/zx8/jj/commit/1febf55␛[0m

To github.com:zx8/jj.git
+ 1febf55ed2b2a07dc1aaed40bcaed10f672ec532:refs/heads/zx8/ntmyzyrvtzwu 7de2273...1febf55 (forced update)
Done

```

I think disabling Git hooks via the following might help:

```
git -c core.hooksPath=/dev/null
```

### PR DESCRIPTION
**Pull request by bsdinis**
This fixes #5610

### CODE REVIEW

File: lib/src/git_subprocess.rs [hunk 1]
```diff
@@ -205,7 +205,8 @@ impl<'a> GitSubprocessContext<'a> {
     ) -> Result<(Vec<String>, Vec<String>), GitSubprocessError> {
         let mut command = self.create_command();
         command.stdout(Stdio::piped());
-        command.args(["push", "--porcelain"]);
+        // we use --no-verify to skip the pre-push hooks
```
Comment (arxanas) [inline lib/src/git_subprocess.rs:208]: suggestion: Do we actually _want_ to skip the pre-push hooks in the long-term? I had imagined that we did want to run them. Let's update the comment to explain whether or not this is the end goal.

Comment (PhilipMetzger) [reply lib/src/git_subprocess.rs:208]: See the discussion in Discord.

Comment (PhilipMetzger) [reply lib/src/git_subprocess.rs:208]: I argue against this until #405 and #3577 are somewhat solved.

Comment (bsdinis) [reply lib/src/git_subprocess.rs:208]: I think we do want to run pre-push hooks in the long term. However, it seems that there are some design considerations to take into account.

I am happy to expand on this in the comment, but since this is a bug that has hit our users, we should merge the solution that matches the behaviour that exists elsewhere

**Review by martinvonz — APPROVED** [review]
LGTM, but let's give @arxanas a chance to object before merging.

**Review by arxanas — APPROVED** [review]
To be clear, for this PR, I just wanted to update the comment to specify that it's an intermediate state of indecision rather than the ultimate state, rather than make any specific decision about `pre-push` hooks right now. It looks good to me now that the comment includes references to the relevant issues.

**Comment by arxanas** [comment]
> Let's update the comment to explain whether or not this is the end goal.

Oops, I see now that I didn't write what I wanted to write. Originally, I wrote something like "let's update the comment to say that this is not the end goal", but then I realized we technically did not have agreement on whether it was or wasn't the end goal, so I tried to adjust the wording, and did so wrongly.
